### ISSUE TITLE
[package] libbacktrace/cci.20210118: Bug when using Conan 2 profile mode

### ISSUE THREAD

**Issue by mscofield0** [conan-io/conan-center-index#10167]
### Package
  * Package Name/Version: **libbacktrace/cci.20210118**

### Steps to reproduce (Include if Applicable)
Specify both the host profile and the build profile in `conan create`.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: Traceback (most recent call last):
    File "conans\model\user_info.py", line 15, in __getattr__
    KeyError: 'compile'
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "conans\errors.py", line 34, in conanfile_exception_formatter
      File "conans\client\conanfile\build.py", line 16, in run_build_method
      File ".conan\data\libbacktrace\cci.20210118\_\_\export\conanfile.py", line 108, in build
        with self._build_context():
      File "contextlib.py", line 81, in __enter__
      File ".conan\data\libbacktrace\cci.20210118\_\_\export\conanfile.py", line 73, in _build_context
        "CC": "{} cl -nologo".format(tools.unix_path(self.deps_user_info["automake"].compile)),
      File "conans\model\user_info.py", line 17, in __getattr__
    AttributeError
```

</details>

**Comment by mscofield0** [comment]
Fixed with #10168
