### ISSUE TITLE
[package] Boost/1.70.0: Impossible to install with python but without numpy

### ISSUE THREAD

**Issue by buddly27** [conan-io/conan-center-index#10953]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.70.0**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.46.2**
  * Python version: **Python 3.7.13**

### Conan profile
```
Configuration for profile default:
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

On a station with python available (but not numpy), install `boost/1.70.0` with python as follows:
```
conan install boost/1.70.0@ \
    --options=boost:without_python=False \
    --generator=cmake_find_package \
    --build
```

It will fail with the following message:
```
notice: [python-cfg] Checking for NumPy...
notice: [python-cfg] running command '/opt/hostedtoolcache/Python/3.7.13/x64/bin/python -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())"'
notice: [python-cfg] NumPy disabled. Reason:
notice: [python-cfg]   /opt/hostedtoolcache/Python/3.7.13/x64/bin/python -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())" aborted with 
notice: [python-cfg]   Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'

...
boost/1.70.0: WARN: Boost component 'numpy' is missing libraries. Try building boost with '-o boost:without_numpy'. (Option is not guaranteed to exist)
ERROR: boost/1.70.0: Error in package_info() method, line 1637
	raise ConanException("These libraries were expected to be built, but were not built: {}".format(non_built))
	ConanException: These libraries were expected to be built, but were not built: {'boost_numpy37'}
```

So it seems that numpy is properly disabled, but not removed from the "all_expected_libraries" set
https://github.com/conan-io/conan-center-index/blob/master/recipes/boost/all/conanfile.py#L1577

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
boost/1.70.0: Not found in local cache, looking in remotes...
boost/1.70.0: Trying with 'conancenter'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
boost/1.70.0: Downloaded recipe revision 0
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x[64](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:65)/bin/python" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"
zlib/1.2.12: Not found in local cache, looking in remotes...
zlib/1.2.12: Trying with 'conancenter'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
zlib/1.2.12: Downloaded recipe revision 0
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Trying with 'conancenter'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
bzip2/1.0.8: Downloaded recipe revision 0
libbacktrace/cci.20210118: Not found in local cache, looking in remotes...
libbacktrace/cci.20210118: Trying with 'conancenter'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
libbacktrace/cci.20210118: Downloaded recipe revision 0
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"
b2/4.8.0: Not found in local cache, looking in remotes...
b2/4.8.0: Trying with 'conancenter'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
b2/4.8.0: Downloaded recipe revision 0
Installing package: boost/1.70.0
Requirements
    boost/1.70.0 from 'conancenter' - Downloaded
    bzip2/1.0.8 from 'conancenter' - Downloaded
    libbacktrace/cci.20210118 from 'conancenter' - Downloaded
    zlib/1.2.12 from 'conancenter' - Downloaded
Packages
    boost/1.70.0:e5ac8ac88acdfbd3031413e771479b1873d04dd7 - Build
    bzip2/1.0.8:da606cf731e334010b0bf6e85a2a6f891b9f36b0 - Download
    libbacktrace/cci.20210118:6af9cc7cb931c5ad942174fd7838eb[65](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:66)5717c709 - Download
    zlib/1.2.12:6af9cc7cb931c5ad942174fd7838eb655717c709 - Download
Build requirements
    b2/4.8.0 from 'conancenter' - Downloaded
Build requirements packages
    b2/4.8.0:4db1be536558d833e52e862fd84d64d75c2b3656 - Download

Installing (downloading, building) binaries...
b2/4.8.0: Retrieving package 4db1be536558d833e52e862fd84d64d75c2b3656 from remote 'conancenter' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
b2/4.8.0: Package installed 4db1be536558d833e52e862fd84d64d75c2b3656
b2/4.8.0: Downloaded package revision 0
bzip2/1.0.8: Retrieving package da606cf731e334010b0bf6e85a2a6f891b9f36b0 from remote 'conancenter' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
bzip2/1.0.8: Package installed da606cf731e334010b0bf6e85a2a6f891b9f36b0
bzip2/1.0.8: Downloaded package revision 0
libbacktrace/cci.20210118: Retrieving package 6af9cc7cb931c5ad942174fd7838eb655717c709 from remote 'conancenter' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
libbacktrace/cci.20210118: Package installed 6af9cc7cb931c5ad942174fd7838eb655717c709
libbacktrace/cci.20210118: Downloaded package revision 0
zlib/1.2.12: Retrieving package 6af9cc7cb931c5ad942174fd7838eb655717c709 from remote 'conancenter' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
zlib/1.2.12: Package installed 6af9cc7cb931c5ad942174fd7838eb655717c709
zlib/1.2.12: Downloaded package revision 0
bzip2/1.0.8: Appending PATH environment variable: /home/runner/.conan/data/bzip2/1.0.8/_/_/package/da606cf731e334010b0bf6e85a2a6f891b9f36b0/bin
boost/1.70.0: Applying build-requirement: b2/4.8.0
Downloading conan_sources.tgz
boost/1.70.0: Configuring sources in /home/runner/.conan/data/boost/1.70.0/_/_/source

boost/1.70.0: Building your package in /home/runner/.conan/data/boost/1.70.0/_/_/build/e5ac8ac88acdfbd3031413e771479b1873d04dd7
boost/1.70.0: Generator txt created conanbuildinfo.txt
boost/1.70.0: Aggregating env generators
boost/1.70.0: Calling build()
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"
boost/1.[70](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:71).0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sysconfig; print(sysconfig.get_path('include'))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sysconfig; print(sysconfig.get_path('platinclude'))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sysconfig; print(sysconfig.get_config_var('INCLUDEPY'))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sysconfig; print(sysconfig.get_config_var('INCLUDEDIR'))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sysconfig; print(sysconfig.get_python_inc())"
boost/1.70.0: (failed)
boost/1.70.0: checking /opt/hostedtoolcache/Python/3.7.13/x64/include/python3.7m/Python.h
boost/1.70.0: found Python.h: /opt/hostedtoolcache/Python/3.7.13/x64/include/python3.7m/Python.h
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sysconfig; print(sysconfig.get_config_var('LIBRARY'))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sysconfig; print(sysconfig.get_config_var('LDLIBRARY'))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sysconfig; print(sysconfig.get_config_var('LIBDIR'))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sysconfig; print(sysconfig.get_config_var('MULTIARCH'))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sysconfig; print(sysconfig.get_config_var('multiarchsubdir'))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import distutils.sysconfig as du_sysconfig; print(du_sysconfig.get_config_var('multiarchsubdir'))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sysconfig; print(sysconfig.get_config_var('WITH_DYLD'))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sys; print(getattr(sys, 'abiflags', ''))"
boost/1.70.0: checking /opt/hostedtoolcache/Python/3.7.13/x64/lib/libpython3.7m.so
boost/1.70.0: found python library: /opt/hostedtoolcache/Python/3.7.13/x64/lib/libpython3.7m.so
notice: found boost-build.jam at /home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/boost-build.jam
notice: loading B2 from /home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/bootstrap.jam
warning: mismatched versions of Boost.Build engine and core
warning: Boost.Build engine (b2) is 4.8.0
warning: Boost.Build core (at /home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src) is 2018.02-git
notice: Searching '/etc' '/home/runner' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/kernel' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/util' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/build' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/tools' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/contrib' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/.' for site-config configuration file 'site-config.jam'.
notice: Configuration file 'site-config.jam' not found in '/etc' '/home/runner' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/kernel' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/util' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/build' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/tools' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/contrib' '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/src/.'.
notice: Loading explicitly specified user configuration file:
    /home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/user-config.jam
notice: Searching '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build'.
notice: [zlib] Using pre-installed library
notice: [zlib] Condition
notice: [bzip2] Using pre-installed library
notice: [bzip2] Condition
notice: [python-cfg] Configuring python...
notice: [python-cfg]   user-specified version: "3.7"
notice: [python-cfg]   user-specified cmd-or-prefix: "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python"
notice: [python-cfg]   user-specified includes: "/opt/hostedtoolcache/Python/3.7.13/x64/include/python3.7m"
notice: [python-cfg]   user-specified libraries: "/opt/hostedtoolcache/Python/3.7.13/x64/lib"
notice: [python-cfg] Details of this Python configuration:
notice: [python-cfg]   interpreter command: "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python"
notice: [python-cfg]   include path: "/opt/hostedtoolcache/Python/3.7.13/x64/include/python3.7m"
notice: [python-cfg]   library path: "/opt/hostedtoolcache/Python/3.7.13/x64/lib"
notice: [python-cfg] Checking for NumPy...
notice: [python-cfg] running command '/opt/hostedtoolcache/Python/3.7.13/x64/bin/python -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())"'
notice: [python-cfg] NumPy disabled. Reason:
notice: [python-cfg]   /opt/hostedtoolcache/Python/3.7.13/x64/bin/python -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())" aborted with 
notice: [python-cfg]   Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
notice: will use '/usr/bin/g++-9' for gcc, condition <toolset>gcc-9.4.0
notice: using gcc libraries :: <toolset>gcc-9.4.0 :: /usr/bin /usr/lib /usr/lib32 /usr/lib64
notice: using gcc archiver :: <toolset>gcc-9.4.0 :: /usr/bin/ar
notice: using gcc ranlib :: <toolset>gcc-9.4.0 :: /usr/bin/ranlib
warning: toolset gcc initialization: can not find tool windres
warning: initialized from /home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/user-config.jam:6
notice: using rc compiler :: <toolset>gcc-9.4.0 :: /usr/bin/as
notice: [zlib] zlib is already configured
notice: [bzip2] bzip is already configured
notice: iostreams: not using lzma compression 
notice: iostreams: not using zstd compression 
Performing configuration checks

    - default address-model    : 64-bit
    - default architecture     : x86
    - C++11 mutex              : yes
    - lockfree boost::atomic_flag : yes
    - Boost.Config Feature Check: cxx11_auto_declarations : yes
    - Boost.Config Feature Check: cxx11_constexpr : yes
    - Boost.Config Feature Check: cxx11_defaulted_functions : yes
    - Boost.Config Feature Check: cxx11_final : yes
    - Boost.Config Feature Check: cxx11_hdr_mutex : yes
    - Boost.Config Feature Check: cxx11_hdr_tuple : yes
    - Boost.Config Feature Check: cxx11_lambdas : yes
    - Boost.Config Feature Check: cxx11_noexcept : yes
    - Boost.Config Feature Check: cxx11_nullptr : yes
    - Boost.Config Feature Check: cxx11_rvalue_references : yes
    - Boost.Config Feature Check: cxx11_template_aliases : yes
    - Boost.Config Feature Check: cxx11_thread_local : yes
    - Boost.Config Feature Check: cxx11_variadic_templates : yes
    - has_icu builds           : no
    - zlib                     : yes
    - bzip2                    : yes
    - iconv (libc)             : yes
    - native-atomic-int32-supported : yes
    - native-syslog-supported  : yes
    - pthread-supports-robust-mutexes : yes
    - compiler-supports-ssse3  : yes
    - compiler-supports-avx2   : yes
    - gcc visibility           : yes
    - long double support      : yes
    - libbacktrace builds      : yes
    - addr2line builds         : yes
    - WinDbg builds            : no
    - WinDbgCached builds      : no
    - BOOST_COMP_GNUC >= 4.3.0 : yes

Component configuration:

    - atomic                   : building
    - chrono                   : building
    - container                : building
    - context                  : building
    - contract                 : building
    - coroutine                : building
    - date_time                : building
    - exception                : building
    - fiber                    : building
    - filesystem               : building
    - graph                    : building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : building
    - locale                   : building
    - log                      : building
    - math                     : building
    - mpi                      : not building
    - program_options          : building
    - python                   : building
    - random                   : building
    - regex                    : building
    - serialization            : building
    - stacktrace               : building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : building
    - type_erasure             : building
    - wave                     : building

boost/1.70.0: Package 'e5ac8ac88acdfbd3031413e7[71](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:72)479b18[73](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:74)d04dd7' built
boost/1.70.0: Build folder /home/runner/.conan/data/boost/1.70.0/_/_/build/e5ac8ac88acdfbd3031413e771479b1873d04dd7
boost/1.70.0: Generated conaninfo.txt
boost/1.70.0: Generated conanbuildinfo.txt
boost/1.70.0: Generating the package
boost/1.70.0: Package folder /home/runner/.conan/data/boost/1.70.0/_/_/package/e5ac8ac88acdfbd3031413e771479b1873d04dd7
boost/1.70.0: Calling package()
boost/1.70.0 package(): Packaged 40 '.a' files
boost/1.70.0 package(): Packaged 1 '.txt' file: LICENSE_1_0.txt
boost/1.70.0 package(): Packaged 13463 '.hpp' files
boost/1.70.0 package(): Packaged 146 '.h' files
boost/1.70.0 package(): Packaged 218 '.ipp' files
boost/1.70.0 package(): Packaged 2 '.inc' files: cpp_re.inc, strict_cpp_re.inc
boost/1.70.0 package(): Packaged 17 files
boost/1.70.0: Package 'e5ac8ac88acdfbd3031413e771479b1873d04dd7' created
boost/1.70.0: Created package revision 18624c9b8bbe445c12f8ac1149b14b51
boost/1.70.0: running "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" -c "from __future__ import print_function; import sys; print('{}.{}'.format(sys.version_info[0], sys.version_info[1]))"
WARN: Remotes registry file missing, creating default one in /home/runner/.conan/remotes.json
WARN: replace_in_file didn't find pattern '/* thread_local */' in '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/boost/stacktrace/detail/libbacktrace_impls.hpp' file.
WARN: replace_in_file didn't find pattern '/* static __thread */' in '/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/boost/stacktrace/detail/libbacktrace_impls.hpp' file.
boost/1.70.0: WARN: Patching user-config.jam
boost/1.70.0: WARN: 
using zlib : 1.2.12 : <include>"/home/runner/.conan/data/zlib/1.2.12/_/_/package/6af9cc7cb931c5ad9421[74](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:75)fd7838eb655717c709/include" <search>"/home/runner/.conan/data/zlib/1.2.12/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/lib" <name>z ;
using bzip2 : 1.0.8 : <include>"/home/runner/.conan/data/bzip2/1.0.8/_/_/package/da606cf731e334010b0bf6e85a2a6f891b9f36b0/include" <search>"/home/runner/.conan/data/bzip2/1.0.8/_/_/package/da606cf731e334010b0bf6e85a2a6f891b9f36b0/lib" <name>bz2 ;
using python : 3.7 : "/opt/hostedtoolcache/Python/3.7.13/x64/bin/python" : "/opt/hostedtoolcache/Python/3.7.13/x64/include/python3.7m" : "/opt/hostedtoolcache/Python/3.7.13/x64/lib" ;
using "gcc" :  :  /usr/bin/g++-9 : 
<compileflags>"-I/home/runner/.conan/data/libbacktrace/cci.20210118/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/include" <linkflags>"-L/home/runner/.conan/data/libbacktrace/cci.20210118/_/_/package/6af9cc7cb931c5ad942174fd7838eb655717c709/lib"  ;
boost/1.70.0: WARN: b2 -q numa=on target-os=linux architecture=x86 address-model=64 binary-format=elf abi=sysv --layout=system --user-config=/home/runner/.conan/data/boost/1.70.0/_/_/source/source_subfolder/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=on boost.locale.iconv.lib=libc threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-context --with-contract --with-coroutine --with-date_time --with-exception --with-fiber --with-filesystem --with-graph --with-iostreams --with-locale --with-log --with-math --with-program_options --with-python --with-random --with-regex --with-serialization --with-stacktrace --with-system --with-test --with-thread --with-timer --with-type_erasure --with-wave toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=0 pch=on  cxxflags="-fPIC -DBOOST_STACKTRACE_ADDR2LINE_LOCATION=/usr/bin/addr2line" install --prefix=/home/runner/.conan/data/boost/1.70.0/_/_/package/e5ac8ac88acdfbd3031413e[77](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:78)14[79](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:80)b1[87](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:88)3d04dd7 -j2 --abbreviate-paths -d0 --debug-configuration --build-dir="/home/runner/.conan/data/boost/1.70.0/_/_/build/e5ac8ac[88](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:89)acdfbd303[141](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:142)3e77[147](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:148)9b1873d04dd7"
boost/1.70.0: WARN: Boost component 'numpy' is missing libraries. Try building boost with '-o boost:without_numpy'. (Option is not guaranteed to exist)
ERROR: boost/1.70.0: Error in package_info() method, line [163](https://github.com/buddly27/test-build/runs/6602888156?check_suite_focus=true#step:5:164)7
	raise ConanException("These libraries were expected to be built, but were not built: {}".format(non_built))
	ConanException: These libraries were expected to be built, but were not built: {'boost_numpy37'}
Error: Process completed with exit code 1.
```
</details>

**Comment by buddly27** [comment]
Hmm it might not be only an issue with the conan config as bi-passing the check produces this linking error:
```
CMake Error at CMakeLists.txt:118 (add_executable):
  Target "numpy_exe" links to target "Boost::numpy38" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

**Comment by buddly27** [comment]
It seems to be related to this issue #8826

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `boost/1.70.0` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸

**Comment by aaronsuydam** [comment]
Hey, could anyone point me in the right direction for how to specify that I want Boost to be built with python? I've been searching for some time as to what the conanfile.txt needs to say but i can't seem to find it.

**Comment by perseoGI** [comment]
Hello @aaronsuydam, I've been looking into your question. 
To compile boost with python, for the moment, until `boost python` supports it, `numpy` is needed. See https://github.com/conan-io/conan-center-index/issues/8826#issuecomment-1026849720 for extra information.

Moreover, a version of `numpy` < 2.0 is required. This problem seems to be fixed in https://github.com/boostorg/python/pull/432 but it has not been released yet. 

All in all, to compile boost with python you can do:
```
$ conan install --requires="boost/[*]" -o "boost/*:without_python=False" --build=missing
```

There is a "on the fly boost option" called `without_numpy` which aims to disable the `numpy` component inside boost but I could not get to work. And in any case, as upstream (boost python) requires it, it will check for `numpy` in your environment so it may be easier to just have it installed.

Let me know if that worked!
