### ISSUE TITLE
[package] pkgconf/1.7.4: can't build with python 3.6

### ISSUE THREAD

**Issue by dvirtz** [conan-io/conan-center-index#11192]
### Package and Environment Details

* Package Name/Version: **pkgconf/1.7.4**
* Python version: **Python 3.6.8**

### Conan profile

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=13.0
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install -r conancenter --build pkgconf --update pkgconf/1.7.4@

### Logs

<details><summary>Click to expand log</summary>

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

pkgconf/1.7.4: Retrieving from remote 'conancenter'...
pkgconf/1.7.4: Retrieving from server 'conancenter' 
pkgconf/1.7.4: Trying with 'conancenter'...
Downloading cd2d72b9bb63c06cd822c63f8c09da319280016d6938c14ca2dc900633608474 completed [6.14k]                           
Downloading afe6e023e2538ac5190c17ca78c4dd4ea0c242c6365f83ce17cdef9310d56a87 completed [0.37k]                         
Decompressing conan_export.tgz completed [0.00k]                                         
pkgconf/1.7.4: Downloaded recipe revision cef6c1423898afb2580e10022caf3c89
pkgconf/1.7.4: Forced build from source
meson/0.62.1: Retrieving from server 'conancenter' 
meson/0.62.1: Trying with 'conancenter'...
Downloading 8e970393081cdcbc583f8936fcfd2a40b0e84cd3c3b80dd6412f31b0a26ed652 completed [0.10k]                         
Downloading f29413f9155f93217c4ec2182afd6275381054eba4eaa21f5ee134c9bb62a46a completed [2.81k]                           
Downloading 68b1ff927f1e5eda807ca0e98c5cae1799b8d56461a7a8269e6a8e87110fd34a completed [0.24k]                         
Decompressing conan_export.tgz completed [0.00k]                                         
meson/0.62.1: Downloaded recipe revision 56af587c39ed2cd866945962ed16f8b9
ninja/1.10.2: Retrieving from remote 'conancenter'...
ninja/1.10.2: Retrieving from server 'conancenter' 
ninja/1.10.2: Trying with 'conancenter'...
Downloading 86bb8dc744d0e444d19d7a4019548610562d94c3cf3d0812067a91b78e48c32d completed [1.55k]                           
Downloading 2c4af112db82acf0f25dc5ef92c9f3fe3f69bf1f88d52b616cd4cdf3355fe199 completed [0.25k]                         
Decompressing conan_export.tgz completed [0.00k]                                         
ninja/1.10.2: Downloaded recipe revision 97ca12608a00fa4b1502bf0abd7bbc3e
ninja/1.10.2: WARN: The package ninja/1.10.2:801752c0480319b8e090188c566245a78e9abcf4 doesn't belong to the installed recipe revision, removing folder
Installing package: pkgconf/1.7.4
Requirements
    pkgconf/1.7.4 from 'conancenter' - Updated
Packages
    pkgconf/1.7.4:801752c0480319b8e090188c566245a78e9abcf4 - Build
Build requirements
    meson/0.62.1 from 'conancenter' - Downloaded
    ninja/1.10.2 from 'conancenter' - Updated
Build requirements packages
    meson/0.62.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    ninja/1.10.2:801752c0480319b8e090188c566245a78e9abcf4 - Download

Installing (downloading, building) binaries...
ninja/1.10.2: Retrieving package 801752c0480319b8e090188c566245a78e9abcf4 from remote 'conancenter' 
Downloading 18b5ed41a85c78f5566ae122dae0440e04b821ea177e31011d588b654cbb7ddd completed [0.15k]                         
Downloading 5bc88b24a6dff6396d8d4fea554b84ec09d7cbda65b2994048138f965f6e540f completed [121.52k]                               
Decompressing conan_package.tgz completed [0.00k]                                        
ninja/1.10.2: Package installed 801752c0480319b8e090188c566245a78e9abcf4
ninja/1.10.2: Downloaded package revision fc9303c64b3a579025b8fe8c065196a2
meson/0.62.1: Retrieving package 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 from remote 'conancenter' 
Downloading ba818d2ed2d982e9aca36ab57442abba60319a345e816f174476d65cbb8ff0ff completed [47.95k]                          
Downloading 0b130c3cde9923f03e0d9233d120d9238fbb5344590d61fe4bc4f1d51e1d4390 completed [3457.58k]                                 
Decompressing conan_package.tgz completed [0.00k]                                        
meson/0.62.1: Package installed 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
meson/0.62.1: Downloaded package revision fe5e945ad79944c4e843d2512a7d4c83
[HOOK - conan-recipes.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
ninja/1.10.2: WARN: Lib folder doesn't exist, can't collect libraries: /Users/dyitzchaki/.conan/data/ninja/1.10.2/_/_/package/801752c0480319b8e090188c566245a78e9abcf4/lib
[HOOK - conan-recipes.py] post_package_info(): [LIBRARY DOES NOT EXIST (KB-H054)] OK
meson/0.62.1: Appending PATH environment variable: /Users/dyitzchaki/.conan/data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin
[HOOK - conan-recipes.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
meson/0.62.1: WARN: Lib folder doesn't exist, can't collect libraries: /Users/dyitzchaki/.conan/data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/lib
[HOOK - conan-recipes.py] post_package_info(): [LIBRARY DOES NOT EXIST (KB-H054)] OK
pkgconf/1.7.4: Applying build-requirement: meson/0.62.1
pkgconf/1.7.4: Applying build-requirement: ninja/1.10.2
Downloading 1d97907d6ab7113398078dd7d62ac098d615efe1ecdaa66553c0315c7cf540fb completed [1.17k]                           
Decompressing conan_sources.tgz completed [0.00k]                                        
[HOOK - conan-recipes.py] pre_source(): [IMMUTABLE SOURCES (KB-H010)] OK
pkgconf/1.7.4: Configuring sources in /Users/dyitzchaki/.conan/data/pkgconf/1.7.4/_/_/source
Downloading 61c1b47ced1508f0c9bd1c98b732cf0cd76e1c11c7c43b88bcec55862e644e1a completed [287.00k]                               

[HOOK - conan-recipes.py] post_source(): [LIBCXX MANAGEMENT (KB-H011)] OK
[HOOK - conan-recipes.py] post_source(): [CPPSTD MANAGEMENT (KB-H022)] OK
pkgconf/1.7.4: Copying sources to build folder
pkgconf/1.7.4: Building your package in /Users/dyitzchaki/.conan/data/pkgconf/1.7.4/_/_/build/801752c0480319b8e090188c566245a78e9abcf4
pkgconf/1.7.4: Generator txt created conanbuildinfo.txt
pkgconf/1.7.4: Aggregating env generators
[HOOK - conan-recipes.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
[HOOK - conan-recipes.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
pkgconf/1.7.4: Calling build()
Traceback (most recent call last):
  File "/Users/dyitzchaki/.conan/data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/meson.py", line 26, in <module>
    from mesonbuild import mesonmain
  File "/Users/dyitzchaki/.conan/data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/mesonmain.py", line 28, in <module>
    from . import mesonlib
  File "/Users/dyitzchaki/.conan/data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/mesonlib/__init__.py", line 21, in <module>
    from .universal import *
  File "/Users/dyitzchaki/.conan/data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/mesonlib/universal.py", line 17
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
pkgconf/1.7.4: 
pkgconf/1.7.4: ERROR: Package '801752c0480319b8e090188c566245a78e9abcf4' build failed
pkgconf/1.7.4: WARN: Build folder /Users/dyitzchaki/.conan/data/pkgconf/1.7.4/_/_/build/801752c0480319b8e090188c566245a78e9abcf4
ERROR: pkgconf/1.7.4: Error in build() method, line 101
        meson = self._configure_meson()
while calling '_configure_meson', line 84
        meson.configure(source_folder=self._source_subfolder, build_folder=self._build_subfolder)
        ConanException: Error 1 while executing meson "/Users/dyitzchaki/.conan/data/pkgconf/1.7.4/_/_/build/801752c0480319b8e090188c566245a78e9abcf4/source_subfolder" "/Users/dyitzchaki/.conan/data/pkgconf/1.7.4/_/_/build/801752c0480319b8e090188c566245a78e9abcf4/build_subfolder" --backend=ninja -Dprefix="/Users/dyitzchaki/.conan/data/pkgconf/1.7.4/_/_/package/801752c0480319b8e090188c566245a78e9abcf4" -Dlibdir="lib" -Dbindir="bin" -Dsbindir="bin" -Dlibexecdir="bin" -Dincludedir="include" -Ddefault_library="static" -Dtests="False" -Dsharedstatedir="/Users/dyitzchaki/.conan/data/pkgconf/1.7.4/_/_/package/801752c0480319b8e090188c566245a78e9abcf4/bin/share" --buildtype=release```

</details>

**Comment by dvirtz** [comment]
the [FAQ](https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-is-the-policy-for-supported-python-versions) states that python 3.6 should be supported by recipes.
meson dropped support for 3.6 however since 0.62.0: https://github.com/mesonbuild/meson/pull/9510

**Comment by Croydon** [comment]
Also generally spoken, the mentioned Python support only reflects what kind of language features we use directly within recipes. It does not reflect the Python support of some packages themselves.
