### ISSUE TITLE
[package] pkgconf/1.7.4: SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/conan-center-index#11599]
### Package and Environment Details

* Package Name/Version: **pkgconf/1.7.4**
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **GCC 7**
* Conan version: **conan 1.49.0**
* Python version: **Python 3.6.9**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=armv8
arch_build=armv8
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install pkgconf/1.7.4@ --build=missing

### Logs

<details><summary>Click to expand log</summary>

```
Traceback (most recent call last):
  File "/data/.data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/meson.py", line 26, in <module>
    from mesonbuild import mesonmain
  File "/data/.data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/mesonmain.py", line 28, in <module>
    from . import mesonlib
  File "/data/.data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/mesonlib/__init__.py", line 21, in <module>
    from .universal import *
  File "/data/.data/meson/0.62.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/mesonlib/universal.py", line 17
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
pkgconf/1.7.4: WARN: Package binary is corrupted, removing: 1a032419479e0fe8660712050df2775c495d3123
pkgconf/1.7.4: WARN: Build folder is dirty, removing it: /data/.data/pkgconf/1.7.4/_/_/build/1a032419479e0fe8660712050df2775c495d3123
pkgconf/1.7.4: ERROR: Package '1a032419479e0fe8660712050df2775c495d3123' build failed
pkgconf/1.7.4: WARN: Build folder /data/.data/pkgconf/1.7.4/_/_/build/1a032419479e0fe8660712050df2775c495d3123
ERROR: pkgconf/1.7.4: Error in build() method, line 101
        meson = self._configure_meson()
while calling '_configure_meson', line 84
        meson.configure(source_folder=self._source_subfolder, build_folder=self._build_subfolder)
        ConanException: Error 1 while executing meson "/data/.data/pkgconf/1.7.4/_/_/build/1a032419479e0fe8660712050df2775c495d3123/source_subfolder" "/data/.data/pkgconf/1.7.4/_/_/build/1a032419479e0fe8660712050df2775c495d3123/build_subfolder" --backend=ninja -Dprefix="/data/.data/pkgconf/1.7.4/_/_/package/1a032419479e0fe8660712050df2775c495d3123" -Dlibdir="lib" -Dbindir="bin" -Dsbindir="bin" -Dlibexecdir="bin" -Dincludedir="include" -Ddefault_library="static" -Dtests="False" -Dsharedstatedir="/data/.data/pkgconf/1.7.4/_/_/package/1a032419479e0fe8660712050df2775c495d3123/bin/share" --buildtype=release
```

</details>

**Comment by Tumb1eweed** [comment]
it urns out, pkgconf requires python3 >= 3.7

**Comment by Croydon** [comment]
Duplicate https://github.com/conan-io/conan-center-index/issues/11192
