### ISSUE TITLE
boost: support `tools.build:jobs={{max(1, os.cpu_count()-2)}}`

### ISSUE THREAD

**Issue by blockspacer** [conan-io/conan-center-index#12737]
### Package and Environment Details

* Package Name/Version: **boost/1.71.0**
* Operating System+version: **Windows 10**
* Compiler+version: **clang-cl**
* Docker image: **no**
* Conan version: **conan 1.51.3**
* Python version: **Python 3.10.5**

### Conan profile

```
toolchain_arch=x86_64

[settings]
# Tested in Windows 10
os=Windows
os_target=Windows
os_build=Windows
arch_build=$toolchain_arch
arch=$toolchain_arch
compiler=clang
compiler.version=14
# Must match CMAKE_BUILD_TYPE
# NOTE: do not forget to select Debug or Release compiler.runtime
build_type=Debug
# runtime:
# /MDd - Multi threaded Debug DLL
# /MD - Multi threaded DLL
# If you use /MT, your executable won't depend on a DLL being present on the target system. 
# If you're wrapping this in an installer, it probably won't be an issue and you can go either way.
# /MTd - Multi threaded Debug
# /MT - Multi threaded
compiler.runtime=MTd
# compiler.libcxx=libstdc++11

[options]
[tool_requires]
cmake/[>=3.23]
ninja/[>=1.11]
ccache/[>=4.6]
[build_requires]
[conf]
tools.build:jobs={{max(1, os.cpu_count()-2)}}
tools.files.download:retry=3
tools.files.download:retry_wait=5
tools.system.package_manager:tool="choco"
[env]
CONAN_CMAKE_GENERATOR=Ninja
CONAN_REVISIONS_ENABLED=1
CONAN_VERBOSE_TRACEBACK=1
CONAN_PRINT_RUN_COMMANDS=1
CONAN_LOGGING_LEVEL=10
CONAN_USE_ALWAYS_SHORT_PATHS=1
# NOTE: usually path is C:\PROGRA~1\LLVM\bin\clang-cl.exe
CC="C:\Program Files\LLVM\bin\clang-cl.exe"
CXX="C:\Program Files\LLVM\bin\clang-cl.exe"
LDFLAGS="-fuse-ld=lld-link"
AR="C:\Program Files\LLVM\bin\llvm-ar.exe"
RANLIB="C:\Program Files\LLVM\bin\llvm-ranlib.exe"
```

### Steps to reproduce

run conan create for boost with `tools.build:jobs={{max(1, os.cpu_count()-2)}}` in conan profile

```
expected int but got string from `tools.build:jobs={{max(1, os.cpu_count()-2)}}`

see 
                    command = f"{self._b2_exe} -j{build_jobs(self)} --abbreviate-paths toolset={self._toolset}"
and
        flags.extend([
            "install",
            f"--prefix={self.package_folder}",
            f"-j{build_jobs(self)}",
            "--abbreviate-paths",
            "-d%d" % self.options.debug_level,
        ])
```

### Logs

<details><summary>Click to expand log</summary>

```
expected int but got string from `tools.build:jobs={{max(1, os.cpu_count()-2)}}`

see 
                    command = f"{self._b2_exe} -j{build_jobs(self)} --abbreviate-paths toolset={self._toolset}"
and
        flags.extend([
            "install",
            f"--prefix={self.package_folder}",
            f"-j{build_jobs(self)}",
            "--abbreviate-paths",
            "-d%d" % self.options.debug_level,
        ])
```

</details>

**Comment by uilianries** [comment]
This is not a package problem, but a Conan client bug.

I gonna transfer this issue to conan-io/conan.

This feature it's documented on Docs:

https://docs.conan.io/en/latest/reference/config_files/global_conf.html#configuration-file-template

https://docs.conan.io/en/latest/reference/conanfile/tools/build.html#conan-tools-build-build-jobs

For better reproduction:

#### Steps

```python
from conan import ConanFile
from conan.tools.build import build_jobs

class FooConan(ConanFile):
    def configure(self):
        cpucount = build_jobs(self)
        self.output.info(f"**** CPUCOUNT: {type(cpucount)}")
        self.output.info(f"**** CPUCOUNT: {cpucount}")
```

    conan profile update 'conf.tools.build:jobs={{os.cpu_count()}}' default 
    conan create . foo/0.1@  -pr:b=default -pr:h=default


#### Output:

```
foo/0.1: Exported revision: e32b23a17d67db859472a46a6ceb3e0b
Configuration (profile_host):
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
[conf]
tools.build:jobs={{os.cpu_count()}}

Configuration (profile_build):
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
[conf]
tools.build:jobs={{os.cpu_count()}}

ERROR: Traceback (most recent call last):
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conans/client/conanfile/configure.py", line 27, in run_configure_method
    conanfile.configure()
  File "/Users/uilian/.conan/data/foo/0.1/_/_/export/conanfile.py", line 10, in configure
    cpucount = build_jobs(self)
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conan/tools/build/cpu.py", line 9, in build_jobs
    njobs = conanfile.conf.get("tools.build:jobs",
  File "/Users/uilian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/conans/model/conf.py", line 246, in get
    raise ConanException("[conf] {name} must be a {type}-like object. "
conans.errors.ConanException: [conf] tools.build:jobs must be a int-like object. The value '{{os.cpu_count()}}' introduced is a str object
```

#### Environment

- Conan 1.52.0 (Same result for 1.51.3)
- OS: OSX 12.5.1
- Arch: aarch64

**Comment by uilianries** [comment]
I Have no permission to transfer. I gonna this issue and open a new one in Conan client.
