### ISSUE TITLE
[package] double-conversion/3.1.4: clang-cl support

### ISSUE THREAD

**Issue by blockspacer** [conan-io/conan-center-index#12760]
### Package and Environment Details

* Package Name/Version: **double-conversion/3.1.4**
* Operating System+version: **Windows 10**
* Compiler+version: **clang-cl**
* Docker image: **no**
* Conan version: **conan 1.51.3**
* Python version: **Python 3.10.5**

### Conan profile

toolchain_arch=x86_64

[settings]
# Tested in Windows 10
os=Windows
os_target=Windows
os_build=Windows
arch_build=$toolchain_arch
arch=$toolchain_arch
compiler=clang
compiler.version=14
# Must match CMAKE_BUILD_TYPE
# NOTE: do not forget to select Debug or Release compiler.runtime
build_type=Debug
# runtime:
# /MDd - Multi threaded Debug DLL
# /MD - Multi threaded DLL
# If you use /MT, your executable won't depend on a DLL being present on the target system. 
# If you're wrapping this in an installer, it probably won't be an issue and you can go either way.
# /MTd - Multi threaded Debug
# /MT - Multi threaded
compiler.runtime=MTd
# compiler.libcxx=libstdc++11
# compiler.threads=win32

[options]
[tool_requires]
cmake/[>=3.23]
ninja/[>=1.11]
ccache/[>=4.6]
[build_requires]
[conf]
# tools.build:jobs={{max(1, os.cpu_count()-2)}}
tools.files.download:retry=3
tools.files.download:retry_wait=5
tools.system.package_manager:tool="choco"
[env]
CONAN_CMAKE_GENERATOR=Ninja
CONAN_REVISIONS_ENABLED=1
CONAN_VERBOSE_TRACEBACK=1
CONAN_PRINT_RUN_COMMANDS=1
CONAN_LOGGING_LEVEL=10
CONAN_USE_ALWAYS_SHORT_PATHS=1
# NOTE: usually path is C:\PROGRA~1\LLVM\bin\clang-cl.exe
CC=clang-cl.exe
CXX=clang-cl.exe

### Steps to reproduce

run conan create for double-conversion/3.1.4 with clang-cl profile

### Logs

<details><summary>Click to expand log</summary>

```
double-conversion/3.1.4: Applying build-requirement: cmake/3.23.1
double-conversion/3.1.4: Applying build-requirement: ninja/1.11.0
double-conversion/3.1.4: Applying build-requirement: ccache/4.6
double-conversion/3.1.4: Applying build-requirement: zstd/1.5.2
double-conversion/3.1.4: Applying build-requirement: hiredis/1.0.2
double-conversion/3.1.4: WARN: Build folder is dirty, removing it: C:\Users\den00\.conan\data\double-conversion\3.1.4\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2
double-conversion/3.1.4: Copying sources to build folder
double-conversion/3.1.4: Building your package in C:\Users\den00\.conan\data\double-conversion\3.1.4\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2
double-conversion/3.1.4: Generator txt created conanbuildinfo.txt
double-conversion/3.1.4: Calling generate()
double-conversion/3.1.4: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
double-conversion/3.1.4: Aggregating env generators
double-conversion/3.1.4: Calling build()
double-conversion/3.1.4: CMake command: cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="C:/Users/den00/.conan/data/double-conversion/3.1.4/_/_/build/0974a5b97849875d7301803ccabc46a5c139aab2/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/den00/.conan/data/double-conversion/3.1.4/_/_/package/0974a5b97849875d7301803ccabc46a5c139aab2" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "C:\Users\den00\.conan\data\double-conversion\3.1.4\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2\src"
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
double-conversion/3.1.4:
double-conversion/3.1.4: ERROR: Package '0974a5b97849875d7301803ccabc46a5c139aab2' build failed
double-conversion/3.1.4: WARN: Build folder C:\Users\den00\.conan\data\double-conversion\3.1.4\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2\build\Debug
ERROR: Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\conans\errors.py", line 34, in conanfile_exception_formatter
    yield
  File "C:\Python310\lib\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method
    conanfile.build()
  File "C:\Users\den00\.conan\data\double-conversion\3.1.4\_\_\export\conanfile.py", line 56, in build
    cmake.configure()
  File "C:\Python310\lib\site-packages\conan\tools\cmake\cmake.py", line 97, in configure
    self._conanfile.run(command)
  File "C:\Python310\lib\site-packages\conans\model\conan_file.py", line 443, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 1 while executing cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE="C:/Users/den00/.conan/data/double-conversion/3.1.4/_/_/build/0974a5b97849875d7301803ccabc46a5c139aab2/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/den00/.conan/data/double-conversion/3.1.4/_/_/package/0974a5b97849875d7301803ccabc46a5c139aab2" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "C:\Users\den00\.conan\data\double-conversion\3.1.4\_\_\build\0974a5b97849875d7301803ccabc46a5c139aab2\src"

```

</details>

**Comment by blockspacer** [comment]
UPD:

`cmake -G "MinGW Makefiles"`` fixed by adding 

```
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```

For some reason package ignores

```
[env]
CONAN_CMAKE_GENERATOR=Ninja
```

**Comment by blockspacer** [comment]
Now i get other build error:

```
double-conversion/3.1.4@conan/stable: Applying build-requirement: cmake/3.23.1
double-conversion/3.1.4@conan/stable: Applying build-requirement: ninja/1.11.0
double-conversion/3.1.4@conan/stable: Applying build-requirement: ccache/4.6
double-conversion/3.1.4@conan/stable: Applying build-requirement: zstd/1.5.2
double-conversion/3.1.4@conan/stable: Applying build-requirement: hiredis/1.0.2
double-conversion/3.1.4@conan/stable: WARN: Build folder is dirty, removing it: C:\Users\den00\.conan\data\double-conversion\3.1.4\conan\stable\build\0974a5b97849875d7301803ccabc46a5c139aab2
double-conversion/3.1.4@conan/stable: Copying sources to build folder
double-conversion/3.1.4@conan/stable: Building your package in C:\Users\den00\.conan\data\double-conversion\3.1.4\conan\stable\build\0974a5b97849875d7301803ccabc46a5c139aab2
double-conversion/3.1.4@conan/stable: Generator txt created conanbuildinfo.txt
double-conversion/3.1.4@conan/stable: Calling generate()
Found Visual Studio 16
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.5
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
double-conversion/3.1.4@conan/stable: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
double-conversion/3.1.4@conan/stable: Aggregating env generators
double-conversion/3.1.4@conan/stable: Calling build()
Found Visual Studio 16
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.5
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
double-conversion/3.1.4@conan/stable: CMake command: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="C:/Users/den00/.conan/data/double-conversion/3.1.4/conan/stable/build/0974a5b97849875d7301803ccabc46a5c139aab2/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/den00/.conan/data/double-conversion/3.1.4/conan/stable/package/0974a5b97849875d7301803ccabc46a5c139aab2" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "C:\Users\den00\.conan\data\double-conversion\3.1.4\conan\stable\build\0974a5b97849875d7301803ccabc46a5c139aab2\src"
-- Using Conan toolchain: C:/Users/den00/.conan/data/double-conversion/3.1.4/conan/stable/build/0974a5b97849875d7301803ccabc46a5c139aab2/build/generators/conan_toolchain.cmake
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is Clang 14.0.6 with MSVC-like command-line
-- The CXX compiler identification is Clang 14.0.6 with MSVC-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang-cl.exe
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang-cl.exe - broken
CMake Error at C:/Users/den00/.conan/data/cmake/3.23.1/_/_/package/01edd76db8e16db9b38c3cca44ec466a9444c388/share/cmake-3.23/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Program Files/LLVM/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/den00/.conan/data/double-conversion/3.1.4/conan/stable/build/0974a5b97849875d7301803ccabc46a5c139aab2/build/Debug/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/Users/den00/.conan/data/ninja/1.11.0/_/_/package/01edd76db8e16db9b38c3cca44ec466a9444c388/bin/ninja.exe cmTC_0e75b && [1/2] Building C object CMakeFiles\cmTC_0e75b.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_0e75b.exe
    FAILED: cmTC_0e75b.exe
    cmd.exe /C "cd . && C:\Users\den00\.conan\data\cmake\3.23.1\_\_\package\01edd76db8e16db9b38c3cca44ec466a9444c388\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_0e75b.dir --rc=clang --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\LLVM\bin\lld-link.exe /nologo CMakeFiles\cmTC_0e75b.dir\testCCompiler.c.obj  /out:cmTC_0e75b.exe /implib:cmTC_0e75b.lib /pdb:cmTC_0e75b.pdb /version:0.0 -m64 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "clang /fo CMakeFiles\cmTC_0e75b.dir/manifest.res CMakeFiles\cmTC_0e75b.dir/manifest.rc" failed (exit code 1) with the following output:
    clang: error: no such file or directory: '/fo'
    clang: error: no such file or directory: 'CMakeFiles\cmTC_0e75b.dir/manifest.res'
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/den00/.conan/data/double-conversion/3.1.4/conan/stable/build/0974a5b97849875d7301803ccabc46a5c139aab2/build/Debug/CMakeFiles/CMakeOutput.log".
See also "C:/Users/den00/.conan/data/double-conversion/3.1.4/conan/stable/build/0974a5b97849875d7301803ccabc46a5c139aab2/build/Debug/CMakeFiles/CMakeError.log".
double-conversion/3.1.4@conan/stable:
double-conversion/3.1.4@conan/stable: ERROR: Package '0974a5b97849875d7301803ccabc46a5c139aab2' build failed
double-conversion/3.1.4@conan/stable: WARN: Build folder C:\Users\den00\.conan\data\double-conversion\3.1.4\conan\stable\build\0974a5b97849875d7301803ccabc46a5c139aab2\build\Debug
ERROR: Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\conans\errors.py", line 34, in conanfile_exception_formatter
    yield
  File "C:\Python310\lib\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method
    conanfile.build()
  File "C:\Users\den00\.conan\data\double-conversion\3.1.4\conan\stable\export\conanfile.py", line 60, in build
    cmake.configure()
  File "C:\Python310\lib\site-packages\conan\tools\cmake\cmake.py", line 97, in configure
    self._conanfile.run(command)
  File "C:\Python310\lib\site-packages\conans\model\conan_file.py", line 443, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 1 while executing cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="C:/Users/den00/.conan/data/double-conversion/3.1.4/conan/stable/build/0974a5b97849875d7301803ccabc46a5c139aab2/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/den00/.conan/data/double-conversion/3.1.4/conan/stable/package/0974a5b97849875d7301803ccabc46a5c139aab2" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "C:\Users\den00\.conan\data\double-conversion\3.1.4\conan\stable\build\0974a5b97849875d7301803ccabc46a5c139aab2\src"
```

**Comment by blockspacer** [comment]
I attempted to change compiler toolset, but got error `conans.errors.ConanException: CMake does not support toolsets with generator "Ninja:.Please check your conan profile to either remove the toolset, or change the CMake generator.`:

```
toolchain_arch=x86_64

[settings]
# Tested in Windows 10
os=Windows
os_target=Windows
os_build=Windows
arch_build=$toolchain_arch
arch=$toolchain_arch
# compiler=clang
# compiler=msvc
compiler=Visual Studio
# compiler.version=14
compiler.version=16
# compiler.cppstd=17
compiler.toolset=ClangCL
# compiler.toolset=llvm
# Must match CMAKE_BUILD_TYPE
# NOTE: do not forget to select Debug or Release compiler.runtime
build_type=Debug
# runtime:
# /MDd - Multi threaded Debug DLL
# /MD - Multi threaded DLL
# If you use /MT, your executable won't depend on a DLL being present on the target system. 
# If you're wrapping this in an installer, it probably won't be an issue and you can go either way.
# /MTd - Multi threaded Debug
# /MT - Multi threaded
compiler.runtime=MTd
# compiler.runtime=static
# compiler.runtime_type=Debug
# compiler.libcxx=libstdc++11
# compiler.threads=win32
# compiler.exception=seh

[options]
[tool_requires]
# mingw used by double-conversion package
# mingw-w64/[>=8.1]
cmake/[>=3.23]
ninja/[>=1.11]
ccache/[>=4.6]
[buildenv]
PATH=+(path)C:/PROGRA~1/LLVM/bin
CC=clang-cl.exe
CXX=clang-cl.exe
RC=clang-cl.exe
LDFLAGS=-fuse-ld=lld-link
AR=llvm-ar.exe
# NOTE: usually path is C:\Program Files\LLVM\bin\llvm-ranlib.exe
RANLIB=llvm-ranlib.exe
[build_requires]
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.env.virtualenv:auto_use=True
# tools.build:cxxflags
# tools.build:cflags
# tools.build:sharedlinkflags
# tools.build:exelinkflags
# tools.build:defines
# tools.build:jobs={{max(1, os.cpu_count()-2)}}
tools.files.download:retry=3
tools.files.download:retry_wait=5
tools.system.package_manager:tool="choco"
[env]
CONAN_CMAKE_GENERATOR=Ninja
CONAN_REVISIONS_ENABLED=1
CONAN_VERBOSE_TRACEBACK=1
CONAN_PRINT_RUN_COMMANDS=1
CONAN_LOGGING_LEVEL=10
CONAN_USE_ALWAYS_SHORT_PATHS=1
# NOTE: usually path is C:\PROGRA~1\LLVM\bin\clang-cl.exe
CC=clang-cl.exe
CXX=clang-cl.exe
LDFLAGS="-fuse-ld=lld-link"
AR="llvm-ar.exe"
# NOTE: usually path is C:\Program Files\LLVM\bin\llvm-ranlib.exe
RANLIB="llvm-ranlib.exe"
# NOTE: -m64 for 64 bit
# NOTE: -DD_DEBUG only for debug builds
# CXXFLAGS="-m64 /GR /MDd -DD_DEBUG -DIS_CLANG_CL=1 -DENABLE_BASE=1 -D_DEBUG=1 /D_DEBUG -D_HAS_ITERATOR_DEBUGGING=0 -D_ITERATOR_DEBUG_LEVEL=0 -D_WIN32=1 -DHB_NO_MT=1 -DENABLE_COBALT=1 -DCOBALT_FORCE_SOFTWARE_RASTERIZER=1 -DDISABLE_COBALT_STORAGE=1 -DPORT_OWN_DLOG=1 -DNO_CHROMIUM_WINDOW=1 -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DDISABLE_MOJO=1 -DNOMINMAX=1 -D_UNICODE=1 -DUNICODE=1 -DNO_TCMALLOC=1 /utf-8 /Gy /FS /bigobj /Zc:__cplusplus /Zc:sizedDealloc- -D__STD_C -D_CRT_RAND_S -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -D_CRT_NONSTDC_NO_DEPRECATE=1 -D_CRT_NONSTDC_NO_WARNINGS=1 -D_WINSOCKAPI_=1 /EHsc- -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_CONSOLE=1 -DWIN32_LEAN_AND_MEAN /sdl- /GS- /GT /Zc:strictStrings- -DCOMPILER_MSVC=1"
#CFLAGS=""
# LDFLAGS="/SUBSYSTEM:CONSOLE"
#CONAN_CACERT_PATH=...
```

**Comment by blockspacer** [comment]
Looks like double-conversion package for conan v2 is broken with clang-cl after commit https://github.com/conan-io/conan-center-index/pull/12311/files

**Comment by SpaceIm** [comment]
double-conversion recipe just relies on conan v2 helpers without any specific compiler trick, so I think it should be transferted to conan client repo.

**Comment by blockspacer** [comment]
> double-conversion recipe just relies on conan v2 helpers without any specific compiler trick, so I think it should be transfered to conan client repo.

I suppose that conan v2 does not support clang-cl properly, so it is not safe to migrate to conan v2.

I compiled without errors version before commit https://github.com/conan-io/conan-center-index/pull/12311/files

**Comment by SpaceIm** [comment]
> If i need to modify conan profile to add conan v2 support - please tell me. I attempted to set toolchain etc. inside conan profile, but got errors.

I don't know, I'm not a conan developper and not aware of all the changes that a profile needs to properly work with conan v2 profile. I've already expressed my concerns to not always "listen" legacy conan v1 env variables in conan v2 helpers, but I don't know which one doesn't work, nor all equivalent conf parameters in conan v2. So as I said, I believe you'll have more chance if you open an issue on conan client repo.
