### ISSUE TITLE
fmt/7.1.3 and gtest/cci.20210126 android armv8 compile error

### ISSUE THREAD

**Issue by xiaoaniubi** [conan-io/conan-center-index#12877]
### Package and Environment Details

fmt:
* Package Name/Version: **fmt/7.1.3**
* Operating System+version: **Linux Ubuntu 20.04** or _**MacOS**_
* Compiler+version: **clang 11**
* Conan version: **conan 1.52.0**
* Python version: **Python 3.8.10** or _**Python 3.10.4**_

gtest:
* Package Name/Version: **gtest/cci.20210126**
* Operating System+version: **Linux Ubuntu 20.04** or _**MacOS**_
* Compiler+version: **clang 11**
* Conan version: **conan 1.52.0**
* Python version: **Python 3.8.10** or _**Python 3.10.4**_

### Conan profile

[settings]
os=Android
os.api_level=24
arch=armv8
arch_build=armv8
compiler=clang
compiler.libcxx=c++_shared
compiler.version=11
build_type=Release
[options]
[conf]
tools.android:ndk_path=~/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656
[build_requires]
*: android-ndk/r22b, cmake/3.24.1, ninja/1.10.1

### Steps to reproduce

fmt:
conan install fmt/7.1.3@ -pr=android -s build_type=RelWithDebInfo --build missing

gtest:
conan install gtest/cci.20210126@ -pr=android -s build_type=RelWithDebInfo --build missing

### Logs

<details><summary>Click to expand log</summary>
the reason of error is adding "generate" method to produce conan_toolchain.cmake

not set ANDROID_ABI  to arm64-v8a before first include android.toolchian.cmake in conan_toolchain.cmake
it will be set armv7 default

```
Put your log output here
```
**_fmt_**:
fmt/7.1.3: Configuring sources in /home/xiaoa/.conan/data/fmt/7.1.3/_/_/source/.
Downloading 7.1.3.tar.gz completed [751.98k]                                             fmt/7.1.3:
fmt/7.1.3:
fmt/7.1.3: Copying sources to build folder
fmt/7.1.3: Building your package in /home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe
fmt/7.1.3: Generator txt created conanbuildinfo.txt
fmt/7.1.3: Calling generate()
fmt/7.1.3: Aggregating env generators
fmt/7.1.3: Calling build()
fmt/7.1.3: apply_conandata_patches(): No patches defined in conandata
fmt/7.1.3: CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/xiaoa/.conan/data/fmt/7.1.3/_/_/package/331f2eee47cc52c9e63df13719befdba14ad8dbe" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DFMT_DOC="False" -DFMT_TEST="False" -DFMT_INSTALL="True" -DFMT_LIB_DIR="lib" -DFMT_OS="True" "/home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/."
-- CMake version: 3.24.1
-- Using Conan toolchain: /home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/build/generators/conan_toolchain.cmake
-- ANDROID_PLATFORM not set. Defaulting to minimum supported version
16.
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The CXX compiler identification is Clang 11.0.5
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - broken
CMake Error at /home/xiaoa/.conan/data/cmake/3.24.1/_/_/package/5c09c752508b674ca5cb1f2d327b5a2d582866c8/share/cmake-3.24/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/build/RelWithDebInfo/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make -f Makefile cmTC_955b7/fast && /usr/bin/make  -f CMakeFiles/cmTC_955b7.dir/build.make CMakeFiles/cmTC_955b7.dir/build
    make[1]: Entering directory '/home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/build/RelWithDebInfo/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_955b7.dir/testCXXCompiler.cxx.o
    /home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android24 --gcc-toolchain=/home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/sysroot   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security    -fPIE -MD -MT CMakeFiles/cmTC_955b7.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_955b7.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_955b7.dir/testCXXCompiler.cxx.o -c /home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/build/RelWithDebInfo/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    clang++: error: the clang compiler does not support '-march=armv7-a'
    make[1]: *** [CMakeFiles/cmTC_955b7.dir/build.make:79: CMakeFiles/cmTC_955b7.dir/testCXXCompiler.cxx.o] Error 1
    make[1]: Leaving directory '/home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/build/RelWithDebInfo/CMakeFiles/CMakeTmp'
    make: *** [Makefile:127: cmTC_955b7/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:53 (project)

-- Configuring incomplete, errors occurred!
See also "/home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/build/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "/home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/build/RelWithDebInfo/CMakeFiles/CMakeError.log".
fmt/7.1.3:
fmt/7.1.3: ERROR: Package '331f2eee47cc52c9e63df13719befdba14ad8dbe' build failed
fmt/7.1.3: WARN: Build folder /home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/build/RelWithDebInfo
ERROR: Traceback (most recent call last):
  File "/home/xiaoa/.local/lib/python3.8/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/home/xiaoa/.local/lib/python3.8/site-packages/conans/client/conanfile/build.py", line 16, in run_build_method
    conanfile.build()
  File "/home/xiaoa/.conan/data/fmt/7.1.3/_/_/export/conanfile.py", line 89, in build
    cmake.configure(variables=cache_entries)
  File "/home/xiaoa/.local/lib/python3.8/site-packages/conan/tools/cmake/cmake.py", line 97, in configure
    self._conanfile.run(command)
  File "/home/xiaoa/.local/lib/python3.8/site-packages/conans/model/conan_file.py", line 443, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 1 while executing cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/xiaoa/.conan/data/fmt/7.1.3/_/_/package/331f2eee47cc52c9e63df13719befdba14ad8dbe" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DFMT_DOC="False" -DFMT_TEST="False" -DFMT_INSTALL="True" -DFMT_LIB_DIR="lib" -DFMT_OS="True" "/home/xiaoa/.conan/data/fmt/7.1.3/_/_/build/331f2eee47cc52c9e63df13719befdba14ad8dbe/."

-----------------------------------------------------------------------------------------------------
_**gtest**_:

Decompressing conan_sources.tgz completed [0.00k]
gtest/cci.20210126: Configuring sources in /home/xiaoa/.conan/data/gtest/cci.20210126/_/_/source/src
Downloading 273f8cb059a4e7b089731036392422b5ef489791.tar.gz completed [847.56k]          gtest/cci.20210126: cci.20210126: gtest/cci.20210126:
gtest/cci.20210126:
gtest/cci.20210126: Copying sources to build folder
gtest/cci.20210126: Building your package in /home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a
gtest/cci.20210126: Generator txt created conanbuildinfo.txt
gtest/cci.20210126: Calling generate()
gtest/cci.20210126: Aggregating env generators
gtest/cci.20210126: Calling build()
gtest/cci.20210126: CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/xiaoa/.conan/data/gtest/cci.20210126/_/_/package/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a" -DCMAKE_POLICY_DEFAULT_CMP0077="NEW" -DBUILD_GMOCK="ON" -Dgtest_hide_internal_symbols="OFF" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="RelWithDebInfo" "/home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/src"
-- Using Conan toolchain: /home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/build/generators/conan_toolchain.cmake
-- ANDROID_PLATFORM not set. Defaulting to minimum supported version
16.
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is Clang 11.0.5
-- The CXX compiler identification is Clang 11.0.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - broken
CMake Error at /home/xiaoa/.conan/data/cmake/3.24.1/_/_/package/5c09c752508b674ca5cb1f2d327b5a2d582866c8/share/cmake-3.24/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/build/RelWithDebInfo/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make -f Makefile cmTC_8fdd0/fast && /usr/bin/make  -f CMakeFiles/cmTC_8fdd0.dir/build.make CMakeFiles/cmTC_8fdd0.dir/build
    make[1]: Entering directory '/home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/build/RelWithDebInfo/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_8fdd0.dir/testCCompiler.c.o
    /home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android24 --gcc-toolchain=/home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/xiaoa/.conan/data/android-ndk/r22b/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/toolchains/llvm/prebuilt/linux-x86_64/sysroot   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -fPIE -MD -MT CMakeFiles/cmTC_8fdd0.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_8fdd0.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_8fdd0.dir/testCCompiler.c.o -c /home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/build/RelWithDebInfo/CMakeFiles/CMakeTmp/testCCompiler.c
    clang: error: the clang compiler does not support '-march=armv7-a'
    make[1]: *** [CMakeFiles/cmTC_8fdd0.dir/build.make:79: CMakeFiles/cmTC_8fdd0.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/build/RelWithDebInfo/CMakeFiles/CMakeTmp'
    make: *** [Makefile:127: cmTC_8fdd0/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:10 (project)

-- Configuring incomplete, errors occurred!
See also "/home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/build/RelWithDebInfo/CMakeFiles/CMakeOutput.log".
See also "/home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/build/RelWithDebInfo/CMakeFiles/CMakeError.log".
gtest/cci.20210126:
gtest/cci.20210126: ERROR: Package '84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a' build failed
gtest/cci.20210126: WARN: Build folder /home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/build/RelWithDebInfo
ERROR: Traceback (most recent call last):
  File "/home/xiaoa/.local/lib/python3.8/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/home/xiaoa/.local/lib/python3.8/site-packages/conans/client/conanfile/build.py", line 16, in run_build_method
    conanfile.build()
  File "/home/xiaoa/.conan/data/gtest/cci.20210126/_/_/export/conanfile.py", line 151, in build
    cmake.configure()
  File "/home/xiaoa/.local/lib/python3.8/site-packages/conan/tools/cmake/cmake.py", line 97, in configure
    self._conanfile.run(command)
  File "/home/xiaoa/.local/lib/python3.8/site-packages/conans/model/conan_file.py", line 443, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 1 while executing cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/xiaoa/.conan/data/gtest/cci.20210126/_/_/package/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a" -DCMAKE_POLICY_DEFAULT_CMP0077="NEW" -DBUILD_GMOCK="ON" -Dgtest_hide_internal_symbols="OFF" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="RelWithDebInfo" "/home/xiaoa/.conan/data/gtest/cci.20210126/_/_/build/84d2e9ab3c16dd771db231f26bd4e76b8b7ed47a/src"

</details>

**Comment by xiaoaniubi** [comment]
![image](https://user-images.githubusercontent.com/40516053/189259138-e65072c3-f5e3-4b85-ae1c-6783d096ca8a.png)

**Comment by bog-dan-ro** [comment]
https://github.com/conan-io/conan-center-index/pull/12795 will fix it
