### ISSUE TITLE
[package] libmysqlclient/*: fails to build with `with_ssl=False`

### ISSUE THREAD

**Issue by Cogitri** [conan-io/conan-center-index#13413]
### Description

```
ERROR: libmysqlclient/8.0.29: Error in build() method, line 235
	self._patch_files()
while calling '_patch_files', line 174
	"NAMES ssl %s" % self.deps_cpp_info["openssl"].components["ssl"].libs[0])
	KeyError: 'openssl'
Traceback (most recent call last):
  File "build.py", line 140, in build
    subprocess.run(args, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
```

### Package and Environment Details

* Package Name/Version: **libmysqlclient/* **
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **Clang 12**
* Conan version: **conan 1.52.0**
* Python version: **Python 3.10.6**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=12
compiler.libcxx=libstdc++
build_type=Release
compiler.cppstd=17
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install -r conancenter libmysqlclient/8.0.29@ -o libmysqlclient:with_ssl=False -pr:b=default -pr:h=default

### Logs

```
ERROR: libmysqlclient/8.0.29: Error in build() method, line 235
	self._patch_files()
while calling '_patch_files', line 174
	"NAMES ssl %s" % self.deps_cpp_info["openssl"].components["ssl"].libs[0])
	KeyError: 'openssl'
Traceback (most recent call last):
  File "build.py", line 140, in build
    subprocess.run(args, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
```

**Comment by Cogitri** [comment]
Seems like just the obvious fix to the conanfile isn't enough:

```
diff --git a/recipes/libmysqlclient/all/conanfile.py b/recipes/libmysqlclient/all/conanfile.py
index 517322919..b4a6950a6 100644
--- a/recipes/libmysqlclient/all/conanfile.py
+++ b/recipes/libmysqlclient/all/conanfile.py
@@ -169,13 +169,14 @@ class LibMysqlClientCConan(ConanFile):
                 "NAMES zstd",
                 "NAMES zstd %s" % self.deps_cpp_info["zstd"].libs[0])
 
-        replace_in_file(self, os.path.join(self._source_subfolder, "cmake", "ssl.cmake"),
-            "NAMES ssl",
-            "NAMES ssl %s" % self.deps_cpp_info["openssl"].components["ssl"].libs[0])
+        if self.options.with_ssl:
+            replace_in_file(self, os.path.join(self._source_subfolder, "cmake", "ssl.cmake"),
+                "NAMES ssl",
+                "NAMES ssl %s" % self.deps_cpp_info["openssl"].components["ssl"].libs[0])
 
-        replace_in_file(self, os.path.join(self._source_subfolder, "cmake", "ssl.cmake"),
-            "NAMES crypto",
-            "NAMES crypto %s" % self.deps_cpp_info["openssl"].components["crypto"].libs[0])
+            replace_in_file(self, os.path.join(self._source_subfolder, "cmake", "ssl.cmake"),
+                "NAMES crypto",
+                "NAMES crypto %s" % self.deps_cpp_info["openssl"].components["crypto"].libs[0])
 
         replace_in_file(self, os.path.join(self._source_subfolder, "cmake", "ssl.cmake"),
             "IF(NOT OPENSSL_APPLINK_C)\n",
```

With this it doesn't crash in the conanfile, but it just picks up system OpenSSL.
