### ISSUE TITLE
[package] xkgcommon: Cannot install because of #13592

### ISSUE THREAD

**Issue by Psy-Kai** [conan-io/conan-center-index#13625]
### Description

`xorg::xkeyboard-config` was removed without scanning other packages if the component is used.

### Package and Environment Details

Linux

### Conan profile

profile independent

### Steps to reproduce

conan install -r conancenter xkbcommon/1.4.1@_/_ -pr:b=default -pr:h=default -g PkgConfigDeps

### Logs

<details><summary>Click to expand log</summary>

```
Generator 'PkgConfigDeps' calling 'generate()'
ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/conans/client/generators/__init__.py", line 181, in write_generators
    generator.generate()
  File "/usr/local/lib/python3.10/dist-packages/conan/tools/gnu/pkgconfigdeps.py", line 415, in generate
    generator_files = self.content
  File "/usr/local/lib/python3.10/dist-packages/conan/tools/gnu/pkgconfigdeps.py", line 402, in content
    pc_files.update(pc_generator.pc_files)
  File "/usr/local/lib/python3.10/dist-packages/conan/tools/gnu/pkgconfigdeps.py", line 332, in pc_files
    for component_info in self.components_info:
  File "/usr/local/lib/python3.10/dist-packages/conan/tools/gnu/pkgconfigdeps.py", line 264, in components_info
    comp_requires_names = self._get_cpp_info_requires_names(cpp_info)
  File "/usr/local/lib/python3.10/dist-packages/conan/tools/gnu/pkgconfigdeps.py", line 243, in _get_cpp_info_requires_names
    comp_name = _get_component_name(req_conanfile, comp_ref_name, self._build_context_suffix)
  File "/usr/local/lib/python3.10/dist-packages/conan/tools/gnu/pkgconfigdeps.py", line 50, in _get_component_name
    raise ConanException("Component '{name}::{cname}' not found in '{name}' "
conans.errors.ConanException: Component 'xorg::xkeyboard-config' not found in 'xorg' package requirement

ERROR: Error in generator 'PkgConfigDeps': Component 'xorg::xkeyboard-config' not found in 'xorg' package requirement
```

</details>

**Comment by ericLemanissier** [comment]
this will be fixed by https://github.com/conan-io/conan-center-index/pull/13604

**Comment by EstebanDugueperoux2** [comment]
Hello,

I get also this issue when consuming qt.

Regards.

**Comment by ericLemanissier** [comment]
you probably want to rebuild xkbcommon with `-b xkbcommon` command line argument
