### ISSUE TITLE
[package] gmp/6.2.1: Configure fails on Windows (checking how to define a 32-bit word)

### ISSUE THREAD

**Issue by svenpilz** [conan-io/conan-center-index#13724]
### Description

Building the package on _Windows 11_ with _Visual Studio 2019_ fails during configure. It seems `dumpbin` fails with:

```
File Type: COFF OBJECT
conftest.obj : fatal error LNK1106: invalid file or disk full: cannot seek to 0xE9
```

### Package and Environment Details

* Package Name/Version: **gmp/6.2.1**
* Operating System+version: **Windows 11**
* Compiler+version: **Visual Studio 2019**
* Conan version: **conan 1.53.0**
* Python version: **Python 3.10.0**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce

```sh
git clone https://github.com/conan-io/conan-center-index.git
cd conan-center-index\recipes
conan create gmp/all 6.2.1@
```

### Logs

<details><summary>Click to expand log</summary>

```
Exporting package recipe
gmp/6.2.1 exports: File 'conandata.yml' found. Exporting it...
gmp/6.2.1 exports: Copied 1 '.yml' file: conandata.yml
gmp/6.2.1: Calling export_sources()
gmp/6.2.1 export_sources() method: Copied 2 '.patch' files: 0001-msvc-dumpbin-yasm-wrapper.patch, 6.2.x-0001-fix-MSVC-next-prime-error.patch
gmp/6.2.1: A new conanfile.py version was exported
gmp/6.2.1: Folder: C:\Users\user\.conan\data\gmp\6.2.1\_\_\export
gmp/6.2.1: Exported revision: 8c4fb3962b043e387bbf98a944d375cd
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]



gmp/6.2.1: Forced build from source
gmp/6.2.1 (test package): Installing package
Requirements
    gmp/6.2.1 from local cache - Cache
Packages
    gmp/6.2.1:c1430fa7339501202f6eff5c00c1be2706543a7c - Build
Build requirements
    autoconf/2.71 from 'conancenter' - Cache
    automake/1.16.4 from 'conancenter' - Cache
    m4/1.4.19 from 'TsGeometryProcessing' - Cache
    msys2/cci.latest from 'conancenter' - Cache
    yasm/1.3.0 from 'conancenter' - Cache
Build requirements packages
    autoconf/2.71:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    automake/1.16.4:3e48e69237f7f2196164383ef9dedf0f93cbf249 - Cache
    m4/1.4.19:0a420ff5c47119e668867cdb51baff0eca1fdb68 - Cache
    msys2/cci.latest:eee3fba89db6d777329de604625af8c30d46f080 - Cache
    yasm/1.3.0:0a420ff5c47119e668867cdb51baff0eca1fdb68 - Cache



Installing (downloading, building) binaries...
m4/1.4.19: Already installed!
m4/1.4.19: Appending PATH environment variable: C:\Users\user\.conan\data\m4\1.4.19\_\_\package\0a420ff5c47119e668867cdb51baff0eca1fdb68\bin
m4/1.4.19: Setting M4 environment variable: C:/Users/user/.conan/data/m4/1.4.19/_/_/package/0a420ff5c47119e668867cdb51baff0eca1fdb68/bin/m4.exe
msys2/cci.latest: Already installed!
msys2/cci.latest: Creating MSYS_ROOT env var : C:\.conan\b375f8\1\bin\msys64
msys2/cci.latest: Creating MSYS_BIN env var : C:\.conan\b375f8\1\bin\msys64\usr\bin
msys2/cci.latest: Appending PATH env var with : C:\.conan\b375f8\1\bin\msys64\usr\bin
yasm/1.3.0: Already installed!
yasm/1.3.0: Appending PATH environment variable: C:\Users\user\.conan\data\yasm\1.3.0\_\_\package\0a420ff5c47119e668867cdb51baff0eca1fdb68\bin
autoconf/2.71: Already installed!
autoconf/2.71: Appending PATH env var with : C:\Users\user\.conan\data\autoconf\2.71\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin
autoconf/2.71: Setting AC_MACRODIR to C:\Users\user\.conan\data\autoconf\2.71\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin\share\autoconf
autoconf/2.71: Setting AUTOCONF to /c/users/user/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoconf
autoconf/2.71: Setting AUTORECONF to /c/users/user/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoreconf
autoconf/2.71: Setting AUTOHEADER to /c/users/user/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoheader
autoconf/2.71: Setting AUTOM4TE to /c/users/user/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autom4te
autoconf/2.71: Setting AUTOM4TE_PERLLIBDIR to C:\Users\user\.conan\data\autoconf\2.71\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\bin\share\autoconf
automake/1.16.4: Already installed!
automake/1.16.4: Appending PATH environment variable:: C:\Users\user\.conan\data\automake\1.16.4\_\_\package\3e48e69237f7f2196164383ef9dedf0f93cbf249\bin
automake/1.16.4: Appending ACLOCAL environment variable with: /c/users/user/.conan/data/automake/1.16.4/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/aclocal.exe
automake/1.16.4: Setting AUTOMAKE_DATADIR to /c/users/user/.conan/data/automake/1.16.4/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/res
automake/1.16.4: Setting AUTOMAKE_LIBDIR to /c/users/user/.conan/data/automake/1.16.4/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/res/automake-1.16
automake/1.16.4: Setting AUTOMAKE_PERLLIBDIR to /c/users/user/.conan/data/automake/1.16.4/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/res/automake-1.16
automake/1.16.4: Setting AUTOMAKE to /c/users/user/.conan/data/automake/1.16.4/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/automake.exe
automake/1.16.4: Append M4 include directories to AUTOMAKE_CONAN_INCLUDES environment variable
gmp/6.2.1: Applying build-requirement: msys2/cci.latest
gmp/6.2.1: Applying build-requirement: yasm/1.3.0
gmp/6.2.1: Applying build-requirement: automake/1.16.4
gmp/6.2.1: Applying build-requirement: autoconf/2.71
gmp/6.2.1: Applying build-requirement: m4/1.4.19
gmp/6.2.1: Configuring sources in C:\Users\user\.conan\data\gmp\6.2.1\_\_\source
Downloading gmp-6.2.1.tar.bz2 completed [2435.46k]



gmp/6.2.1: Copying sources to build folder
gmp/6.2.1: Building your package in C:\Users\user\.conan\data\gmp\6.2.1\_\_\build\c1430fa7339501202f6eff5c00c1be2706543a7c
gmp/6.2.1: Generator txt created conanbuildinfo.txt
gmp/6.2.1: Aggregating env generators
gmp/6.2.1: Calling build()
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.20
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

[…]

gmp/6.2.1: run_in_windows_bash: C:\.conan\b375f8\1\bin\msys64\usr\bin\bash.exe --login -c ^"cd \^"/c/users/user/.conan/data/gmp/6.2.1/_/_/build/c1430fa7339501202f6eff5c00c1be2706543a7c\^" ^&^& PATH=\^"/c/.conan/b375f8/1/bin/msys64/usr/bin:/c/users/user/.conan/data/yasm/1.3.0/_/_/package/0a420ff5c47119e668867cdb51baff0eca1fdb68/bin:/c/users/user/.conan/data/automake/1.16.4/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin:/c/users/user/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin:/c/users/user/.conan/data/m4/1.4.19/_/_/package/0a420ff5c47119e668867cdb51baff0eca1fdb68/bin:$PATH\^" ^&^& /c/users/user/.conan/data/gmp/6.2.1/_/_/build/c1430fa7339501202f6eff5c00c1be2706543a7c/source_subfolder/configure --with-pic=yes --enable-assembly=no --enable-fat=no --enable-cxx=yes --enable-shared=no --enable-static=yes --srcdir=C:/Users/user/.conan/data/gmp/6.2.1/_/_/build/c1430fa7339501202f6eff5c00c1be2706543a7c/source_subfolder ac_cv_c_restrict=restrict gmp_cv_asm_label_suffix=: lt_cv_sys_global_symbol_pipe=cat --prefix=C:/Users/user/.conan/data/gmp/6.2.1/_/_/package/c1430fa7339501202f6eff5c00c1be2706543a7c  ^"
configure: loading site script /etc/config.site
checking build system type... x86_64-w64-mingw32
checking host system type... x86_64-w64-mingw32

[…]

checking how to switch to text section... .text
checking how to switch to data section... .data
checking for assembler label suffix... (cached) :
checking for assembler global directive... .globl
checking for assembler global directive attribute...
checking if globals are prefixed by underscore... no
checking how to switch to read-only data section... .data
checking for assembler .type directive...
checking for assembler .size directive... .size $1,$2
checking for assembler local label prefix... configure: WARNING: "python /c/users/user/.conan/data/gmp/6.2.1/_/_/build/c1430fa7339501202f6eff5c00c1be2706543a7c/dumpbin_nm.py" failure
configure: WARNING: cannot determine local label, using default L
L
checking for assembler byte directive... .byte
checking how to define a 32-bit word... Traceback (most recent call last):
  File "C:\users\user\.conan\data\gmp\6.2.1\_\_\build\c1430fa7339501202f6eff5c00c1be2706543a7c\dumpbin_nm.py", line 8, in <module>
    output = subprocess.check_output("dumpbin -nologo -symbols {}".format(sys.argv[1]), stderr=subprocess.STDOUT, shell=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'dumpbin -nologo -symbols conftest.obj' returned non-zero exit status 1106.
Traceback (most recent call last):
  File "C:\users\user\.conan\data\gmp\6.2.1\_\_\build\c1430fa7339501202f6eff5c00c1be2706543a7c\dumpbin_nm.py", line 8, in <module>
    output = subprocess.check_output("dumpbin -nologo -symbols {}".format(sys.argv[1]), stderr=subprocess.STDOUT, shell=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'dumpbin -nologo -symbols conftest.obj' returned non-zero exit status 1106.
configure: error: cannot determine how to define a 32-bit word
gmp/6.2.1:
gmp/6.2.1: ERROR: Package 'c1430fa7339501202f6eff5c00c1be2706543a7c' build failed
gmp/6.2.1: WARN: Build folder C:\Users\user\.conan\data\gmp\6.2.1\_\_\build\c1430fa7339501202f6eff5c00c1be2706543a7c
ERROR: gmp/6.2.1: Error in build() method, line 152
        autotools = self._configure_autotools()
while calling '_configure_autotools', line 125
        autotools.configure(args=configure_args, configure_dir=self._source_subfolder)
        ConanException: Error 1 while executing /c/users/user/.conan/data/gmp/6.2.1/_/_/build/c1430fa7339501202f6eff5c00c1be2706543a7c/source_subfolder/configure --with-pic=yes --enable-assembly=no --enable-fat=no --enable-cxx=yes --enable-shared=no --enable-static=yes --srcdir=C:/Users/user/.conan/data/gmp/6.2.1/_/_/build/c1430fa7339501202f6eff5c00c1be2706543a7c/source_subfolder ac_cv_c_restrict=restrict gmp_cv_asm_label_suffix=: lt_cv_sys_global_symbol_pipe=cat --prefix=C:/Users/user/.conan/data/gmp/6.2.1/_/_/package/c1430fa7339501202f6eff5c00c1be2706543a7c
```

</details>

**Comment by svenpilz** [comment]
Input file:
```asm
	.data
	.globl	foo
	data4	0
foo:
	.byte	0
```

Command: `yasm -a x86 -m amd64 -p gas -r raw -f win32 -g null -X gnu -FS -DNDEBUG -o conftest.obj conftest.s`

Output:
```
yasm: warning: unrecognized option `-FS'
conftest.s:3: error: instruction not recognized: `data4'
```

**Comment by svenpilz** [comment]
If I set `gmp_cv_asm_w32=.long` or `gmp_cv_asm_w32=.word` in the `conanfile.py` of `gmp`, the configure step passes but building fails 
```
cl -nologo -DHAVE_CONFIG_H -I. -IC:/Users/user/.conan/data/gmp/6.2.1/_/_/source/source_subfolder -D__GMP_WITHIN_GMP -DNDEBUG -O2 -Ob2 -MD -FS -c C:/Users/user/.conan/data/gmp/6.2.1/_/_/source/source_subfolder/nextprime.c -o nextprime.obj
```
prints
```
cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
nextprime.c
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime_string.h(67): error C2059: syntax error: 'do'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime_string.h(67): error C2059: syntax error: 'while'
```

Compiler identifies as: `Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64`
