### ISSUE TITLE
[package] rapidyaml/0.4.1: An exception is thrown when linking RapidYaml as a dependency from other recipe

### ISSUE THREAD

**Issue by PavelKisliak** [conan-io/conan-center-index#14972]
### Description

I ran into this problem while trying to use the `RapidYaml` library as a dependency while developing a recipe for the new version of [BitSerializer](https://github.com/conan-io/conan-center-index/tree/master/recipes/bitserializer) v0.50.

Can't say that it's exactly related to `RapidYaml`, I don't see any suspicious in his recipe, probably the issue is related to Conan dependency processor. In any case, I think that better to handle exception and display more useful error message for user.

### Package and Environment Details

* Package Name/Version: **rapidyaml/0.4.1**
* Windows+version: 19044.2364
* Compiler+version: **Visual Studio 2022**
* Conan version: **conan 1.56.0**
* Python version: **Python 3.11.1**

### Conan profile

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
compiler.cppstd=17
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce

Assumption that PR: #14933 with new version of BitSerializer was already merged (otherwise need to clone branch from [fork](https://github.com/PavelKisliak/conan-center-index/tree/bitserializer_0.50)).

1. Edit recipe "conan-center-index_my\recipes\bitserializer\all\conanfile.py", comment code in the `validate()` method that prevents using option 'with_rapidyaml'
```
        # ToDo: remove this after fix linkage the base library
        if self.options.with_rapidyaml:
            raise ConanInvalidConfiguration("YAML currently unavailable due an issue with linking the base library")
```
(Please remove this code when issue will be fixed)

2. Try to create BitSerializer package with option `with_rapidyaml` via below command:
`conan create . bitserializer/0.50@ -o bitserializer:with_rapidyaml=True --build missing -pr:b=default`

**Expected:** Package should be successfully built.
**Actual:** Python exception is thrown:
> ERROR: Error in generator 'CMakeDeps': error generating context for 'bitserializer/0.50': {'ref': ryml/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}

(Please see full exception in the attached log)

### Logs

<details><summary>Click to expand log</summary>

```
[HOOK - conan-center.py] pre_export(): [DEPRECATED GLOBAL CPPSTD (KB-H001)] OK
[HOOK - conan-center.py] pre_export(): [REFERENCE LOWERCASE (KB-H002)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE METADATA (KB-H003)] OK
[HOOK - conan-center.py] pre_export(): [HEADER_ONLY, NO COPY SOURCE (KB-H005)] OK
[HOOK - conan-center.py] pre_export(): [FPIC OPTION (KB-H006)] OK
[HOOK - conan-center.py] pre_export(): [VERSION RANGES (KB-H008)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] Total recipe size: 16.71484375 KB
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] OK
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE FOLDER (KB-H024)] OK
[HOOK - conan-center.py] pre_export(): [META LINES (KB-H025)] OK
[HOOK - conan-center.py] pre_export(): [CONAN CENTER INDEX URL (KB-H027)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE MINIMUM VERSION (KB-H028)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - RUN ENVIRONMENT (KB-H029)] OK
[HOOK - conan-center.py] pre_export(): [SYSTEM REQUIREMENTS (KB-H032)] OK
[HOOK - conan-center.py] pre_export(): [CONANDATA.YML FORMAT (KB-H030)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - NO IMPORTS() (KB-H034)] OK
[HOOK - conan-center.py] pre_export(): [NO AUTHOR (KB-H037)] OK
[HOOK - conan-center.py] pre_export(): [NOT ALLOWED ATTRIBUTES (KB-H039)] OK
[HOOK - conan-center.py] pre_export(): [NO TARGET NAME (KB-H040)] OK
[HOOK - conan-center.py] pre_export(): [NO FINAL ENDLINE (KB-H041)] OK
[HOOK - conan-center.py] pre_export(): [NO REQUIRES.ADD() (KB-H044)] OK
[HOOK - conan-center.py] pre_export(): [DELETE OPTIONS (KB-H045)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE VERBOSE MAKEFILE (KB-H046)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE VERSION REQUIRED (KB-H048)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE WINDOWS EXPORT ALL SYMBOLS (KB-H049)] OK
[HOOK - conan-center.py] pre_export(): [DEFAULT OPTIONS AS DICTIONARY (KB-H051)] OK
[HOOK - conan-center.py] pre_export(): [CONFIG.YML HAS NEW VERSION (KB-H052)] OK
[HOOK - conan-center.py] pre_export(): [PRIVATE IMPORTS (KB-H053)] OK
[HOOK - conan-center.py] pre_export(): [SINGLE REQUIRES (KB-H055)] OK
[HOOK - conan-center.py] pre_export(): [TOOLS RENAME (KB-H057)] OK
[HOOK - conan-center.py] pre_export(): [ILLEGAL CHARACTERS (KB-H058)] OK
[HOOK - conan-center.py] pre_export(): [CLASS NAME (KB-H059)] OK
[HOOK - conan-center.py] pre_export(): [NO CRLF (KB-H060)] OK
[HOOK - conan-center.py] pre_export(): [NO BUILD SYSTEM FUNCTIONS (KB-H061)] OK
[HOOK - conan-center.py] pre_export(): [TOOLS CROSS BUILDING (KB-H062)] OK
[HOOK - conan-center.py] pre_export(): [INVALID TOPICS (KB-H064)] OK
[HOOK - conan-center.py] pre_export(): [NO REQUIRED_CONAN_VERSION (KB-H065)] OK
[HOOK - conan-center.py] pre_export(): [TEST_TYPE MANAGEMENT (KB-H068)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - NO DEFAULT OPTIONS (KB-H069)] OK
[HOOK - conan-center.py] pre_export(): [MANDATORY SETTINGS (KB-H070)] OK
[HOOK - conan-center.py] pre_export(): [PYLINT EXECUTION (KB-H072)] OK
[HOOK - conan-center.py] pre_export(): [TEST V1 PACKAGE FOLDER (KB-H073)] OK
[HOOK - conan-center.py] pre_export(): [REQUIREMENT OVERRIDE PARAMETER (KB-H075)] OK
Exporting package recipe
bitserializer/0.50 exports: File 'conandata.yml' found. Exporting it...
bitserializer/0.50 exports: Copied 1 '.yml' file: conandata.yml
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] Saving conandata.yml: {'sources': {'0.50': {'url': 'https://bitbucket.com/Pavel_Kisliak/BitSerializer/get/0.50.tar.gz', 'sha256': 'dc000b6516db60337d5dd56fb1b60e29ce700bd2e6f4e609ca548b84d1f1dcee'}}}
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] New conandata.yml contents: sources:
  '0.50':
    sha256: dc000b6516db60337d5dd56fb1b60e29ce700bd2e6f4e609ca548b84d1f1dcee
    url: https://bitbucket.com/Pavel_Kisliak/BitSerializer/get/0.50.tar.gz

[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] OK
[HOOK - conan-center.py] post_export(): [DEFAULT SHARED OPTION VALUE (KB-H050)] OK
[HOOK - conan-center.py] post_export(): [LICENSE PUBLIC DOMAIN (KB-H056)] OK
bitserializer/0.50: The stored package has not changed
bitserializer/0.50: Exported revision: 753d001d015b6c2150fea13018c32af8
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
bitserializer:with_rapidyaml=True
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.cppstd=17
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

bitserializer/0.50 (test package): Installing package
Requirements
    bitserializer/0.50 from local cache - Cache
    c4core/0.1.10 from 'conancenter' - Cache
    fast_float/3.8.1 from 'conancenter' - Cache
    rapidyaml/0.4.1 from 'conancenter' - Cache
Packages
    bitserializer/0.50:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    c4core/0.1.10:69e4b61f9e88a1d90ce83b88bb7bc95759fda136 - Cache
    fast_float/3.8.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    rapidyaml/0.4.1:72f94d9a7e9d543f70ef5ad3b86d357b56cff2a1 - Cache

Installing (downloading, building) binaries...
fast_float/3.8.1: Already installed!
c4core/0.1.10: Already installed!
rapidyaml/0.4.1: Already installed!
bitserializer/0.50: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
[HOOK - conan-center.py] post_package_info(): [LIBRARY DOES NOT EXIST (KB-H054)] OK
[HOOK - conan-center.py] post_package_info(): [INCLUDE PATH DOES NOT EXIST (KB-H071)] OK
bitserializer/0.50 (test package): Generator 'VirtualRunEnv' calling 'generate()'
bitserializer/0.50 (test package): Generator 'CMakeDeps' calling 'generate()'
bitserializer/0.50 (test package): ERROR: Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\tools\cmake\cmakedeps\templates\__init__.py", line 42, in render
    context = self.context
              ^^^^^^^^^^^^
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\tools\cmake\cmakedeps\templates\target_data.py", line 32, in context
    components = self._get_required_components_cpp()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\tools\cmake\cmakedeps\templates\target_data.py", line 172, in _get_required_components_cpp
    req = direct_visible_host[pkg]
          ~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python311\Lib\site-packages\conans\model\dependencies.py", line 76, in __getitem__
    return self._data[r]
           ~~~~~~~~~~^^^
KeyError: {'ref': ryml/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python311\Lib\site-packages\conans\client\generators\__init__.py", line 187, in write_generators
    generator.generate()
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\tools\cmake\cmakedeps\cmakedeps.py", line 47, in generate
    generator_files = self.content
                      ^^^^^^^^^^^^
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\tools\cmake\cmakedeps\cmakedeps.py", line 89, in content
    self._generate_files(require, dep, ret, find_module_mode=False)
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\tools\cmake\cmakedeps\cmakedeps.py", line 102, in _generate_files
    ret[data_target.filename] = data_target.render()
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pavel\AppData\Local\Programs\Python\Python311\Lib\site-packages\conan\tools\cmake\cmakedeps\templates\__init__.py", line 44, in render
    raise ConanException("error generating context for '{}': {}".format(self.conanfile, e))
conans.errors.ConanException: error generating context for 'bitserializer/0.50': {'ref': ryml/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}

ERROR: Error in generator 'CMakeDeps': error generating context for 'bitserializer/0.50': {'ref': ryml/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False, 'visible': True}
```

</details>

**Comment by uilianries** [comment]
Its because you should use the package name as component to be required, not the CMake target name.

**Comment by PavelKisliak** [comment]
> Its because you should use the package name as component to be required, not the CMake target name.

Thanks for help @uilianries!
