### ISSUE TITLE
[package] glfw/3.3.8: Paths don't have the same drive

### ISSUE THREAD

**Issue by IceflowRE** [conan-io/conan-center-index#16875]
### Description

https://github.com/inexorgame/vulkan-renderer/blob/iceflower/conan_cmake/.github/workflows/build.yml#L164

With this https://github.com/inexorgame/vulkan-renderer/blob/iceflower/conan_cmake/.github/workflows/build.yml#L148-L153 configuration.

### Package and Environment Details

Setup can be found here: https://github.com/inexorgame/vulkan-renderer/tree/iceflower/conan_cmake

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=20
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

### Steps to reproduce

conan install . -pr:h ./conan/msvc_release_profile -pr:b ./conan/msvc_release_profile --update --build=missing --output-folder build/

### Logs

<details><summary>Click to expand log</summary>

Full log: https://github.com/inexorgame/vulkan-renderer/actions/runs/4599701705/jobs/8125395643

```
======== Finalizing install (deploy, generators) ========
conanfile.py (Vulkan Renderer/0.1.0): Writing generators to D:\a\vulkan-renderer\vulkan-renderer\build
conanfile.py (Vulkan Renderer/0.1.0): Generator 'CMakeDeps' calling 'generate()'
conanfile.py (Vulkan Renderer/0.1.0): ERROR: Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\tools\cmake\cmakedeps\templates\__init__.py", line 42, in render
    context = self.context
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\tools\cmake\cmakedeps\templates\target_data.py", line 54, in context
    if os.path.commonpath([root_folder, generators_folder]) == generators_folder:
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\ntpath.py", line 763, in commonpath
    raise ValueError("Paths don't have the same drive")
ValueError: Paths don't have the same drive

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conans\client\generators\__init__.py", line 70, in write_generators
    generator.generate()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\tools\cmake\cmakedeps\cmakedeps.py", line 42, in generate
    generator_files = self.content
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\tools\cmake\cmakedeps\cmakedeps.py", line 84, in content
    self._generate_files(require, dep, ret, find_module_mode=False)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\tools\cmake\cmakedeps\cmakedeps.py", line 97, in _generate_files
    ret[data_target.filename] = data_target.render()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\conan\tools\cmake\cmakedeps\templates\__init__.py", line 44, in render
    raise ConanException("error generating context for '{}': {}".format(self.conanfile, e))
conans.errors.ConanException: error generating context for 'glfw/3.3.8': Paths don't have the same drive

ERROR: Error in generator 'CMakeDeps': error generating context for 'glfw/3.3.8': Paths don't have the same drive
```

</details>

**Comment by SpaceIm** [comment]
Unlikely a recipe bug, but a conan client bug instead. The traceback refers to a new bunch of code introduced in conan 2.0.3 (released today): https://github.com/conan-io/conan/pull/13526

Please open an issue in https://github.com/conan-io/conan

**Comment by SpaceIm** [comment]
see https://github.com/conan-io/conan/issues/13606
