### ISSUE TITLE
[package] nasm/2.15.05: Failed to build on windows with mingw64

### ISSUE THREAD

**Issue by bennyhuo** [conan-io/conan-center-index#17160]
### Description

Build failure with nasm on windows. I seems a problem with the win_bash. I can also reproduce the problem when build 'libtool'. 

### Package and Environment Details

* Package Name/Version: **nasm/2.15.05**
* Operating System+version: **Windows 11 + msys2 mingw64**
* Compiler+version: **GCC 9.2**
* Conan version: **conan 2.0.4**
* Python version: **Python 3.9.0**

### Conan profile

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=9.2
os=Windows
[conf]
tools.microsoft.bash:active=True
tools.microsoft.bash:subsystem=msys2
tools.microsoft.bash:path=C:/msys64/usr/bin/bash
[buildenv]
MSYS_ROOT=C:/msys64/bin
MSYS_BIN=C:/msys64/usr/bin
CONAN_CMAKE_GENERATOR="MinGW Makefiles"
CXX=C:/msys64/mingw64/bin/g++
CC=C:/msys64/mingw64/bin/gcc
PATH+=C:/msys64/usr/bin;C:/msys64/mingw64/bin

Profile build:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=9.2
os=Windows
[conf]
tools.microsoft.bash:active=True
tools.microsoft.bash:subsystem=msys2
tools.microsoft.bash:path=C:/msys64/usr/bin/bash
[buildenv]
MSYS_ROOT=C:/msys64/bin
MSYS_BIN=C:/msys64/usr/bin
CONAN_CMAKE_GENERATOR="MinGW Makefiles"
CXX=C:/msys64/mingw64/bin/g++
CC=C:/msys64/mingw64/bin/gcc
PATH+=C:/msys64/usr/bin;C:/msys64/mingw64/bin

### Steps to reproduce

 conan install . --output-folder=cmake-build-debug -pr:b=mingw64 -pr:h=mingw64 --build=missing -vvv

### Logs

<details><summary>Click to expand log</summary>

```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=9.2
os=Windows
[conf]
tools.microsoft.bash:active=True
tools.microsoft.bash:subsystem=msys2
tools.microsoft.bash:path=C:/msys64/usr/bin/bash
[buildenv]
MSYS_ROOT=C:/msys64/bin
MSYS_BIN=C:/msys64/usr/bin
CONAN_CMAKE_GENERATOR="MinGW Makefiles"
CXX=C:/msys64/mingw64/bin/g++
CC=C:/msys64/mingw64/bin/gcc
PATH+=C:/msys64/usr/bin;C:/msys64/mingw64/bin

Profile build:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=9.2
os=Windows
[conf]
tools.microsoft.bash:active=True
tools.microsoft.bash:subsystem=msys2
tools.microsoft.bash:path=C:/msys64/usr/bin/bash
[buildenv]
MSYS_ROOT=C:/msys64/bin
MSYS_BIN=C:/msys64/usr/bin
CONAN_CMAKE_GENERATOR="MinGW Makefiles"
CXX=C:/msys64/mingw64/bin/g++
CC=C:/msys64/mingw64/bin/gcc
PATH+=C:/msys64/usr/bin;C:/msys64/mingw64/bin


======== Computing dependency graph ========
Graph root
    conanfile.py: D:\WorkSpace\iMooc\C\ProgramInC\Chapter16\conanfile.py
Requirements
    libcurl/8.0.1#671cb47ae525a8bdb369af8599634fc0 - Cache
    openssl/1.1.1s#5449870f797dec26045f2765d6fc7b5a - Cache
    sqlite3/3.41.1#a367521f65fc33539addbebededbf873 - Cache
    tinycthreadpool/1.0#20400830304a395b72ccdc376b9a7401 - Cache
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f - Cache
Build requirements
    nasm/2.15.05#799d63b1672a337584b09635b0f22fc1 - Cache
    strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47 - Cache

======== Computing necessary packages ========
Requirements
    libcurl/8.0.1#671cb47ae525a8bdb369af8599634fc0:51d342346dbb827ec2559e88a012d6b115646427 - Build
    openssl/1.1.1s#5449870f797dec26045f2765d6fc7b5a:9965a8d69da51f496982f7ecf4500479e4717653 - Build
    sqlite3/3.41.1#a367521f65fc33539addbebededbf873:65ad91812351a07b0af9629c89ddb30dae77b76c#18b884a89763c5d338c2938c98813f49 - Cache
    tinycthreadpool/1.0#20400830304a395b72ccdc376b9a7401:1a17efffc701be120bf5e2e3efbbaa6a0e30c167#63baaf1e2a101fa51a43698439b0c140 - Cache
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f:1a17efffc701be120bf5e2e3efbbaa6a0e30c167#5c6229798e23094af8c7dedb14357b91 - Cache
Build requirements
    nasm/2.15.05#799d63b1672a337584b09635b0f22fc1:e87e09fb175a1b4a35981cd53c3cf142cb86410f - Build
    strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47:522dcea5982a3f8a5b624c16477e47195da2f84f#a365b3810f698e2f0a00fbeece022903 - Cache

======== Installing packages ========
sqlite3/3.41.1: Already installed! (1 of 7)
strawberryperl/5.32.1.1: Already installed! (2 of 7)
tinycthreadpool/1.0: Already installed! (3 of 7)
zlib/1.2.13: Already installed! (4 of 7)

-------- Installing package nasm/2.15.05 (5 of 7) --------
nasm/2.15.05: Building from source
nasm/2.15.05: Package nasm/2.15.05:e87e09fb175a1b4a35981cd53c3cf142cb86410f
nasm/2.15.05: Copying sources to build folder
nasm/2.15.05: Building your package in C:\Users\benny\.conan2\p\t\nasm82f13361505e7\b
nasm/2.15.05: Calling generate()
nasm/2.15.05: Generators folder: C:\Users\benny\.conan2\p\t\nasm82f13361505e7\b\build-debug\conan
nasm/2.15.05: Generating aggregated env files
nasm/2.15.05: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
nasm/2.15.05: Calling build()
nasm/2.15.05: Calling:
 > "/c/users/benny/.conan2/p/t/nasm82f13361505e7/b/src/configure" --prefix=/ --bindir=${prefix}/bin --sbindir=${prefix}/bin --libdir=${prefix}/lib --includedir=${prefix}/include --oldincludedir=${prefix}/include
nasm/2.15.05: RUN: "/c/users/benny/.conan2/p/t/nasm82f13361505e7/b/src/configure" --prefix=/ --bindir=${prefix}/bin --sbindir=${prefix}/bin --libdir=${prefix}/lib --includedir=${prefix}/include --oldincludedir=${prefix}/include     
'.' is not recognized as an internal or external command,
operable program or batch file.

nasm/2.15.05: ERROR:
Package 'e87e09fb175a1b4a35981cd53c3cf142cb86410f' build failed
nasm/2.15.05: WARN: Build folder C:\Users\benny\.conan2\p\t\nasm82f13361505e7\b\build-debug
Traceback (most recent call last):
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\errors.py", line 51, in conanfile_exception_formatter
    yield
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\conanfile\build.py", line 13, in run_build_method
    conanfile.build()
  File "C:\Users\benny\.conan2\p\nasmf995477f1b9b7\e\conanfile.py", line 73, in build
    autotools.configure()
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\tools\gnu\autotools.py", line 59, in configure
    self._conanfile.run(cmd)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\model\conan_file.py", line 318, in run
    raise ConanException("Error %d while executing" % retcode)
conans.errors.ConanException: Error 1 while executing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\cli\cli.py", line 171, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\cli\command.py", line 157, in run
    info = self._method(conan_api, parser, *args)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\cli\commands\install.py", line 82, in install
    conan_api.install.install_binaries(deps_graph=deps_graph, remotes=remotes)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\api\subapi\install.py", line 22, in install_binaries
    installer.install(deps_graph, remotes)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 252, in install
    self._handle_package(package, install_reference, None, handled_count, package_count)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 315, in _handle_package
    self._handle_node_build(package, package_layout)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 385, in _handle_node_build
    pref = builder.build_package(node, pkg_layout)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 159, in build_package
    raise exc
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 152, in build_package
    self._build(conanfile, pref)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\installer.py", line 101, in _build
  File "C:\Users\benny\.conan2\p\nasmf995477f1b9b7\e\conanfile.py", line 73, in build
    autotools.configure()
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\tools\gnu\autotools.py", line 59, in configure
    self._conanfile.run(cmd)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\model\conan_file.py", line 318, in run
    raise ConanException("Error %d while executing" % retcode)
conans.errors.ConanException: Error 1 while executing


ERROR: Traceback (most recent call last):
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\errors.py", line 51, in conanfile_exception_formatter
    yield
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\client\conanfile\build.py", line 13, in run_build_method
    conanfile.build()
  File "C:\Users\benny\.conan2\p\nasmf995477f1b9b7\e\conanfile.py", line 73, in build
    autotools.configure()
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conan\tools\gnu\autotools.py", line 59, in configure
    self._conanfile.run(cmd)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\conans\model\conan_file.py", line 318, in run
    raise ConanException("Error %d while executing" % retcode)
conans.errors.ConanException: Error 1 while executing


```

</details>

**Comment by SpaceIm** [comment]
I guess you call conan from msys2 terminal, so I would tend to believe it's not a recipe issue, more a conan client issue. Can you build any other conancenter recipe based on autotools from this terminal (for example: fontconfig, gmp, libiconv, libbacktrace, libcurl, libjpeg, linusb, xapian-core, xz_utils)?

**Comment by bennyhuo** [comment]
Agree. Maybe it is the problem of conan not the recipe.
