### ISSUE TITLE
[service] Unexpected error on wrong recipe syntax

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-center-index#190]
When a PR has a recipe file with a syntax error, the system reports an unexpected error in the first command that is executed (A `conan export`).

Instead, the system should notify the PR with the syntax error accordingly so the user can take action and solve it with any additional help.

It happened here https://github.com/conan-io/conan-center-index/pull/172#issuecomment-540012516

**Comment by lasote** [comment]
Another Example: https://ci-conan-prod.jfrog.team/job/conan-center-pull-request/job/PR-194/25/console

```
Inspecting options at /home/conan/workspace/conan-center-pull-request_PR-194/recipes/itk/all
[Pipeline] sh
+ conan inspect /home/conan/workspace/conan-center-pull-request_PR-194/recipes/itk/all -a options --json /home/conan/workspace/conan-center-pull-request_PR-194/recipes/itk/all/_options_inspect.json
WARN: Remotes registry file missing, creating default one in /home/conan/.conan/remotes.json
ERROR: Error loading conanfile at '/home/conan/workspace/conan-center-pull-request_PR-194/recipes/itk/all/conanfile.py': Unable to load conanfile in /home/conan/workspace/conan-center-pull-request_PR-194/recipes/itk/all/conanfile.py
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/model/ref.py", line 197, in loads
    name, version, user, channel, revision = get_reference_fields(text)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/model/ref.py", line 66, in get_reference_fields
    el1, el2 = _split_pair(arg_reference, "/") or (arg_reference, None)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/model/ref.py", line 18, in _split_pair
    raise ConanException("The reference has too many '{}'".format(split_char))
conans.errors.ConanException: The reference has too many '/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/site-packages/conans/client/loader.py", line 293, in _parse_conanfile
    loaded = imp.load_source(module_id, conan_file_path)
  File "/opt/pyenv/versions/3.7.1/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/conan/workspace/conan-center-pull-request_PR-194/recipes/itk/all/conanfile.py", line 43
    self.upstream_version = version_token[0] . "." . version_token[1]
                                                 ^
SyntaxError: invalid syntax
```

**Comment by danimtb** [comment]
The issue was fixed, tested in staging env and deployed to production
