### ISSUE TITLE
[package] zlib/1.2.13: Fails to find patch file

### ISSUE THREAD

**Issue by robert-shade** [conan-io/conan-center-index#19108]
### Description

When building locally, the package does not find its patch file and fails to build.

### Package and Environment Details

* Package Name/Version: **zlib/1.2.13**
* Operating System+version: **RHEL 8.8**
* Compiler+version: **GCC 8**
* Conan version: **conan 1.60.1**
* Python version: **Python 3.11**

### Conan profile

Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
cmake:build_type=Release
ninja:build_type=Release
*:compiler.version=8
[options]
qt:qtwayland=True
[build_requires]
[env]
CC=/usr/bin/gcc
CXX=/usr/bin/g++

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
cmake:build_type=Release
ninja:build_type=Release
*:compiler.version=8
[options]
qt:qtwayland=True
[build_requires]
[env]
CC=/usr/bin/gcc
CXX=/usr/bin/g++

### Steps to reproduce

Command line generated with conan cmake

conan install /my/project/dir/ --update --remote ng-conan --build missing --profile:build default --settings build_type=Debug --settings compiler=gcc --settings compiler.version=8 --settings compiler.libcxx=libstdc++11

### Logs

<details><summary>Click to expand log</summary>

```
[cmake] -- Conan executing: /home/rshade/.cache/pypoetry/virtualenvs/igs-D0YkE7Bt-py3.11/bin/conan install /redacted/ --update --remote ng-conan --build missing --profile:build default --settings build_type=Debug --settings compiler=gcc --settings compiler.version=8 --settings compiler.libcxx=libstdc++11
[cmake] Configuration (profile_host):
[cmake] [settings]
[cmake] arch=x86_64
[cmake] arch_build=x86_64
[cmake] build_type=Debug
[cmake] compiler=gcc
[cmake] compiler.libcxx=libstdc++11
[cmake] compiler.version=8
[cmake] os=Linux
[cmake] os_build=Linux
[cmake] cmake:build_type=Release
[cmake] ninja:build_type=Release
[cmake] *:compiler.version=8
[cmake] [options]
[cmake] qt:qtwayland=True
[cmake] [build_requires]
[cmake] [env]
[cmake] CC=/usr/bin/gcc
[cmake] CXX=/usr/bin/g++
[cmake] Configuration (profile_build):
[cmake] [settings]
[cmake] arch=x86_64
[cmake] arch_build=x86_64
[cmake] build_type=Debug
[cmake] compiler=gcc
[cmake] compiler.libcxx=libstdc++11
[cmake] compiler.version=8
[cmake] os=Linux
[cmake] os_build=Linux
[cmake] cmake:build_type=Release
[cmake] ninja:build_type=Release
[cmake] *:compiler.version=8
[cmake] [options]
[cmake] qt:qtwayland=True
[cmake] [build_requires]
[cmake] [env]
[cmake] CC=/usr/bin/gcc
[cmake] CXX=/usr/bin/g++
[cmake] WARN: igs_python/3.8.10-igs.4@redacted/stable: requirement zlib/1.2.11 overridden by your conanfile to zlib/1.2.13 
[cmake] usockets/0.8.5: WARN: Can't update, no package in remote
[cmake] zlib/1.2.13: WARN: Package binary is corrupted, removing: 761432f3453a17c960259b5b2605153e3bcffd7d
[cmake] Version ranges solved
[cmake]     openssl/* versions found in 'ng-conan' remote
[cmake]     Version range '>=1.1 <4' required by 'libcurl/7.87.0' resolved to 'openssl/3.1.0' in remote 'ng-conan'
[cmake] 
[cmake] conanfile.py: Installing package
[cmake] Requirements
[cmake]     RTIConnextDDS/6.1.2@redacted/stable from 'ng-conan' - Cache
[cmake]     S4Comm/15.3.3@redacted/stable from 'ng-conan' - Cache
[cmake]     cpr/1.9.3 from 'ng-conan' - Cache
[cmake]     hdf5/1.14.0 from 'ng-conan' - Cache
[cmake]     highfive/2.7.1 from 'ng-conan' - Cache
[cmake]     igs_python/3.8.10-igs.4@redacted/stable from 'ng-conan' - Cache
[cmake]     libcurl/7.87.0 from 'ng-conan' - Cache
[cmake]     mbedtls/3.1.0 from 'ng-conan' - Cache
[cmake]     openssl/3.1.0 from 'ng-conan' - Cache
[cmake]     sqlite3/3.40.0 from 'ng-conan' - Cache
[cmake]     sqlitecpp/3.2.1 from 'ng-conan' - Cache
[cmake]     usockets/0.8.5 from 'ng-conan' - Cache
[cmake]     uwebsockets/20.36.0 from 'ng-conan' - Cache
[cmake]     zlib/1.2.13 from 'ng-conan' - Cache
[cmake] Packages
[cmake]     RTIConnextDDS/6.1.2@redacted/stable:b188ad00443131d4c2da792eefc93fdfc8806ca9 - Cache
[cmake]     S4Comm/15.3.3@redacted/stable:cc9f9b2b9f92fc82888026414560bf79d8c3a052 - Cache
[cmake]     cpr/1.9.3:ac85cc409bac4bd04d94293608ecef42e5d7c137 - Cache
[cmake]     hdf5/1.14.0:3e2fd036dff6573ba4fc2820c41fa61dc7e052a6 - Cache
[cmake]     highfive/2.7.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
[cmake]     igs_python/3.8.10-igs.4@redacted/stable:3cea63dcd75faf305bb387fd56132f0eabf927e4 - Cache
[cmake]     libcurl/7.87.0:c459df105cb73db3eb0a2677234fa96afae3f740 - Cache
[cmake]     mbedtls/3.1.0:761432f3453a17c960259b5b2605153e3bcffd7d - Cache
[cmake]     openssl/3.1.0:add898c3083be25c44631061338cc17b67f966d9 - Cache
[cmake]     sqlite3/3.40.0:54b8b444f3babb0812d16fc26df6c83677313968 - Cache
[cmake]     sqlitecpp/3.2.1:f9500dbed51159c45062be0e2fea38a0a90951df - Cache
[cmake]     usockets/0.8.5:f216f9e283ee0a54b0bacc96f990613b5c374fe3 - Cache
[cmake]     uwebsockets/20.36.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
[cmake]     zlib/1.2.13:761432f3453a17c960259b5b2605153e3bcffd7d - Build
[cmake] 
[cmake] Installing (downloading, building) binaries...
[cmake] RTIConnextDDS/6.1.2@redacted/stable: Already installed!
[cmake] S4Comm/15.3.3@redacted/stable: Already installed!
[cmake] mbedtls/3.1.0: Already installed!
[cmake] sqlite3/3.40.0: Already installed!
[cmake] usockets/0.8.5: Already installed!
[cmake] zlib/1.2.13: WARN: Build folder is dirty, removing it: /home/rshade/.conan/data/zlib/1.2.13/_/_/build/761432f3453a17c960259b5b2605153e3bcffd7d
[cmake] zlib/1.2.13: Copying sources to build folder
[cmake] zlib/1.2.13: Building your package in /home/rshade/.conan/data/zlib/1.2.13/_/_/build/761432f3453a17c960259b5b2605153e3bcffd7d
[cmake] zlib/1.2.13: Generator txt created conanbuildinfo.txt
[cmake] zlib/1.2.13: Calling generate()
[cmake] zlib/1.2.13: Preset 'debug' added to CMakePresets.json. Invoke it manually using 'cmake --preset debug'
[cmake] zlib/1.2.13: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/rshade/.conan/data/zlib/1.2.13/_/_/build/761432f3453a17c960259b5b2605153e3bcffd7d/build/Debug/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Debug'
[cmake] zlib/1.2.13: Aggregating env generators
[cmake] zlib/1.2.13: Calling build()
[cmake] zlib/1.2.13: 
[cmake] zlib/1.2.13: ERROR: Package '761432f3453a17c960259b5b2605153e3bcffd7d' build failed
[cmake] zlib/1.2.13: WARN: Build folder /home/rshade/.conan/data/zlib/1.2.13/_/_/build/761432f3453a17c960259b5b2605153e3bcffd7d/build/Debug
[cmake] ERROR: Traceback (most recent call last):
[cmake]   File "/home/rshade/.cache/pypoetry/virtualenvs/igs-D0YkE7Bt-py3.11/lib/python3.11/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
[cmake]     yield
[cmake]   File "/home/rshade/.cache/pypoetry/virtualenvs/igs-D0YkE7Bt-py3.11/lib/python3.11/site-packages/conans/client/conanfile/build.py", line 16, in run_build_method
[cmake]     conanfile.build()
[cmake]   File "/home/rshade/.conan/data/zlib/1.2.13/_/_/export/conanfile.py", line 82, in build
[cmake]     self._patch_sources()
[cmake]   File "/home/rshade/.conan/data/zlib/1.2.13/_/_/export/conanfile.py", line 66, in _patch_sources
[cmake]     apply_conandata_patches(self)
[cmake]   File "/home/rshade/.cache/pypoetry/virtualenvs/igs-D0YkE7Bt-py3.11/lib/python3.11/site-packages/conan/tools/files/patches.py", line 117, in apply_conandata_patches
[cmake]     patch(conanfile, patch_file=patch_file, **entry)
[cmake]   File "/home/rshade/.cache/pypoetry/virtualenvs/igs-D0YkE7Bt-py3.11/lib/python3.11/site-packages/conan/tools/files/patches.py", line 53, in patch
[cmake]     patchset = patch_ng.fromfile(patch_path)
[cmake]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[cmake]   File "/home/rshade/.cache/pypoetry/virtualenvs/igs-D0YkE7Bt-py3.11/lib/python3.11/site-packages/patch_ng.py", line 197, in fromfile
[cmake]     fp = open(filename, "rb")
[cmake]          ^^^^^^^^^^^^^^^^^^^^
[cmake] FileNotFoundError: [Errno 2] No such file or directory: '/home/rshade/.conan/data/zlib/1.2.13/_/_/build/761432f3453a17c960259b5b2605153e3bcffd7d/patches/1.2.13/0001-Fix-cmake.patch'
[cmake] 
[cmake] CMake Error at cmake/conan.cmake:651 (message):
[cmake]   Conan install failed='1'
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:92 (conan_cmake_install)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
```

</details>

**Comment by SpaceIm** [comment]
Try to remove zlib recipe from your cache, because later is likely corrupted. I see that your remote is called `ng-conan`, is it private? Are you sure that zlib recipe in this remote is the same that the one in conancenter?

**Comment by robert-shade** [comment]
It was the latest recipe.  I tried going to cci directly instead of going through our artifactory proxy and it worked.  I'll track that down.  thanks.
