### ISSUE TITLE
[package] assimp/5.2.2: Build broken with some option configurations

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan-center-index#20553]
### Description

When building `assimp` with a particular configuration of options, the build will fail.

### Package and Environment Details

* Package Name/Version: assimp/5.2.2
* Operating System+version: Windows 11
* Compiler+version: Visual Studio 2022
* Conan version: conan 2.0.13
* Python version: Python 3.11.5

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

### Steps to reproduce

conanfile.txt
```
[requires]
assimp/5.2.2

[options]
assimp/*:shared=False
assimp/*:with_3d=False
assimp/*:with_3ds=True
assimp/*:with_3ds_exporter=False
assimp/*:with_3mf=False
assimp/*:with_3mf_exporter=False
assimp/*:with_ac=False
assimp/*:with_amf=False
assimp/*:with_ase=False
assimp/*:with_assbin=False
assimp/*:with_assbin_exporter=False
assimp/*:with_assjson_exporter=False
assimp/*:with_assxml_exporter=False
assimp/*:with_b3d=False
assimp/*:with_blend=False
assimp/*:with_bvh=False
assimp/*:with_cob=False
assimp/*:with_collada=False
assimp/*:with_collada_exporter=False
assimp/*:with_csm=False
assimp/*:with_dxf=False
assimp/*:with_fbx=False
assimp/*:with_fbx_exporter=False
assimp/*:with_gltf=False
assimp/*:with_gltf_exporter=False
assimp/*:with_hmp=False
assimp/*:with_ifc=False
assimp/*:with_irr=False
assimp/*:with_irrmesh=False
assimp/*:with_lwo=True
assimp/*:with_lws=False
assimp/*:with_md2=False
assimp/*:with_md3=False
assimp/*:with_md5=False
assimp/*:with_mdc=False
assimp/*:with_mdl=False
assimp/*:with_mmd=False
assimp/*:with_ms3d=False
assimp/*:with_ndo=False
assimp/*:with_nff=False
assimp/*:with_obj=True
assimp/*:with_obj_exporter=False
assimp/*:with_off=False
assimp/*:with_ogre=False
assimp/*:with_opengex=False
assimp/*:with_opengex_exporter=False
assimp/*:with_ply=False
assimp/*:with_ply_exporter=False
assimp/*:with_q3bsp=False
assimp/*:with_q3d=False
assimp/*:with_raw=False
assimp/*:with_sib=False
assimp/*:with_smd=False
assimp/*:with_step=False
assimp/*:with_step_exporter=False
assimp/*:with_stl=True
assimp/*:with_stl_exporter=False
assimp/*:with_terragen=False
assimp/*:with_x=False
assimp/*:with_x3d=False
assimp/*:with_x3d_exporter=False
assimp/*:with_x_exporter=False
assimp/*:with_xgl=False
```

`conan install . --build=missing`

### Logs

<details><summary>Click to expand log</summary>

```
======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
assimp/5.2.2: Not found in local cache, looking in remotes...
assimp/5.2.2: Checking remote: conancenter
assimp/5.2.2: Downloaded recipe revision 9f05c1993aa6dc058055d56ae9fef3cc
minizip/1.2.13: Not found in local cache, looking in remotes...
minizip/1.2.13: Checking remote: conancenter
minizip/1.2.13: Downloaded recipe revision 75d20b6a37ef70126334467f61acadde
zlib/1.3: Not found in local cache, looking in remotes...
zlib/1.3: Checking remote: conancenter
zlib/1.3: Downloaded recipe revision 06023034579559bb64357db3a53f88a4
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Checking remote: conancenter
bzip2/1.0.8: Downloaded recipe revision 411fc05e80d47a89045edc1ee6f23c1d
utfcpp/3.2.3: Not found in local cache, looking in remotes...
utfcpp/3.2.3: Checking remote: conancenter
utfcpp/3.2.3: Downloaded recipe revision bd19718a5088de9d38cb662b87b4f194
pugixml/1.13: Not found in local cache, looking in remotes...
pugixml/1.13: Checking remote: conancenter
pugixml/1.13: Downloaded recipe revision f615c1fcec55122b2e177d17061276e7
stb/cci.20220909: Not found in local cache, looking in remotes...
stb/cci.20220909: Checking remote: conancenter
stb/cci.20220909: Downloaded recipe revision 1c47474f095ef8cd9e4959558525b827
Graph root
    conanfile.txt: D:\dev\third_party_bug_reports\conan\assimp_bug\conanfile.txt
Requirements
    assimp/5.2.2#9f05c1993aa6dc058055d56ae9fef3cc - Downloaded (conancenter)
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Downloaded (conancenter)
    minizip/1.2.13#75d20b6a37ef70126334467f61acadde - Downloaded (conancenter)
    pugixml/1.13#f615c1fcec55122b2e177d17061276e7 - Downloaded (conancenter)
    stb/cci.20220909#1c47474f095ef8cd9e4959558525b827 - Downloaded (conancenter)
    utfcpp/3.2.3#bd19718a5088de9d38cb662b87b4f194 - Downloaded (conancenter)
    zlib/1.3#06023034579559bb64357db3a53f88a4 - Downloaded (conancenter)
Resolved version ranges
    zlib/[>=1.2.11 <2]: zlib/1.3

======== Computing necessary packages ========
assimp/5.2.2: Checking 3 compatible configurations
assimp/5.2.2: Compatible configurations not found in cache, checking servers
assimp/5.2.2: 'd9d20c522f89f81bf65a7a1016033a67ae726321': compiler.cppstd=17
assimp/5.2.2: '77212780e7ca2a752dc81119e5423cb38fa6e416': compiler.cppstd=20
assimp/5.2.2: '22b19f516fbeae7a6e4ab546f92c4cd24cc6dcc0': compiler.cppstd=23
Requirements
    assimp/5.2.2#9f05c1993aa6dc058055d56ae9fef3cc:541b40bae188a084bac87cbf636c257840125663 - Build
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d:67bfcb7b4b78262b9d05495e479dcd92f747316b#7d944f387aef9d7e05a93c6be6033e42 - Download (conancenter)
    minizip/1.2.13#75d20b6a37ef70126334467f61acadde:0a6c917911224e3044c1476d72e469ed0a9f7424#4166d5082154eb19494983e46378ffab - Download (conancenter)
    pugixml/1.13#f615c1fcec55122b2e177d17061276e7:30ef123599bdbe8832d0547653bcc4946252c2f9#24415b5e544ca1388b02f2424a2b55c9 - Download (conancenter)
    stb/cci.20220909#1c47474f095ef8cd9e4959558525b827:da39a3ee5e6b4b0d3255bfef95601890afd80709#cab2e5cf0f4391f87945a304034a4e5d - Download (conancenter)
    utfcpp/3.2.3#bd19718a5088de9d38cb662b87b4f194:da39a3ee5e6b4b0d3255bfef95601890afd80709#a0dd63ca47ba4c2f8e4abca9f50b2f85 - Download (conancenter)
    zlib/1.3#06023034579559bb64357db3a53f88a4:7bfde258ff4f62f75668d0896dbddedaa7480a0f#67a13c948e95f6037be3f15318d222c1 - Download (conancenter)

======== Installing packages ========

-------- Downloading 6 packages --------
bzip2/1.0.8: Retrieving package 67bfcb7b4b78262b9d05495e479dcd92f747316b from remote 'conancenter'
bzip2/1.0.8: Package installed 67bfcb7b4b78262b9d05495e479dcd92f747316b
bzip2/1.0.8: Downloaded package revision 7d944f387aef9d7e05a93c6be6033e42
pugixml/1.13: Retrieving package 30ef123599bdbe8832d0547653bcc4946252c2f9 from remote 'conancenter'
pugixml/1.13: Package installed 30ef123599bdbe8832d0547653bcc4946252c2f9
pugixml/1.13: Downloaded package revision 24415b5e544ca1388b02f2424a2b55c9
stb/cci.20220909: Retrieving package da39a3ee5e6b4b0d3255bfef95601890afd80709 from remote 'conancenter'
stb/cci.20220909: Package installed da39a3ee5e6b4b0d3255bfef95601890afd80709
stb/cci.20220909: Downloaded package revision cab2e5cf0f4391f87945a304034a4e5d
utfcpp/3.2.3: Retrieving package da39a3ee5e6b4b0d3255bfef95601890afd80709 from remote 'conancenter'
utfcpp/3.2.3: Package installed da39a3ee5e6b4b0d3255bfef95601890afd80709
utfcpp/3.2.3: Downloaded package revision a0dd63ca47ba4c2f8e4abca9f50b2f85
zlib/1.3: Retrieving package 7bfde258ff4f62f75668d0896dbddedaa7480a0f from remote 'conancenter'
zlib/1.3: Package installed 7bfde258ff4f62f75668d0896dbddedaa7480a0f
zlib/1.3: Downloaded package revision 67a13c948e95f6037be3f15318d222c1
minizip/1.2.13: Retrieving package 0a6c917911224e3044c1476d72e469ed0a9f7424 from remote 'conancenter'
minizip/1.2.13: Package installed 0a6c917911224e3044c1476d72e469ed0a9f7424
minizip/1.2.13: Downloaded package revision 4166d5082154eb19494983e46378ffab
assimp/5.2.2: Sources downloaded from 'conancenter'
assimp/5.2.2: Calling source() in D:\dev\third_party_bug_reports\conan\assimp_bug\conan_home\p\assim0091e55ed7893\s\src
assimp/5.2.2: Downloading 49.6MB v5.2.2.tar.gz

-------- Installing package assimp/5.2.2 (7 of 7) --------
assimp/5.2.2: Building from source
assimp/5.2.2: Package assimp/5.2.2:541b40bae188a084bac87cbf636c257840125663
assimp/5.2.2: Copying sources to build folder
assimp/5.2.2: Building your package in D:\dev\third_party_bug_reports\conan\assimp_bug\conan_home\p\b\assime644c03101055\b
assimp/5.2.2: Calling generate()
assimp/5.2.2: Generators folder: D:\dev\third_party_bug_reports\conan\assimp_bug\conan_home\p\b\assime644c03101055\b\build\generators
assimp/5.2.2: CMakeToolchain generated: conan_toolchain.cmake
assimp/5.2.2: CMakeToolchain generated: CMakePresets.json
assimp/5.2.2: CMakeToolchain generated: ..\..\src\CMakeUserPresets.json
assimp/5.2.2: Generating aggregated env files
assimp/5.2.2: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
assimp/5.2.2: Calling build()
assimp/5.2.2: Apply patch (file): patches/0005-fix-unzip.patch
assimp/5.2.2: Apply patch (file): patches/0006-unvendor-deps-5.2.x.patch
assimp/5.2.2: WARN: replace_in_file didn't find pattern 'SET(CMAKE_CXX_FLAGS_DEBUG "/D_DEBUG /MDd /Ob2 /DEBUG:FULL /Zi")' in 'D:\dev\third_party_bug_reports\conan\assimp_bug\conan_home\p\b\assime644c03101055\b\src\CMakeLists.txt' file.
assimp/5.2.2: Running CMake.configure()
assimp/5.2.2: RUN: cmake -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="D:/dev/third_party_bug_reports/conan/assimp_bug/conan_home/p/b/assime644c03101055/b/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="D:/dev/third_party_bug_reports/conan/assimp_bug/conan_home/p/b/assime644c03101055/p" -DCMAKE_POLICY_DEFAULT_CMP0077="NEW" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "D:\dev\third_party_bug_reports\conan\assimp_bug\conan_home\p\b\assime644c03101055\b\src"
-- Using Conan toolchain: D:/dev/third_party_bug_reports/conan/assimp_bug/conan_home/p/b/assime644c03101055/b/build/generators/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 14 with extensions OFF
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.37.32822.0
-- The CXX compiler identification is MSVC 19.37.32822.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shared libraries disabled
-- Conan: Target declared 'minizip::minizip'
-- Conan: Target declared 'BZip2::BZip2'
-- Conan: Including build module from 'D:/dev/third_party_bug_reports/conan/assimp_bug/conan_home/p/bzip2390e62dbed9cd/p/lib/cmake/conan-official-bzip2-variables.cmake'
-- Conan: Target declared 'pugixml::pugixml'
-- Conan: Target declared 'utf8cpp'
-- Conan: Target declared 'stb::stb'
-- Enabled importer formats: 3DS IQM LWO M3D OBJ STL
-- Disabled importer formats: AMF AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD TERRAGEN 3D X X3D GLTF 3MF MMD
-- Enabled exporter formats: M3D PBRT
-- Disabled exporter formats: OBJ OPENGEX PLY 3DS ASSBIN ASSXML COLLADA FBX STL X X3D GLTF 3MF ASSJSON STEP
-- Configuring done (4.0s)
CMake Error at D:/dev/third_party_bug_reports/conan/assimp_bug/conan_home/p/b/assime644c03101055/b/build/generators/minizip-Target-release.cmake:15 (set_property):
  The link interface of target "minizip_DEPS_TARGET" contains:

    ZLIB::ZLIB

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  D:/dev/third_party_bug_reports/conan/assimp_bug/conan_home/p/b/assime644c03101055/b/build/generators/minizipTargets.cmake:26 (include)
  D:/dev/third_party_bug_reports/conan/assimp_bug/conan_home/p/b/assime644c03101055/b/build/generators/minizip-config.cmake:16 (include)
  CMakeLists.txt:529 (find_package)


-- Generating done (0.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

assimp/5.2.2: ERROR: 
Package '541b40bae188a084bac87cbf636c257840125663' build failed
assimp/5.2.2: WARN: Build folder D:\dev\third_party_bug_reports\conan\assimp_bug\conan_home\p\b\assime644c03101055\b\build
*********************************************************
Recipe 'assimp/5.2.2' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: assimp/5.2.2: Error in build() method, line 261
        cmake.configure()
        ConanException: Error 1 while executing
Traceback (most recent call last):
  File "D:\dev\third_party_bug_reports\conan\assimp_bug\repro.py", line 16, in <module>
    subprocess.check_call(
  File "C:\Program Files\Python311\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'conan install -pr:b win_release_profile -pr:h win_release_profile "D:\dev\third_party_bug_reports\conan\assimp_bug" --build=missing' returned non-zero exit status 1.
```

</details>

**Comment by SpaceIm** [comment]
Seems to be a CMakeDeps bug since error comes from config file generated by CMakeDeps.

**Comment by memsharded** [comment]
As described in https://github.com/conan-io/conan/issues/14978#issuecomment-1773359791, it seems a failure in the recipe

**Comment by SpaceIm** [comment]
Please try https://github.com/conan-io/conan-center-index/pull/20714

**Comment by rconde01** [comment]
@SpaceIm that indeed fixes the issue
