### ISSUE TITLE
[fftw] conan2: conan install fails if not built and --format json is added to the command

### ISSUE THREAD

**Issue by fdgStilla** [conan-io/conan-center-index#21784]
### Description

conan install fails and does not create the output json if you try to install fftw --format json but without building it.

From the logs, the issue seems to be that the `super().build_folder` returns an empty string in this case in the fftw recipe.
Note sure if this is an error in this recipe (and maybe others) or in conan itself.

Note that the installation succeed even if the command fails so it is really an issue for local developement, but in a CI it is an issue.

### Package and Environment Details

* Package Name/Version: **fftw/3.3.10**
* Operating System+version: **Linux Ubuntu 22.10**
* Compiler+version: **GCC 11**
* Conan version: **conan 2.0.14**
* Python version: **Python 3.10.7**

### Conan profile

[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[conf]
tools.cmake.cmaketoolchain:generator=Unix Makefiles
tools.system.package_manager:mode=install
tools.env.virtualenv:powershell=False

### Steps to reproduce

`conan install --requires fftw/3.3.10 -of /tmp/fftw --format json`

### Logs

<details><summary>Click to expand log</summary>

```
conan install --requires fftw/3.3.10 -of /tmp/fftw --format json

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[conf]
tools.cmake.cmaketoolchain:generator=Unix Makefiles
tools.system.package_manager:mode=install
tools.env.virtualenv:powershell=False

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[conf]
tools.cmake.cmaketoolchain:generator=Unix Makefiles
tools.system.package_manager:mode=install
tools.env.virtualenv:powershell=False


======== Computing dependency graph ========
Graph root
    cli
Requirements
    fftw/3.3.10#8d1d05d6780df0f432b39f4033a395be - Cache

======== Computing necessary packages ========
Requirements
    fftw/3.3.10#8d1d05d6780df0f432b39f4033a395be:80a0f31ebf64b0a37a0c0545fe0f924772616e2c#01f602d2201be239673c652339708107 - Cache

======== Installing packages ========
fftw/3.3.10: Already installed! (1 of 1)
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.filenames' used in: fftw/3.3.10
WARN: deprecated:     'cpp_info.names' used in: fftw/3.3.10

======== Finalizing install (deploy, generators) ========
cli: Generating aggregated env files
cli: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
ERROR: Traceback (most recent call last):
  File "/home/florian/.local/lib/python3.10/site-packages/conan/cli/cli.py", line 272, in main
    cli.run(args)
  File "/home/florian/.local/lib/python3.10/site-packages/conan/cli/cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "/home/florian/.local/lib/python3.10/site-packages/conan/cli/command.py", line 128, in run
    self._format(parser, info, *args)
  File "/home/florian/.local/lib/python3.10/site-packages/conan/cli/command.py", line 94, in _format
    formatter(info)
  File "/home/florian/.local/lib/python3.10/site-packages/conan/cli/formatters/graph/graph.py", line 141, in format_graph_json
    serial = graph.serialize()
  File "/home/florian/.local/lib/python3.10/site-packages/conans/client/graph/graph.py", line 390, in serialize
    result["nodes"] = {n.id: n.serialize() for n in self.nodes}
  File "/home/florian/.local/lib/python3.10/site-packages/conans/client/graph/graph.py", line 390, in <dictcomp>
    result["nodes"] = {n.id: n.serialize() for n in self.nodes}
  File "/home/florian/.local/lib/python3.10/site-packages/conans/client/graph/graph.py", line 228, in serialize
    result.update(self.conanfile.serialize())
  File "/home/florian/.local/lib/python3.10/site-packages/conans/model/conan_file.py", line 161, in serialize
    result["build_folder"] = self.build_folder
  File "/home/florian/.conan2/p/fftwa79a145d5863e/e/conanfile.py", line 99, in build_folder
    return os.path.join(bf, self._current_precision) if self._current_precision else bf
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

ERROR: expected str, bytes or os.PathLike object, not NoneType
```

</details>

**Comment by SpaceIm** [comment]
Since https://github.com/conan-io/conan-center-index/pull/20888, `fftw` recipe tweaks build_folder in order to be able to call cmake configuration, build & install several times (for each precision): https://github.com/conan-io/conan-center-index/blob/d57266c3ad9eb3dbda6e369df33a0daa764a39c3/recipes/fftw/all/conanfile.py#L96-L99

So yes, it may break other logic of other conan commands.

**Comment by SpaceIm** [comment]
Here is an attemp to fix this issue: https://github.com/conan-io/conan-center-index/pull/21788

Could you try please?

**Comment by SSE4** [comment]
IMO a traceback indicates bug in conan itself, so issue has to be reported to the client. the recipe only uses documented functions, so it should work with `--format json`.

**Comment by SpaceIm** [comment]
It's a recipe issue. conan tries to acces build_folder in a serialization method, and its value is None at this moment, but fftw recipe overrides build_folder property by `os.path.join(self.build_folder, self._current_precision)` when `self._current_precision` is not None, and it breaks because you can't pass None to `os.path.join`.

**Comment by fdgStilla** [comment]
> Here is an attempt to fix this issue: #21788
> 
> Could you try please?

It works thanks
