### ISSUE TITLE
[package] bison/3.5.3: Cannot build on x86, doesn't seem to understand canonical names or something

### ISSUE THREAD

**Issue by jmarrec** [conan-io/conan-center-index#2300]
### Package and Environment Details (include every applicable attribute)

  * Package Name/Version: **bison/3.5.3**
  * Operating System+version: **Windows**, **x86**
  * Compiler+version: **Visual Studio 2019**
  * Docker image: Appveyor, cf details below
  * Conan version: **conan 1.27.1**
  * Python version: **Python 3.7**

appveyor that produces it:

```
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86
          CONAN_BUILD_REQUIRES: msys2/20190524
```

Some conversation on the topic happened in https://github.com/conan-io/conan-center-index/issues/2183
m4 (a bison requirement) was patched as well, and now I'm getting a new error with bison itself.

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
+------------------------+
| Profile                |
|------------------------|
| include(default)       |
|                        |
| [settings]             |
| arch=x86               |
| build_type=Release     |
| compiler=Visual Studio |
| compiler.runtime=MD    |
| compiler.version=16    |
| [options]              |
|                        |
| [env]                  |
|                        |
| [build_requires]       |
| *:msys2/20190524       |
+------------------------+
[conan_create]
```

### Logs (Include/Attach if Applicable)

https://ci.appveyor.com/project/ci-commercialbuildings/conan-openstudio-ruby/builds/34347448/job/k3f7573oh2kq3onu?fullLog=true

<details><summary>Click to expand log</summary>

```
[...]
bison/3.5.3: Applying build-requirement: msys2/20190524
bison/3.5.3: Applying build-requirement: automake/1.16.1
bison/3.5.3: Applying build-requirement: autoconf/2.69
Downloading conan_sources.tgz
bison/3.5.3: Configuring sources in C:\Users\appveyor\.conan\data\bison\3.5.3\_\_\source
bison/3.5.3: Copying sources to build folder
bison/3.5.3: Building your package in C:\Users\appveyor\.conan\data\bison\3.5.3\_\_\build\9b01c5b89d2898ea5ee7a34d047e105bdf301e15
bison/3.5.3: Generator txt created conanbuildinfo.txt
bison/3.5.3: Calling build()
Conan:vcvars already set 
bison/3.5.3: run_in_windows_bash: C:\.conan\bc9a75\1\bin\usr\bin\bash.exe --login -c ^"cd \^"/c/users/appveyor/.conan/data/bison/3.5.3/_/_/build/9b01c5b89d2898ea5ee7a34d047e105bdf301e15\^" ^&^& PATH=\^"/c/.conan/bc9a75/1/bin/usr/bin:/c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin:/c/users/appveyor/.conan/data/autoconf/2.69/_/_/package/456f15897172eef340fcbac8a70811f2beb26a93/bin:/c/users/appveyor/.conan/data/m4/1.4.18/_/_/package/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/bin:$PATH\^" ^&^& /c/users/appveyor/.conan/data/bison/3.5.3/_/_/build/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/source_subfolder/configure --help ^"
bison/3.5.3: `configure' configures GNU Bison 3.5.3 to adapt to many kinds of systems.
bison/3.5.3: 
bison/3.5.3: Usage: /c/users/appveyor/.conan/data/bison/3.5.3/_/_/build/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/source_subfolder/configure [OPTION]... [VAR=VALUE]...
bison/3.5.3: 
bison/3.5.3: To assign environment variables (e.g., CC, CFLAGS...), specify them as
bison/3.5.3: VAR=VALUE.  See below for descriptions of some of the useful variables.
bison/3.5.3: 
bison/3.5.3: Defaults for the options are specified in brackets.
bison/3.5.3: 
bison/3.5.3: Configuration:
bison/3.5.3:   -h, --help              display this help and exit
bison/3.5.3:       --help=short        display options specific to this package
bison/3.5.3:       --help=recursive    display the short help of all the included packages
bison/3.5.3:   -V, --version           display version information and exit
bison/3.5.3:   -q, --quiet, --silent   do not print `checking ...' messages
bison/3.5.3:       --cache-file=FILE   cache test results in FILE [disabled]
bison/3.5.3:   -C, --config-cache      alias for `--cache-file=config.cache'
bison/3.5.3:   -n, --no-create         do not create output files
bison/3.5.3:       --srcdir=DIR        find the sources in DIR [configure dir or `..']
bison/3.5.3: 
bison/3.5.3: Installation directories:
bison/3.5.3:   --prefix=PREFIX         install architecture-independent files in PREFIX
bison/3.5.3:                           [/usr/local]
bison/3.5.3:   --exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX
bison/3.5.3:                           [PREFIX]
bison/3.5.3: 
bison/3.5.3: By default, `make install' will install all the files in
bison/3.5.3: `/usr/local/bin', `/usr/local/lib' etc.  You can specify
bison/3.5.3: an installation prefix other than `/usr/local' using `--prefix',
bison/3.5.3: for instance `--prefix=$HOME'.
bison/3.5.3: 
bison/3.5.3: For better control, use the options below.
bison/3.5.3: 
bison/3.5.3: Fine tuning of the installation directories:
bison/3.5.3:   --bindir=DIR            user executables [EPREFIX/bin]
bison/3.5.3:   --sbindir=DIR           system admin executables [EPREFIX/sbin]
bison/3.5.3:   --libexecdir=DIR        program executables [EPREFIX/libexec]
bison/3.5.3:   --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
bison/3.5.3:   --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
bison/3.5.3:   --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
bison/3.5.3:   --libdir=DIR            object code libraries [EPREFIX/lib]
bison/3.5.3:   --includedir=DIR        C header files [PREFIX/include]
bison/3.5.3:   --oldincludedir=DIR     C header files for non-gcc [/usr/include]
bison/3.5.3:   --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
bison/3.5.3:   --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
bison/3.5.3:   --infodir=DIR           info documentation [DATAROOTDIR/info]
bison/3.5.3:   --localedir=DIR         locale-dependent data [DATAROOTDIR/locale]
bison/3.5.3:   --mandir=DIR            man documentation [DATAROOTDIR/man]
bison/3.5.3:   --docdir=DIR            documentation root [DATAROOTDIR/doc/bison]
bison/3.5.3:   --htmldir=DIR           html documentation [DOCDIR]
bison/3.5.3:   --dvidir=DIR            dvi documentation [DOCDIR]
bison/3.5.3:   --pdfdir=DIR            pdf documentation [DOCDIR]
bison/3.5.3:   --psdir=DIR             ps documentation [DOCDIR]
bison/3.5.3: 
bison/3.5.3: Program names:
bison/3.5.3:   --program-prefix=PREFIX            prepend PREFIX to installed program names
bison/3.5.3:   --program-suffix=SUFFIX            append SUFFIX to installed program names
bison/3.5.3:   --program-transform-name=PROGRAM   run sed PROGRAM on installed program names
bison/3.5.3: 
bison/3.5.3: System types:
bison/3.5.3:   --build=BUILD     configure for building on BUILD [guessed]
bison/3.5.3:   --host=HOST       cross-compile to build programs to run on HOST [BUILD]
bison/3.5.3: 
bison/3.5.3: Optional Features:
bison/3.5.3:   --disable-option-checking  ignore unrecognized --enable/--with options
bison/3.5.3:   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
bison/3.5.3:   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
bison/3.5.3:   --enable-silent-rules   less verbose build output (undo: "make V=1")
bison/3.5.3:   --disable-silent-rules  verbose build output (undo: "make V=0")
bison/3.5.3:   --enable-dependency-tracking
bison/3.5.3:                           do not reject slow dependency extractors
bison/3.5.3:   --disable-dependency-tracking
bison/3.5.3:                           speeds up one-time build
bison/3.5.3:   --disable-largefile     omit support for large files
bison/3.5.3:   --enable-threads={isoc|posix|isoc+posix|windows}
bison/3.5.3:                           specify multithreading API
bison/3.5.3:   --disable-threads       build without multithread safety
bison/3.5.3:   --enable-gcc-warnings   turn on lots of GCC warnings (not recommended).
bison/3.5.3:                            Also, issue synclines from the examples/ to
bison/3.5.3:                            the corresponding source in the Texinfo doc.
bison/3.5.3:   --disable-yacc          do not build a yacc command or an -ly library
bison/3.5.3:   --enable-cross-guesses={conservative|risky}
bison/3.5.3:                           specify policy for cross-compilation guesses
bison/3.5.3:   --disable-assert        turn off assertions
bison/3.5.3:   --disable-rpath         do not hardcode runtime library paths
bison/3.5.3:   --enable-relocatable    install a package that can be moved in the file
bison/3.5.3:                           system
bison/3.5.3:   --disable-nls           do not use Native Language Support
bison/3.5.3: 
bison/3.5.3: Optional Packages:
bison/3.5.3:   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
bison/3.5.3:   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
bison/3.5.3:   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
bison/3.5.3:   --with-libtextstyle-prefix[=DIR]  search for libtextstyle in DIR/include and DIR/lib
bison/3.5.3:   --without-libtextstyle-prefix     don't search for libtextstyle in includedir and libdir
bison/3.5.3:   --with-libiconv-prefix[=DIR]  search for libiconv in DIR/include and DIR/lib
bison/3.5.3:   --without-libiconv-prefix     don't search for libiconv in includedir and libdir
bison/3.5.3:   --with-libintl-prefix[=DIR]  search for libintl in DIR/include and DIR/lib
bison/3.5.3:   --without-libintl-prefix     don't search for libintl in includedir and libdir
bison/3.5.3: 
bison/3.5.3: Some influential environment variables:
bison/3.5.3:   CC          C compiler command
bison/3.5.3:   CFLAGS      C compiler flags
bison/3.5.3:   LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
bison/3.5.3:               nonstandard directory <lib dir>
bison/3.5.3:   LIBS        libraries to pass to the linker, e.g. -l<library>
bison/3.5.3:   CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
bison/3.5.3:               you have headers in a nonstandard directory <include dir>
bison/3.5.3:   CXX         C++ compiler command
bison/3.5.3:   CXXFLAGS    C++ compiler flags
bison/3.5.3:   CPP         C preprocessor
bison/3.5.3:   YACC        The `Yet Another Compiler Compiler' implementation to use.
bison/3.5.3:               Defaults to the first program found out of: `bison -y', `byacc',
bison/3.5.3:               `yacc'.
bison/3.5.3:   YFLAGS      The list of arguments that will be passed by default to $YACC.
bison/3.5.3:               This script will default YFLAGS to the empty string to avoid a
bison/3.5.3:               default value of `-d' given by some make applications.
bison/3.5.3:   M4          Location of GNU M4 1.4.6 or later. Defaults to the first program
bison/3.5.3:               of 'm4', 'gm4', or 'gnum4' on PATH that meets Autoconf needs.
bison/3.5.3: 
bison/3.5.3: Use these variables to override the choices made by `configure' or to help
bison/3.5.3: it to find libraries and programs with nonstandard names/locations.
bison/3.5.3: 
bison/3.5.3: Report bugs to <bug-bison@gnu.org>.
bison/3.5.3: GNU Bison home page: <https://www.gnu.org/software/bison/>.
bison/3.5.3: General help using GNU software: <http://www.gnu.org/gethelp/>.
bison/3.5.3: Calling:
 > /c/users/appveyor/.conan/data/bison/3.5.3/_/_/build/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/source_subfolder/configure --enable-relocatable --disable-nls --datarootdir=C:/Users/appveyor/.conan/data/bison/3.5.3/_/_/package/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/bin/share --prefix=C:/Users/appveyor/.conan/data/bison/3.5.3/_/_/package/9b01c5b89d2898ea5ee7a34d047e105bdf301e15 --build=x86_64-windows-msvc --host=i686-windows-msvc
bison/3.5.3: run_in_windows_bash: C:\.conan\bc9a75\1\bin\usr\bin\bash.exe --login -c ^"cd \^"/c/users/appveyor/.conan/data/bison/3.5.3/_/_/build/9b01c5b89d2898ea5ee7a34d047e105bdf301e15\^" ^&^& PATH=\^"/c/.conan/bc9a75/1/bin/usr/bin:/c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin:/c/users/appveyor/.conan/data/autoconf/2.69/_/_/package/456f15897172eef340fcbac8a70811f2beb26a93/bin:/c/users/appveyor/.conan/data/m4/1.4.18/_/_/package/b93966b2c7cc0f91e10c82ffc67c5fb2d3101fa3/bin:$PATH\^" ^&^& /c/users/appveyor/.conan/data/bison/3.5.3/_/_/build/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/source_subfolder/configure --enable-relocatable --disable-nls --datarootdir=C:/Users/appveyor/.conan/data/bison/3.5.3/_/_/package/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/bin/share --prefix=C:/Users/appveyor/.conan/data/bison/3.5.3/_/_/package/9b01c5b89d2898ea5ee7a34d047e105bdf301e15 --build=x86_64-windows-msvc --host=i686-windows-msvc ^"
bison/3.5.3: configure: loading site script /mingw32/etc/config.site
bison/3.5.3: checking for a BSD-compatible install... /usr/bin/install -c
bison/3.5.3: checking whether build environment is sane... yes
bison/3.5.3: checking for i686-windows-msvc-strip... :
bison/3.5.3: checking for a thread-safe mkdir -p... /c/.conan/bc9a75/1/bin/usr/bin/mkdir -p
bison/3.5.3: checking for gawk... gawk
bison/3.5.3: checking whether make sets $(MAKE)... yes
bison/3.5.3: checking whether make supports nested variables... yes
bison/3.5.3: checking whether make supports nested variables... (cached) yes
bison/3.5.3: checking whether make supports the include directive... yes (GNU style)
bison/3.5.3: checking for i686-windows-msvc-gcc... /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo
bison/3.5.3: checking whether the C compiler works... yes
bison/3.5.3: checking for C compiler default output file name... conftest.exe
bison/3.5.3: checking for suffix of executables... .exe
bison/3.5.3: checking whether we are cross compiling... yes
bison/3.5.3: checking for suffix of object files... obj
bison/3.5.3: checking whether we are using the GNU C compiler... no
bison/3.5.3: checking whether /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo accepts -g... no
bison/3.5.3: checking for /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo option to enable C11 features... unsupported
bison/3.5.3: checking for /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo option to enable C99 features... unsupported
bison/3.5.3: checking for /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo option to enable C89 features... none needed
bison/3.5.3: checking whether the compiler is clang... no
bison/3.5.3: checking for compiler option needed when checking for declarations... none
bison/3.5.3: checking dependency style of /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo... msvc7
bison/3.5.3: checking whether we are using the GNU C++ compiler... no
bison/3.5.3: checking whether /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo accepts -g... no
bison/3.5.3: checking for /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo option to enable C++11 features... none needed
bison/3.5.3: checking dependency style of /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo... msvc7
bison/3.5.3: checking how to run the C preprocessor... /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/compile cl -nologo -E
bison/3.5.3: checking for grep that handles long lines and -e... /c/.conan/bc9a75/1/bin/usr/bin/grep
bison/3.5.3: checking for egrep... /c/.conan/bc9a75/1/bin/usr/bin/grep -E
bison/3.5.3: checking for ANSI C header files... yes
bison/3.5.3: checking for sys/types.h... yes
bison/3.5.3: checking for sys/stat.h... yes
bison/3.5.3: checking for stdlib.h... yes
bison/3.5.3: checking for string.h... yes
bison/3.5.3: checking for memory.h... yes
bison/3.5.3: checking for strings.h... no
bison/3.5.3: checking for inttypes.h... yes
bison/3.5.3: checking for stdint.h... yes
bison/3.5.3: checking for unistd.h... no
bison/3.5.3: checking minix/config.h usability... no
bison/3.5.3: checking minix/config.h presence... no
bison/3.5.3: checking for minix/config.h... no
bison/3.5.3: checking whether it is safe to define __EXTENSIONS__... yes
bison/3.5.3: checking whether _XOPEN_SOURCE should be defined... no
bison/3.5.3: checking for Minix Amsterdam compiler... no
bison/3.5.3: checking for i686-windows-msvc-ar... /c/users/appveyor/.conan/data/automake/1.16.1/_/_/package/3e48e69237f7f2196164383ef9dedf0f93cbf249/bin/share/automake-1.16/ar-lib lib
bison/3.5.3: checking build system type... Invalid configuration `x86_64-windows-msvc': system `msvc' not recognized
bison/3.5.3: configure: error: /bin/sh /c/users/appveyor/.conan/data/bison/3.5.3/_/_/build/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/source_subfolder/build-aux/config.sub x86_64-windows-msvc failed
bison/3.5.3: 
openstudio_ruby/2.5.5@nrel/testing: WARN: Readline (hence GDBM) will not work on MSVC right now
openstudio_ruby/2.5.5@nrel/testing: WARN: Conan LIBFFI will not allow linking right now with MSVC, so temporarilly built it from CMakeLists instead
openstudio_ruby/2.5.5@nrel/testing: WARN: Conan GMP isn't supported on MSVC
WARN: replace_in_file didn't find pattern '/MTd ' in 'Configurations\10-main.conf' file.
WARN: replace_in_file didn't find pattern '/MTd"' in 'Configurations\10-main.conf' file.
bison/3.5.3: ERROR: Package '9b01c5b89d2898ea5ee7a34d047e105bdf301e15' build failed
bison/3.5.3: WARN: Build folder C:\Users\appveyor\.conan\data\bison\3.5.3\_\_\build\9b01c5b89d2898ea5ee7a34d047e105bdf301e15
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\conans\errors.py", line 34, in conanfile_exception_formatter
    yield
  File "C:\Python37\lib\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method
    conanfile.build()
  File "C:\Users\appveyor\.conan\data\bison\3.5.3\_\_\export\conanfile.py", line 119, in build
    env_build = self._configure_autotools()
  File "C:\Users\appveyor\.conan\data\bison\3.5.3\_\_\export\conanfile.py", line 84, in _configure_autotools
    self._autotools.configure(args=args, configure_dir=self._source_subfolder)
  File "C:\Python37\lib\site-packages\conans\client\build\autotools_environment.py", line 196, in configure
    self._conanfile.run(command, win_bash=self._win_bash, subsystem=self.subsystem)
  File "C:\Python37\lib\site-packages\conans\model\conan_file.py", line 287, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 1 while executing /c/users/appveyor/.conan/data/bison/3.5.3/_/_/build/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/source_subfolder/configure --enable-relocatable --disable-nls --datarootdir=C:/Users/appveyor/.conan/data/bison/3.5.3/_/_/package/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/bin/share --prefix=C:/Users/appveyor/.conan/data/bison/3.5.3/_/_/package/9b01c5b89d2898ea5ee7a34d047e105bdf301e15 --build=x86_64-windows-msvc --host=i686-windows-msvc
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "build.py", line 54, in <module>
    builder.run()
  File "C:\Python37\lib\site-packages\cpt\packager.py", line 594, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "C:\Python37\lib\site-packages\cpt\packager.py", line 687, in run_builds
    r.run()
  File "C:\Python37\lib\site-packages\cpt\runner.py", line 131, in run
    lockfile=self._lockfile)
  File "C:\Python37\lib\site-packages\conans\client\conan_api.py", line 94, in wrapper
    return f(api, *args, **kwargs)
  File "C:\Python37\lib\site-packages\conans\client\conan_api.py", line 376, in create
    test_build_folder, test_folder, conanfile_path, recorder=recorder)
  File "C:\Python37\lib\site-packages\conans\client\cmd\create.py", line 43, in create
    recorder=recorder)
  File "C:\Python37\lib\site-packages\conans\client\cmd\test.py", line 38, in install_build_and_test
    recorder=recorder)
  File "C:\Python37\lib\site-packages\conans\client\manager.py", line 77, in deps_install
    graph_info=graph_info)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 295, in install
    self._build(nodes_by_level, keep_build, root_node, graph_info, remotes, build_mode, update)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 423, in _build
    self._handle_node_cache(node, keep_build, processed_package_refs, remotes)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 481, in _handle_node_cache
    pref = self._build_package(node, output, keep_build, remotes)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 511, in _build_package
    pref = builder.build_package(node, keep_build, self._recorder, remotes)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 227, in build_package
    raise exc
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 215, in build_package
    self._build(conanfile, pref)
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 143, in _build
    raise exc
  File "C:\Python37\lib\site-packages\conans\client\installer.py", line 135, in _build
    run_build_method(conanfile, self._hook_manager, reference=pref.ref, package_id=pref.id)
  File "C:\Python37\lib\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method
    conanfile.build()
  File "C:\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python37\lib\site-packages\conans\errors.py", line 40, in conanfile_exception_formatter
    raise ConanExceptionInUserConanfileMethod(msg)
conans.errors.ConanExceptionInUserConanfileMethod: bison/3.5.3: Error in build() method, line 119
	env_build = self._configure_autotools()
while calling '_configure_autotools', line 84
	self._autotools.configure(args=args, configure_dir=self._source_subfolder)
	ConanException: Error 1 while executing /c/users/appveyor/.conan/data/bison/3.5.3/_/_/build/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/source_subfolder/configure --enable-relocatable --disable-nls --datarootdir=C:/Users/appveyor/.conan/data/bison/3.5.3/_/_/package/9b01c5b89d2898ea5ee7a34d047e105bdf301e15/bin/share --prefix=C:/Users/appveyor/.conan/data/bison/3.5.3/_/_/package/9b01c5b89d2898ea5ee7a34d047e105bdf301e15 --build=x86_64-windows-msvc --host=i686-windows-msvc
Command exited with code 1

```

</details>

**Comment by madebr** [comment]
This means that all projects using msvc, autotools and `AC_CANONICAL_*` might fail when crossbuilding.

**Comment by madebr** [comment]
I can confirm. The triplet `x86_64-windows-msvc`, generated by conan is not recognized by gnu-config.
On Windows' msys2, it detects `x86_64-pc-mingw64`.
