### ISSUE TITLE
[package] libcurl/7.71.1 : Issue building on CentOS 7

### ISSUE THREAD

**Issue by rdeterre** [conan-io/conan-center-index#2413]
Hi,

I'm having trouble building the libcurl package on CentOS 7. The `conan install` commands outputs the following error:

```
conanfile.py: ERROR: Generator cmake(file:conanbuildinfo.cmake) failed
'libcrypto'
ERROR: 'libcrypto'
```

I'm building using a docker image based on `centos:7`. If I use `conanio/gcc48` instead (CentOS 7 uses GCC 4.8), everything works.

The complete Dockerfile I use is:

<details><summary>Dockerfile</summary>

```
FROM centos:7

RUN yum update -y \
    && yum groupinstall -y 'Development Tools' \
    && yum install -y \
        bash \
        git \
        gtk2-devel \
        libstdc++-static \
        libssh \
        mesa-libGLU-devel \
        python3-devel \
        python3-pip \
        qt5-qtbase-devel \
        rpm \
        wget \
        which \
        cmake \
    && pip3 install --upgrade pip

ADD common/requirements.txt .

RUN pip install -r requirements.txt \
    && conan remote add bincrafters \
        https://api.bintray.com/conan/bincrafters/public-conan True \
    && conan remote add ottawa http://10.3.30.158:9300 True

ADD common/conanfile.py .
RUN conan install . --build missing
```

</details>

This file pulls in requirements.txt and conanfile.py, which are respectively:
<details><summary>requirements.txt</summary>

```
pipenv==2020.6.2
conan==1.28.0
```

</details>

<details><summary>conanfile.py</summary>

```
import os
import shutil
from datetime import datetime

from conans import CMake, ConanFile, tools
from conans.tools import Version


class CommonDependenciesConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    requires = (
        "libcurl/7.71.1"
    )
    generators = "cmake"
    exports = "*"
```

</details>

In addition, if I run `conan install libcurl/7.71.1@` instead of using a `conanfile.py`, the installation works well.

Lastly, the problem is the same with older libcurl versions. I tried `libcurl/7.71.0` and `libcurl/7.70.0`.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.71.1**
  * Operating System+version: **CentOS 7**
  * Compiler+version: **GCC 4.8**
  * Docker image: **centos:7**
  * Conan version: **conan 1.28.0**
  * Python version: **Python 3.6.8**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=4.8
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=4.8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

libcurl/7.71.1: Not found in local cache, looking in remotes...
libcurl/7.71.1: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
libcurl/7.71.1: Downloaded recipe revision 0
conanfile.py: Installing package
Requirements
    libcurl/7.71.1 from 'conan-center' - Downloaded
    openssl/1.1.1g from 'conan-center' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    libcurl/7.71.1:fd492abe6eef240bcc16f4a70e81bb240bcf9bd0 - Build
    openssl/1.1.1g:3a5f72c8cd50641b8efa6ed13e6914c6ced2747c - Cache
    zlib/1.2.11:3a5f72c8cd50641b8efa6ed13e6914c6ced2747c - Cache
Build requirements
    autoconf/2.69 from 'conan-center' - Cache
    automake/1.16.2 from 'conan-center' - Cache
    libtool/2.4.6 from 'conan-center' - Cache
    m4/1.4.18 from 'conan-center' - Cache
Build requirements packages
    autoconf/2.69:44fcf6b9a7fb86b2586303e3db40189d3b511830 - Cache
    automake/1.16.2:258f6f05ca54813b3d7180161753df7f9ccf7e1d - Cache
    libtool/2.4.6:e8a3ee862fc5369b49ea810e9343980b53c26b96 - Cache
    m4/1.4.18:80206e07321641d2362b7a56ceaf8254914e44f7 - Cache

Installing (downloading, building) binaries...
m4/1.4.18: Already installed!
m4/1.4.18: Appending PATH environment variable: /root/.conan/data/m4/1.4.18/_/_/package/80206e07321641d2362b7a56ceaf8254914e44f7/bin
m4/1.4.18: Setting M4 environment variable: /root/.conan/data/m4/1.4.18/_/_/package/80206e07321641d2362b7a56ceaf8254914e44f7/bin/m4
openssl/1.1.1g: Already installed!
zlib/1.2.11: Already installed!
autoconf/2.69: Already installed!
autoconf/2.69: Appending PATH env var with : /root/.conan/data/autoconf/2.69/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin
autoconf/2.69: Setting AC_MACRODIR to /root/.conan/data/autoconf/2.69/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/share/autoconf
autoconf/2.69: Setting AUTOCONF to /root/.conan/data/autoconf/2.69/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/autoconf
autoconf/2.69: Setting AUTORECONF to /root/.conan/data/autoconf/2.69/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/autoreconf
autoconf/2.69: Setting AUTOHEADER to /root/.conan/data/autoconf/2.69/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/autoheader
autoconf/2.69: Setting AUTOM4TE to /root/.conan/data/autoconf/2.69/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/autom4te
autoconf/2.69: Setting AUTOM4TE_PERLLIBDIR to /root/.conan/data/autoconf/2.69/_/_/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/share/autoconf
automake/1.16.2: Already installed!
automake/1.16.2: Appending PATH env var with : /root/.conan/data/automake/1.16.2/_/_/package/258f6f05ca54813b3d7180161753df7f9ccf7e1d/bin
automake/1.16.2: Setting ACLOCAL to /root/.conan/data/automake/1.16.2/_/_/package/258f6f05ca54813b3d7180161753df7f9ccf7e1d/bin/aclocal
automake/1.16.2: Setting AUTOMAKE_DATADIR to /root/.conan/data/automake/1.16.2/_/_/package/258f6f05ca54813b3d7180161753df7f9ccf7e1d/bin/share
automake/1.16.2: Setting AUTOMAKE_LIBDIR to /root/.conan/data/automake/1.16.2/_/_/package/258f6f05ca54813b3d7180161753df7f9ccf7e1d/bin/share/automake-1.16
automake/1.16.2: Setting AUTOMAKE_PERLLIBDIR to /root/.conan/data/automake/1.16.2/_/_/package/258f6f05ca54813b3d7180161753df7f9ccf7e1d/bin/share/automake-1.16
automake/1.16.2: Setting AUTOMAKE to /root/.conan/data/automake/1.16.2/_/_/package/258f6f05ca54813b3d7180161753df7f9ccf7e1d/bin/automake
automake/1.16.2: Append M4 include directories to AUTOMAKE_CONAN_INCLUDES environment variable
libtool/2.4.6: Already installed!
libtool/2.4.6: Appending PATH env: /root/.conan/data/libtool/2.4.6/_/_/package/e8a3ee862fc5369b49ea810e9343980b53c26b96/bin
libtool/2.4.6: Setting LIBTOOLIZE env to /root/.conan/data/libtool/2.4.6/_/_/package/e8a3ee862fc5369b49ea810e9343980b53c26b96/bin/libtoolize
libtool/2.4.6: Appending ACLOCAL_PATH env: /root/.conan/data/libtool/2.4.6/_/_/package/e8a3ee862fc5369b49ea810e9343980b53c26b96/bin/share/aclocal
libtool/2.4.6: Setting LIBTOOL_PREFIX environment variable to /root/.conan/data/libtool/2.4.6/_/_/package/e8a3ee862fc5369b49ea810e9343980b53c26b96
libtool/2.4.6: Setting LIBTOOL_DATADIR environment variable to /root/.conan/data/libtool/2.4.6/_/_/package/e8a3ee862fc5369b49ea810e9343980b53c26b96/bin/share
libtool/2.4.6: Setting LIBTOOL_PKGAUXDIR environment variable to /root/.conan/data/libtool/2.4.6/_/_/package/e8a3ee862fc5369b49ea810e9343980b53c26b96/bin/share/libtool/build-aux
libtool/2.4.6: Setting LIBTOOL_PKGLTDLDIR environment variable to /root/.conan/data/libtool/2.4.6/_/_/package/e8a3ee862fc5369b49ea810e9343980b53c26b96/bin/share/libtool
libtool/2.4.6: Setting LIBTOOL_ACLOCALDIR environment variable to /root/.conan/data/libtool/2.4.6/_/_/package/e8a3ee862fc5369b49ea810e9343980b53c26b96/bin/share/aclocal
libtool/2.4.6: Appending AUTOMAKE_CONAN_INCLUDES environment variable: /root/.conan/data/libtool/2.4.6/_/_/package/e8a3ee862fc5369b49ea810e9343980b53c26b96/bin/share/aclocal
libcurl/7.71.1: Applying build-requirement: libtool/2.4.6
libcurl/7.71.1: Applying build-requirement: automake/1.16.2
libcurl/7.71.1: Applying build-requirement: autoconf/2.69
libcurl/7.71.1: Applying build-requirement: m4/1.4.18
Downloading conan_sources.tgz
libcurl/7.71.1: Configuring sources in /root/.conan/data/libcurl/7.71.1/_/_/source


libcurl/7.71.1: Copying sources to build folder
libcurl/7.71.1: Building your package in /root/.conan/data/libcurl/7.71.1/_/_/build/fd492abe6eef240bcc16f4a70e81bb240bcf9bd0
libcurl/7.71.1: Generator pkg_config created libtool.pc
libcurl/7.71.1: Generator pkg_config created libcrypto.pc
libcurl/7.71.1: Generator pkg_config created libssl.pc
libcurl/7.71.1: Generator pkg_config created openssl.pc
libcurl/7.71.1: Generator pkg_config created zlib.pc
libcurl/7.71.1: Generator pkg_config created automake.pc
libcurl/7.71.1: Generator pkg_config created autoconf.pc
libcurl/7.71.1: Generator pkg_config created m4.pc
libcurl/7.71.1: ERROR: Generator cmake(file:conanbuildinfo.cmake) failed
'libcrypto'
ERROR: 'libcrypto'

```

</details>

Since the error is not very verbose, even when `log` is set to `debug` in conan.conf, I  set `CONAN_VERBOSE_TRACEBACK=1` and got the following output:

```
libcurl/7.71.1: Copying sources to build folder
libcurl/7.71.1: Building your package in /root/.conan/data/libcurl/7.71.1/_/_/build/fd492abe6eef240bcc16f4a70e81bb240bcf9bd0
libcurl/7.71.1: Generator pkg_config created libtool.pc
libcurl/7.71.1: Generator pkg_config created libcrypto.pc
libcurl/7.71.1: Generator pkg_config created libssl.pc
libcurl/7.71.1: Generator pkg_config created openssl.pc
libcurl/7.71.1: Generator pkg_config created zlib.pc
libcurl/7.71.1: Generator pkg_config created automake.pc
libcurl/7.71.1: Generator pkg_config created autoconf.pc
libcurl/7.71.1: Generator pkg_config created m4.pc
libcurl/7.71.1: ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/conans/client/generators/__init__.py", line 108, in write_generators
    content = generator.content
  File "/usr/local/lib/python3.6/site-packages/conans/client/generators/cmake.py", line 109, in content
    sections.extend(generate_targets_section(self.deps_build_info.dependencies, "cmake"))
  File "/usr/local/lib/python3.6/site-packages/conans/client/generators/cmake_common.py", line 224, in generate_targets_section
    use_deps = ["CONAN_PKG::%s" % dependencies_dict[d].get_name(generator_name) for d in dep_info.public_deps]
  File "/usr/local/lib/python3.6/site-packages/conans/client/generators/cmake_common.py", line 224, in <listcomp>
    use_deps = ["CONAN_PKG::%s" % dependencies_dict[d].get_name(generator_name) for d in dep_info.public_deps]
KeyError: 'libcrypto'

libcurl/7.71.1: ERROR: Generator cmake(file:conanbuildinfo.cmake) failed
'libcrypto'
ERROR: 'libcrypto'
```

**Comment by madebr** [comment]
This looks like https://github.com/conan-io/conan/issues/7474
You will have to revert to 1.27 or wait for 1.28.1

**Comment by rdeterre** [comment]
That's right, the problem goes away with Conan 1.27. Thanks for your help!

Should I close this issue now?

**Comment by madebr** [comment]
#7474 is closed too, and this problem is not really cci related.
There is nothing more we can do here, so closing is the only way forward.
