### ISSUE TITLE
[package] cpython/3.10.14: DLL load failed while importing _{module_name}: The specified module could not be found

### ISSUE THREAD

**Issue by maksim-petukhou** [conan-io/conan-center-index#24630]
### Description

The problem arises only on Windows when the requirement for a module you are trying to use is built with `shared=True`. In my particular case, I have shared OpenSSL and I'm trying to use the `ssl` module in Python. This also applies when you're using this module indirectly. For example, you will encounter the same error if you try to use `pip install` to install some package because `pip` uses the `ssl` module under the hood.

The root of the problem is that cpython doesn't use [default dll search order](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order) to load module DLLs. It passes `LOAD_LIBRARY_SEARCH_DEFAULT_DIRS | LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR` flags to a [LoadLibraryExW](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw) function which disables default dll search order and allows to load dlls only from the same directory where module dll (`_ssl.pyd` in my case) is located (this would be `conan-cpython-root/bin/DLLs`) or from directories which are added with [AddDllDirectory](https://learn.microsoft.com/en-us/windows/desktop/api/libloaderapi/nf-libloaderapi-adddlldirectory) function:

https://github.com/python/cpython/blob/48f9d3e3faec5faaa4f7c9849fecd27eae4da213/Python/dynload_win.c#L190-L198

Conan relies on a default dll search order and adds openssl bin directory to a PATH which doesn't work in this case.

There are some workarounds I came up with:
1. You can modify `test.py` (from **Steps to reproduce**) in such way:

```
import os


if os.name == "nt":
    paths = os.environ.get("PATH", "")
    for p in paths.split(";"):
        if os.path.exists(p):
            os.add_dll_directory(p)

import ssl # works
```

But this will not work with `pip`. You'll have to create a wrapper for it (which is not officially supported by `pip` itself but works):

```
import os
import pip


if os.name == "nt":
    paths = os.environ.get("PATH", "")
    for p in paths.split(";"):
        if os.path.exists(p):
            os.add_dll_directory(p)


def install(package):
    if hasattr(pip, 'main'):
        pip.main(['install', package])
    else:
        pip._internal.main(['install', package])


if __name__ == '__main__':
    install("jinja2") # works
```

2. We can patch cpython to not pass `LOAD_LIBRARY_SEARCH_DEFAULT_DIRS | LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR` flags to a `LoadLibraryExW` which will force cpython to use default dll search order

3. We can copy dlls of the dependencies to a cpython package bin/DLLs directory

And each of these methods has its drawbacks.

### Package and Environment Details

* Package Name/Version: **cpython/3.10.14**
* Operating System+version: **Windows 11**
* Compiler+version: **msvc 192**
* Conan version: **conan 2.5.0**
* Python version: **Python 3.10.0**

### Conan profile

```
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
os=Windows
[options]
cpython/*:shared=True
openssl/*:shared=True
```

### Steps to reproduce

1. Create conanfile.py

```python
from conan import ConanFile
from conan.tools.layout import basic_layout
from conan.tools.env import VirtualBuildEnv
from conan.tools.files import copy

import os


class TestCpythonModuleImportConan(ConanFile):
    name = "test-cpython-module-import"
    version = "1.0"
    settings = "os", "arch", "compiler", "build_type"

    def export_sources(self):
        copy(self, "test.py", src=self.recipe_folder, dst=self.export_sources_folder)

    def layout(self):
        basic_layout(self, src_folder="src")

    def build_requirements(self):
        self.tool_requires("cpython/3.10.14")

    def generate(self):
        tc = VirtualBuildEnv(self)
        tc.generate(scope="build")

    def build(self):
        self.run(f"python {os.path.join(self.export_sources_folder, 'test.py')}")

```

2. Create test.py

```
import ssl

```

3. Run

`conan create . -o:b=cpython/*:shared=True -o:b=openssl/*:shared=True -pr:h=host-profile -pr:b=build-profile --build=missing`

### Logs

<details><summary>Click to expand log</summary>

```
...
-------- Installing package test-cpython-module-import/1.0 (14 of 14) --------
test-cpython-module-import/1.0: Building from source
test-cpython-module-import/1.0: Package test-cpython-module-import/1.0:50403a14ae7ffa7f16e59375c94b5b0598ef37d3
test-cpython-module-import/1.0: Copying sources to build folder
test-cpython-module-import/1.0: Building your package in C:\Users\Use\.conan2\p\b\test-82ec2a533f82c\b
test-cpython-module-import/1.0: Calling generate()
test-cpython-module-import/1.0: Generators folder: C:\Users\User\.conan2\p\b\test-82ec2a533f82c\b\build-release\conan
test-cpython-module-import/1.0: Generating aggregated env files
test-cpython-module-import/1.0: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
test-cpython-module-import/1.0: Calling build()
test-cpython-module-import/1.0: RUN: python C:\Users\User\.conan2\p\test-9d0c57dc89faf\s\test.py
Traceback (most recent call last):
  File "C:\Users\User\.conan2\p\test-9d0c57dc89faf\s\test.py", line 1, in <module>
    import ssl
  File "C:\Users\User\.conan2\p\b\cpyth2dd1a28692d18\p\bin\lib\ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed while importing _ssl: The specified module could not be found

test-cpython-module-import/1.0: ERROR:
Package '50403a14ae7ffa7f16e59375c94b5b0598ef37d3' build failed
```

</details>

**Comment by jcar87** [comment]
Hi @maksim-petukhov  - thanks for reporting this.

I would treat the cpython recipe with a bit of caution in terms of how to use it, since it is:
* an application (the interpreter)
* a library (headers and library) that has a dual use:
    - for python modules (shared libraries), it may need to be visible to the linker, but it must not be linked
    - but it may be linked if one is creating executables with an embedded interpreter
* a python "distribution" (in the sense that one may or may not have the expectation to be able to operate more widely with it)

Currently none of the Conan 2 package types support such a special use case, so there may be some limitations, this being one of them.

As for the reported issue, I would distinguish two cases:
1. ability to do `import ssl`, if the ssl module is part of the cpython package
2. ability to do `import xxx` where xxx is a module you are building with other conan dependencies


For the former, this would be a recipe bug. I'd personally not copy the DLLs into the package - as this can actually interfere with openssl elsewhere in the graph. However, we can consider linking openssl statically unconditionally - but that's not currently possible to do in a reliable way while supporting both Conan 1 and Conan 2.

For the latter, I would not expect this to work out of the box  - and I would also opt to follow the convention of linking all dependencies of the module statically.

Regardless of the above, I believe there is a potentially easy solution this -  site module can be used for custom initialisation that is global to the interpreter.

So you can create a file called `sitecustomize.py` with contents:

```
import os

if os.name == "nt":
    paths = os.environ.get("PATH", "")
    for p in paths.split(";"):
        if os.path.exists(p):
            os.add_dll_directory(p)

```

and then simply pass the path to that file to the `PYTHONPATH` environment variable. Then it should globally apply. Even better, if you want to be more strict and less prone to errors, you can generate the contents of this file via the `generate()` method, such that you only add the directories from conan dependencies, rather than EVERYTHING in the `PATH` variable. 

I would stay away from patching the interpreter itself from considering the `PATH` variable directly - they steered away from this for a reason.
