### ISSUE TITLE
[package] boost/1.74.0: ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by jwillikers** [conan-io/conan-center-index#3384]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.74.0**
  * Operating System+version: **Linux CentOS 7.8**
  * Compiler+version: **GCC 10.2**
  * Conan version: **conan 1.30.2** (installed through Pipenv)
  * Python version: **Python 3.9.0** (installed / available through asdf)
  * Tar version: **GNU Tar 1.32** (installed from source)
  * bzip2 version: **bzip2 1.0.8** (installed from source)

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
compiler.cppstd=20
build_type=Release
```

### Steps to reproduce (Include if Applicable)
```sh
$ mkdir build
$ cd build
$ conan install .. --build=missing --profile=../my-profile
...
boost/1.74.0: Applying build-requirement: b2/4.2.0
boost/1.74.0: WARN: Build folder is dirty, removing it: /home/jwill/.conan/data/boost/1.74.0/_/_/build/13be98c64c170d06f8226ebceba69791c7c2ea91
boost/1.74.0: WARN: Trying to remove corrupted source folder
boost/1.74.0: WARN: This can take a while for big packages
boost/1.74.0: Configuring sources in /home/jwill/.conan/data/boost/1.74.0/_/_/source
Downloading boost_1_74_0.tar.bz2 completed [107031.87k]

ERROR: Traceback (most recent call last):
  File "/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/client/source.py", line 143, in _run_source
    conanfile.source()
  File "/home/jwill/.conan/data/boost/1.74.0/_/_/export/conanfile.py", line 178, in source
    tools.get(**self.conan_data["sources"][self.version])
  File "/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/tools.py", line 83, in get
    return tools_net.get(output=_global_output, requester=_global_requester, *args, **kwargs)
  File "/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/client/tools/net.py", line 26, in get
    unzip(filename, destination=destination, keep_permissions=keep_permissions, pattern=pattern,
  File "/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/client/tools/files.py", line 75, in unzip
    return untargz(filename, destination, pattern)
  File "/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/client/tools/files.py", line 143, in untargz
    with tarfile.TarFile.open(filename, 'r:*') as tarredgzippedFile:
  File "/home/jwill/.asdf/installs/python/3.9.0/lib/python3.9/tarfile.py", line 1614, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
{"_action": "COMMAND", "name": "install", "parameters": {"build": ["missing"], "channel": null, "env": null, "generators": null, "install_folder": "build", "lockfile": null, "lockfile_out": null, "manifests": null, "manifests_interactive": null, "name": null, "no_imports": false, "options": null, "path": ".", "profile_build": [null, null, null, null], "profile_names": ["profiles/centos7"], "remote_name": null, "settings": null, "update": false, "user": null, "verify": null, "version": null}, "time": 1604434397.1745236}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "benchmark/1.5.2", "time": 1604434397.2108912}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "boost/1.74.0", "time": 1604434397.215427}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "zlib/1.2.11", "time": 1604434397.228203}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "bzip2/1.0.8", "time": 1604434397.2336674}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "fmt/7.1.0", "time": 1604434397.2372048}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "ms-gsl/3.1.0", "time": 1604434397.2408624}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "quill/1.4.0", "time": 1604434397.2447393}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "tomlplusplus/2.2.0", "time": 1604434397.2488492}
{"_action": "REST_API_CALL", "duration": 0.27437567710876465, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1604434397.5317724, "url": "https://conan.bintray.com/v1/ping"}
{"_action": "REST_API_CALL", "duration": 0.11702108383178711, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1604434397.6499178, "url": "https://conan.bintray.com/v1/conans/boost/1.74.0/_/_/packages/13be98c64c170d06f8226ebceba69791c7c2ea91/download_urls"}
{"_action": "REST_API_CALL", "duration": 0.08781027793884277, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1604434397.7403321, "url": "https://conan.bintray.com/v1/conans/quill/1.4.0/_/_/packages/2f8d6866984cf9c9262a45a6675ee1fab9a81fe2/download_urls"}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "b2/4.2.0", "time": 1604434397.743624}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "b2/4.2.0:44fcf6b9a7fb86b2586303e3db40189d3b511830", "time": 1604434397.7507484}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "benchmark/1.5.2:9e57163b5ff5c67e957f53eb92839ead8174e9d7", "time": 1604434397.7531085}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "bzip2/1.0.8:91a8b22c2c5a149bc617cfc06cdd21bf23b12567", "time": 1604434397.754259}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "fmt/7.1.0:1291f461f6832a5b3098e2156f727f267fd98612", "time": 1604434397.7552145}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "ms-gsl/3.1.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", "time": 1604434397.755917}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "tomlplusplus/2.2.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", "time": 1604434397.756594}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "zlib/1.2.11:19729b9559f3ae196cad45cb2b97468ccb75dcd1", "time": 1604434397.7571495}
{"_action": "REST_API_CALL", "duration": 0.5367279052734375, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0"}, "method": "GET", "time": 1604434398.3031433, "url": "https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.bz2"}
{"_action": "DOWNLOAD", "duration": 13.602269649505615, "time": 1604434411.3686707, "url": "https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.bz2"}
{"_action": "EXCEPTION", "class": "ConanExceptionInUserConanfileMethod", "message": "boost/1.74.0: Error in source() method, line 178\n\ttools.get(**self.conan_data[\"sources\"][self.version])\n\tReadError: file could not be opened successfully", "time": 1604434411.8337767}
{"_action": "COMMAND", "name": "install", "parameters": {"build": ["missing"], "channel": null, "env": null, "generators": null, "install_folder": "build", "lockfile": null, "lockfile_out": null, "manifests": null, "manifests_interactive": null, "name": null, "no_imports": false, "options": null, "path": ".", "profile_build": [null, null, null, null], "profile_names": ["profiles/centos7"], "remote_name": null, "settings": null, "update": false, "user": null, "verify": null, "version": null}, "time": 1604434437.416722}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "benchmark/1.5.2", "time": 1604434437.4626534}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "boost/1.74.0", "time": 1604434437.4680836}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "zlib/1.2.11", "time": 1604434437.4827962}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "bzip2/1.0.8", "time": 1604434437.489718}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "fmt/7.1.0", "time": 1604434437.49422}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "ms-gsl/3.1.0", "time": 1604434437.4989989}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "quill/1.4.0", "time": 1604434437.5060253}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "tomlplusplus/2.2.0", "time": 1604434437.5127058}
{"_action": "REST_API_CALL", "duration": 0.2902648448944092, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1604434437.8134966, "url": "https://conan.bintray.com/v1/ping"}
{"_action": "REST_API_CALL", "duration": 0.10442018508911133, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1604434437.9189863, "url": "https://conan.bintray.com/v1/conans/boost/1.74.0/_/_/packages/13be98c64c170d06f8226ebceba69791c7c2ea91/download_urls"}
{"_action": "REST_API_CALL", "duration": 0.08863210678100586, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1604434438.0103486, "url": "https://conan.bintray.com/v1/conans/quill/1.4.0/_/_/packages/2f8d6866984cf9c9262a45a6675ee1fab9a81fe2/download_urls"}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "b2/4.2.0", "time": 1604434438.0127642}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "b2/4.2.0:44fcf6b9a7fb86b2586303e3db40189d3b511830", "time": 1604434438.0180855}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "benchmark/1.5.2:9e57163b5ff5c67e957f53eb92839ead8174e9d7", "time": 1604434438.019447}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "bzip2/1.0.8:91a8b22c2c5a149bc617cfc06cdd21bf23b12567", "time": 1604434438.0200992}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "fmt/7.1.0:1291f461f6832a5b3098e2156f727f267fd98612", "time": 1604434438.0207527}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "ms-gsl/3.1.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", "time": 1604434438.021393}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "tomlplusplus/2.2.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", "time": 1604434438.0220892}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "zlib/1.2.11:19729b9559f3ae196cad45cb2b97468ccb75dcd1", "time": 1604434438.02271}
{"_action": "REST_API_CALL", "duration": 0.5207068920135498, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0"}, "method": "GET", "time": 1604434438.5647697, "url": "https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.bz2"}
{"_action": "DOWNLOAD", "duration": 13.611560821533203, "time": 1604434451.655615, "url": "https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.bz2"}
{"_action": "EXCEPTION", "class": "ConanExceptionInUserConanfileMethod", "message": "boost/1.74.0: Error in source() method, line 178\n\ttools.get(**self.conan_data[\"sources\"][self.version])\n\tReadError: file could not be opened successfully", "time": 1604434452.2213962}
{"_action": "COMMAND", "name": "install", "parameters": {"build": ["missing"], "channel": null, "env": null, "generators": null, "install_folder": "build", "lockfile": null, "lockfile_out": null, "manifests": null, "manifests_interactive": null, "name": null, "no_imports": false, "options": null, "path": ".", "profile_build": [null, null, null, null], "profile_names": ["profiles/centos7"], "remote_name": null, "settings": null, "update": false, "user": null, "verify": null, "version": null}, "time": 1604434577.6262596}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "benchmark/1.5.2", "time": 1604434577.6626885}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "boost/1.74.0", "time": 1604434577.6671848}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "zlib/1.2.11", "time": 1604434577.6798372}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "bzip2/1.0.8", "time": 1604434577.6851864}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "fmt/7.1.0", "time": 1604434577.688646}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "ms-gsl/3.1.0", "time": 1604434577.6926413}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "quill/1.4.0", "time": 1604434577.6965537}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "tomlplusplus/2.2.0", "time": 1604434577.7009947}
{"_action": "REST_API_CALL", "duration": 0.47042036056518555, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1604434578.1797612, "url": "https://conan.bintray.com/v1/ping"}
{"_action": "REST_API_CALL", "duration": 0.16994380950927734, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1604434578.35076, "url": "https://conan.bintray.com/v1/conans/boost/1.74.0/_/_/packages/13be98c64c170d06f8226ebceba69791c7c2ea91/download_urls"}
{"_action": "REST_API_CALL", "duration": 0.09412074089050293, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1604434578.447519, "url": "https://conan.bintray.com/v1/conans/quill/1.4.0/_/_/packages/2f8d6866984cf9c9262a45a6675ee1fab9a81fe2/download_urls"}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "b2/4.2.0", "time": 1604434578.449945}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "b2/4.2.0:44fcf6b9a7fb86b2586303e3db40189d3b511830", "time": 1604434578.4552276}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "benchmark/1.5.2:9e57163b5ff5c67e957f53eb92839ead8174e9d7", "time": 1604434578.456544}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "bzip2/1.0.8:91a8b22c2c5a149bc617cfc06cdd21bf23b12567", "time": 1604434578.457201}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "fmt/7.1.0:1291f461f6832a5b3098e2156f727f267fd98612", "time": 1604434578.4578304}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "ms-gsl/3.1.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", "time": 1604434578.4584668}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "tomlplusplus/2.2.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9", "time": 1604434578.4591613}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "zlib/1.2.11:19729b9559f3ae196cad45cb2b97468ccb75dcd1", "time": 1604434578.4597392}
{"_action": "REST_API_CALL", "duration": 0.520237922668457, "headers": {"User-Agent": "Conan/1.30.2 (Python 3.9.0) python-requests/2.24.0"}, "method": "GET", "time": 1604434579.0015607, "url": "https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.bz2"}
{"_action": "DOWNLOAD", "duration": 13.909408330917358, "time": 1604434592.3907084, "url": "https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.bz2"}
{"_action": "EXCEPTION", "class": "ConanExceptionInUserConanfileMethod", "message": "Traceback (most recent call last):\n  File \"/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/errors.py\", line 34, in conanfile_exception_formatter\n    yield\n  File \"/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/client/source.py\", line 143, in _run_source\n    conanfile.source()\n  File \"/home/jwill/.conan/data/boost/1.74.0/_/_/export/conanfile.py\", line 178, in source\n    tools.get(**self.conan_data[\"sources\"][self.version])\n  File \"/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/tools.py\", line 83, in get\n    return tools_net.get(output=_global_output, requester=_global_requester, *args, **kwargs)\n  File \"/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/client/tools/net.py\", line 26, in get\n    unzip(filename, destination=destination, keep_permissions=keep_permissions, pattern=pattern,\n  File \"/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/client/tools/files.py\", line 75, in unzip\n    return untargz(filename, destination, pattern)\n  File \"/home/jwill/.virtualenvs/heliosplot/lib/python3.9/site-packages/conans/client/tools/files.py\", line 143, in untargz\n    with tarfile.TarFile.open(filename, 'r:*') as tarredgzippedFile:\n  File \"/home/jwill/.asdf/installs/python/3.9.0/lib/python3.9/tarfile.py\", line 1614, in open\n    raise ReadError(\"file could not be opened successfully\")\ntarfile.ReadError: file could not be opened successfully\n", "time": 1604434593.1453269}
```

</details>
It appears to be able to successfully download boost but then has an error opening a file.

**Comment by madebr** [comment]
Was this a fluke or is this error repeatable?
Is there sufficient free disk space on the volume containing the conan home?

**Comment by jwillikers** [comment]
The error is 100% repeatable. I have about 20GB free on my home partition, so I don't think it is a space issue.

**Comment by jwillikers** [comment]
I can successfully decompress the boost source tarball which Conan downloaded, so it is not a space issue.

**Comment by madebr** [comment]
Does enabling [`verbose_traceback`](https://docs.conan.io/en/latest/reference/config_files/conan.conf.html) return a more useful traceback?

**Comment by jwillikers** [comment]
Well, that's super helpful! I've updated the bug report with the output when `verbose_traceback` is enabled.

**Comment by madebr** [comment]
It looks like [`tarfile.TarFile.open`](https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.open) does not work.
What does manually running the following inside python3 give?
```python
import tarfile
tarfile.TarFile.open("/path/to/manually/downloaded/boost/sources.tar.bz2", 'r:*')
```

**Comment by jwillikers** [comment]
It gives me the exact same error.

```python
Python 3.9.0 (default, Oct 26 2020, 14:24:03)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tarfile
>>> tarfile.TarFile.open("/home/jwill/Downloads/boost_1_74_0.tar.bz2", 'r:*')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jwill/.asdf/installs/python/3.9.0/lib/python3.9/tarfile.py", line 1614, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

**Comment by madebr** [comment]
I think this means the problem is with your linux distribution, more specific python and/or bzip2.
It looks like it is not able to extract `bz2` archives. Do you have `bzip2` installed?
You can do a few things:
- check bz2/tar (extract from the command line)
- open a ticket to the centos python package maintainer 
- comment at https://bugs.python.org/issue8978 with a short reproducer

(I am not able to reproduce it on python 3.7.7@Linux and python3.9.0@Windows)

**Comment by jwillikers** [comment]
@madebr Thanks for your help.

- Both tar and bzip2 work correctly from the command-line.
- I'm using asdf, which uses Pyenv internally, to build and manage the python version, so it doesn't involve the CentOS package maintainer.
- I have left a [comment](https://bugs.python.org/issue8978?@ok_message=msg%20380322%20created%0Aissue%208978%20message_count%2C%20type%2C%20versions%2C%20nosy%2C%20nosy_count%2C%20messages%20edited%20ok&@template=item#msg380322) on the related issue.

I managed to fix the issue by installing bzip2, including it's shared library, from source and then rebuilding Python.
