### ISSUE TITLE
[package] gtk/3.24.24: Windows support

### ISSUE THREAD

**Issue by ericLemanissier** [conan-io/conan-center-index#4306]
### Package and Environment Details
  * Package Name/Version: **gtk/3.24.24**
  * Operating System+version: **Windows**
  * Compiler+version: **msvc**
  * Conan version: **conan 1.32.1**
  * Python version: **Python 3.8.0**

### Steps to reproduce

Currently gtk recipe does not support windows, because of all the following issues:

1.  compilation of first file fails with:
```
ninja: fatal: CreateProcess: ParamÞtre incorrect.
 (is the command line too long?)
 ```
 
this is solved by using `short_paths = True`

2. it fails later at link stage with `fatal error LNK1170: line in command file contains 131071 or more characters`

this is solved by using `CONAN_USE_ALWAYS_SHORT_PATHS=1` environment variable.

3.

```
FAILED: gtk/gtk-query-settings.exe gtk/gtk-query-settings.pdb
"link" @gtk/gtk-query-settings.exe.rsp
libgdk-3.a(gdkmain-win32.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
gdk_pixbuf-2.0.lib(gdk-pixbuf-io.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
atk-1.0.lib(atkprivate.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
   Création de la bibliothèque gtk\gtk-query-settings.lib et de l'objet gtk\gtk-query-settings.exp
LINK : warning LNK4286: le symbole 'atk_misc_instance' défini dans 'atk-1.0.lib(atkmisc.c.obj)' est importé par 'libgtk-3.a(a11y_gtkaccessibility.c.obj)'
gtk\gtk-query-settings.exe : fatal error LNK1169: un ou plusieurs symboles définis à différentes reprises ont été rencontrés
[637/640] Linking target gtk/gtk-launch.exe
FAILED: gtk/gtk-launch.exe gtk/gtk-launch.pdb
"link" @gtk/gtk-launch.exe.rsp
libgdk-3.a(gdkmain-win32.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
gdk_pixbuf-2.0.lib(gdk-pixbuf-io.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
atk-1.0.lib(atkprivate.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
   Création de la bibliothèque gtk\gtk-launch.lib et de l'objet gtk\gtk-launch.exp
LINK : warning LNK4286: le symbole 'atk_misc_instance' défini dans 'atk-1.0.lib(atkmisc.c.obj)' est importé par 'libgtk-3.a(a11y_gtkaccessibility.c.obj)'
gtk\gtk-launch.exe : fatal error LNK1169: un ou plusieurs symboles définis à différentes reprises ont été rencontrés
[638/640] Linking target gtk/gtk-update-icon-cache.exe
s informations de débogage
[639/640] Linking target gtk/gtk-builder-tool.exe
FAILED: gtk/gtk-builder-tool.exe gtk/gtk-builder-tool.pdb
"link" @gtk/gtk-builder-tool.exe.rsp
libgdk-3.a(gdkmain-win32.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
gdk_pixbuf-2.0.lib(gdk-pixbuf-io.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
atk-1.0.lib(atkprivate.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
   Création de la bibliothèque gtk\gtk-builder-tool.lib et de l'objet gtk\gtk-builder-tool.exp
LINK : warning LNK4286: le symbole 'atk_misc_instance' défini dans 'atk-1.0.lib(atkmisc.c.obj)' est importé par 'libgtk-3.a(a11y_gtkaccessibility.c.obj)'
gtk\gtk-builder-tool.exe : fatal error LNK1169: un ou plusieurs symboles définis à différentes reprises ont été rencontrés
[640/640] Linking target gtk/gtk-query-immodules-3.0.exe
FAILED: gtk/gtk-query-immodules-3.0.exe gtk/gtk-query-immodules-3.0.pdb
"link" @gtk/gtk-query-immodules-3.0.exe.rsp
libgdk-3.a(gdkmain-win32.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
gdk_pixbuf-2.0.lib(gdk-pixbuf-io.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
atk-1.0.lib(atkprivate.c.obj) : error LNK2005: DllMain déjà défini(e) dans libgtk-3.a(gtkwin32.c.obj)
   Création de la bibliothèque gtk\gtk-query-immodules-3.0.lib et de l'objet gtk\gtk-query-immodules-3.0.exp
LINK : warning LNK4286: le symbole 'atk_misc_instance' défini dans 'atk-1.0.lib(atkmisc.c.obj)' est importé par 'libgtk-3.a(a11y_gtkaccessibility.c.obj)'
gtk\gtk-query-immodules-3.0.exe : fatal error LNK1169: un ou plusieurs symboles définis à différentes reprises ont été rencontrés
```
These are worked-around by using `-o gdk-pixbuf:shared=True -o atk:shared=True -o gtk:shared=True -o cairo:shared=True`

4. last failure happens during install:

```
Compiling GSettings schemas...
Traceback (most recent call last):
  File "C:\.conan\ebe967\1\source_subfolder\build-aux/meson/post-install.py", line 30, in <module>
    glib_compile_schemas = subprocess.check_output(['pkg-config',
  File "C:\Users\eric\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\eric\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\eric\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\eric\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
FAILED: install script 'C:\Users\eric\AppData\Local\Programs\Python\Python38\python.exe C:\.conan\ebe967\1\source_subfolder\build-aux/meson/post-install.py 3.0 3.0.0 C:/.conan/1b7833/1/bin C:/.conan/1b7833/1/lib C:/.conan/1b7833/1/res/share' exit code 1, stopped
```

**Comment by madebr** [comment]
I think this is a bug/(missing) configuration option of meson.
MSVC probably allows a maximum sized string buffer for parsing the arguments.
Googling for LNK1170 shows me that the command line files (.rsp files?) can be split in multiple lines.

**Comment by ericLemanissier** [comment]
Yes, also meson does not de-duplicate the arguments for visual studio, contrary to other compilers
