### ISSUE TITLE
[package] boost/1.75.0: build fails with MinGW on Windows

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan-center-index#4764]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.75.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **MinGW 8.0.0 & GCC 10.2.0**
  * Conan version: **conan 1.34.0**
  * Python version: **Python 3.9.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

`conan install boost/1.75.0 -b missing`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
boost/1.75.0: Calling build()
boost/1.75.0: WARN: Patching user-config.jam
boost/1.75.0: WARN:
using zlib : 1.2.11 : <include>"C:/Users/spaceim/.conan/data/zlib/1.2.11/_/_/package/c6817f477abe7e9a917b102f37dc1fd0c2d95f50/include" <search>"C:/Users/spaceim/.conan/data/zlib/1.2.11/_/_/package/c6817f477abe7e9a917b102f37dc1fd0c2d95f50/lib" <name>zlib ;
using bzip2 : 1.0.8 : <include>"C:/Users/spaceim/.conan/data/bzip2/1.0.8/_/_/package/0766393ee44f07d2755696e76f200af2c3907715/include" <search>"C:/Users/spaceim/.conan/data/bzip2/1.0.8/_/_/package/0766393ee44f07d2755696e76f200af2c3907715/lib" <name>bz2 ;
using "gcc" :  :  C:/mingw64/bin/g++.exe :
 ;
boost/1.75.0: WARN: b2.exe -q numa=on target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system --user-config=C:\Users\spaceim\.conan_short\a7b008\1\source_subfolder\tools\build\user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.iconv=on boost.locale.icu=off --disable-icu threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-context --with-contract --with-coroutine --with-date_time --with-exception --with-fiber --with-filesystem --with-graph --with-iostreams --with-json --with-locale --with-log --with-math --with-nowide --with-program_options --with-random --with-regex --with-serialization --with-stacktrace --with-system --with-test --with-thread --with-timer --with-type_erasure --with-wave toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=1 pch=on -sICONV_PATH=C:\Users\spaceim\.conan\data\libiconv\1.16\_\_\package\c6817f477abe7e9a917b102f37dc1fd0c2d95f50   install --prefix=C:\Users\spaceim\.conan_short\ac5def\1 -j8 --abbreviate-paths -d0 --debug-configuration --build-dir="C:\Users\spaceim\.conan_short\615b3d\1"
notice: found boost-build.jam at C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/boost-build.jam
notice: loading B2 from C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src
warning: mismatched versions of B2 engine and core
warning: B2 engine (b2.exe) is 4.2.0
warning: B2 core (at C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src) is 4.3-git
notice: Searching 'C:\Users\spaceim' 'C:\Users\spaceim' 'C:\Users\spaceim\.conan_short\a7b008\1\source_subfolder\tools/build/src' 'C:\Users\spaceim\.conan\data\b2\4.2.0\_\_\package\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\bin\b2_src\src\kernel' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/kernel' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/util' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/build' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/tools' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/contrib' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/.' for site-config configuration file 'site-config.jam'.
notice: Configuration file 'site-config.jam' not found in 'C:\Users\spaceim' 'C:\Users\spaceim' 'C:\Users\spaceim\.conan_short\a7b008\1\source_subfolder\tools/build/src' 'C:\Users\spaceim\.conan\data\b2\4.2.0\_\_\package\ca33edce272a279b24f87dc0d4cf5bbdcffbc187\bin\b2_src\src\kernel' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/kernel' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/util' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/build' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/tools' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/contrib' 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build/src/.'.
notice: Loading explicitly specified user configuration file:
    C:\Users\spaceim\.conan_short\a7b008\1\source_subfolder\tools\build\user-config.jam
notice: Searching 'C:\Users\spaceim\.conan_short\a7b008\1\source_subfolder\tools\build' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'C:/Users/spaceim/.conan_short/a7b008/1/source_subfolder/tools/build'.
notice: [zlib] Using pre-installed library
notice: [zlib] Condition
notice: [bzip2] Using pre-installed library
notice: [bzip2] Condition
notice: will use 'C:/mingw64/bin/g++.exe' for gcc, condition <toolset>gcc-10.2.0
notice: using gcc libraries :: <toolset>gcc-10.2.0 :: C:/mingw64/bin C:/mingw64/lib C:/mingw64/lib32 C:/mingw64/lib64
notice: using gcc archiver :: <toolset>gcc-10.2.0 :: C:/mingw64/x86_64-w64-mingw32/bin/ar.exe
notice: using gcc ranlib :: <toolset>gcc-10.2.0 :: C:/mingw64/x86_64-w64-mingw32/bin/ranlib.exe
notice: using rc compiler :: <toolset>gcc-10.2.0 :: C:\mingw64\bin\windres.exe
notice: [zlib] zlib is already configured
notice: [bzip2] bzip is already configured
notice: iostreams: not using lzma compression
notice: iostreams: not using zstd compression
notice: [python-cfg] Configuring python...
notice: [python-cfg] Checking interpreter command "python"...
notice: [python-cfg] running command 'DIR /-C /A:S "C:\Users\spaceim\AppData\Local\Programs\Python\Python39\python.exe" 2>&1'
notice: [python-cfg] running command 'python -c "from sys import *; print('version=%d.%d\nplatform=%s\nbase_prefix=%s\nbase_exec_prefix=%s\nexecutable=%s' % (version_info[0],version_info[1],platform,base_prefix,base_exec_prefix,executable))" 2>&1'
notice: [python-cfg] ...requested configuration matched!
notice: [python-cfg] Details of this Python configuration:
notice: [python-cfg]   interpreter command: "python"
notice: [python-cfg]   include path: "C:\Users\spaceim\AppData\Local\Programs\Python\Python39\Include"
notice: [python-cfg]   library path: "C:\Users\spaceim\AppData\Local\Programs\Python\Python39\libs"
notice: [python-cfg]   DLL search path: "C:\Users\spaceim\AppData\Local\Programs\Python\Python39"
notice: [python-cfg] Checking for NumPy...
notice: [python-cfg] running command 'python -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())"'
notice: [python-cfg] NumPy disabled. Reason:
notice: [python-cfg]   python -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())" aborted with
notice: [python-cfg]   Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Performing configuration checks

    - default address-model    : 64-bit
    - default architecture     : x86
    - compiler supports SSE2   : yes
    - compiler supports SSE4.1 : yes
    - has synchronization.lib  : yes
    - C++11 mutex              : yes
    - has BCrypt API           : no
    - is Windows CE            : no
    - has stat::st_mtim        : no
    - has stat::st_mtimensec   : no
    - has stat::st_mtimespec   : no
    - has stat::st_birthtim    : no
    - has stat::st_birthtimensec : no
    - has stat::st_birthtimespec : no
    - has statx                : no
    - has statx syscall        : no
    - cxx11_auto_declarations  : yes
    - cxx11_constexpr          : yes
    - cxx11_defaulted_functions : yes
    - cxx11_final              : yes
    - cxx11_hdr_mutex          : yes
    - cxx11_hdr_tuple          : yes
    - cxx11_lambdas            : yes
    - cxx11_noexcept           : yes
    - cxx11_nullptr            : yes
    - cxx11_rvalue_references  : yes
    - cxx11_template_aliases   : yes
    - cxx11_thread_local       : yes
    - cxx11_variadic_templates : yes
    - has_icu builds           : no
    - zlib                     : yes
    - bzip2                    : yes
    - cxx11_alignas            : yes
    - cxx11_decltype           : yes
    - iconv (libc)             : no
    - iconv (separate)         : yes
    - native atomic int32 supported : yes
    - has message compiler     : no
    - native syslog supported  : no
    - pthread supports robust mutexes : no
    - compiler supports SSSE3  : yes
    - compiler supports AVX2   : yes
    - gcc visibility           : yes
    - long double support      : yes
    - cxx11_static_assert      : yes
    - std::fstream is moveable and swappable : yes
    - Has Large File Support   : yes
    - libbacktrace builds      : no
    - addr2line builds         : no
    - WinDbg builds            : yes
    - WinDbgCached builds      : yes
    - BOOST_COMP_GNUC >= 4.3.0 : yes

Component configuration:

    - atomic                   : building
    - chrono                   : building
    - container                : building
    - context                  : building
    - contract                 : building
    - coroutine                : building
    - date_time                : building
    - exception                : building
    - fiber                    : building
    - filesystem               : building
    - graph                    : building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : building
    - json                     : building
    - locale                   : building
    - log                      : building
    - math                     : building
    - mpi                      : not building
    - nowide                   : building
    - program_options          : building
    - python                   : not building
    - random                   : building
    - regex                    : building
    - serialization            : building
    - stacktrace               : building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : building
    - type_erasure             : building
    - wave                     : building

...failed updating 1 target...
boost/1.75.0:
boost/1.75.0: ERROR: Package 'cae56bc250568c49625d181cf86f1bb1944be0a9' build failed
boost/1.75.0: WARN: Build folder C:\Users\spaceim\.conan_short\615b3d\1
ERROR: boost/1.75.0: Error in build() method, line 671
        self.run(full_command, run_environment=True)
        ConanException: Error 1 while executing b2.exe -q numa=on target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system --user-config=C:\Users\spaceim\.conan_short\a7b008\1\source_subfolder\tools\build\user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.iconv=on boost.locale.icu=off --disable-icu threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-context --with-contract --with-coroutine --with-date_time --with-exception --with-fiber --with-filesystem --with-graph --with-iostreams --with-json --with-locale --with-log --with-math --with-nowide --with-program_options --with-random --with-regex --with-serialization --with-stacktrace --with-system --with-test --with-thread --with-timer --with-type_erasure --with-wave toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=1 pch=on -sICONV_PATH=C:\Users\spaceim\.conan\data\libiconv\1.16\_\_\package\c6817f477abe7e9a917b102f37dc1fd0c2d95f50   install --prefix=C:\Users\spaceim\.conan_short\ac5def\1 -j8 --abbreviate-paths -d0 --debug-configuration --build-dir="C:\Users\spaceim\.conan_short\615b3d\1"
```

</details>

**Comment by dmn-star** [comment]
Probably numpy is simply not installed on your Windows.

>pip3 show numpy

**Comment by SpaceIm** [comment]
It's unrelated, I can build boost with Visual Studio without numpy installed.

**Comment by SpaceIm** [comment]
After lot of testing, I've isolated the component which fails, it's `fiber` (this component has several internal dependencies, but all of them succeed when I build boost with these components but without fiber).

```
conan create . boost/1.76.0@ -o boost:without_atomic=False -o boost:without_chrono=False -o boost:without_container=False -o boost:without_context=False -o boost:without_contract=True -o boost:without_coroutine=True -o boost:without_date_time=False -o boost:without_exception=False -o boost:without_fiber=False -o boost:without_filesystem=False -o boost:without_graph=True -o boost:without_iostreams=True -o boost:without_json=True -o boost:without_locale=True -o boost:without_log=True -o boost:without_math=True -o boost:without_nowide=True -o boost:without_program_options=True -o boost:without_random=True -o boost:without_regex=True -o boost:without_serialization=True -o boost:without_stacktrace=True -o boost:without_system=False -o boost:without_test=True -o boost:without_thread=False -o boost:without_timer=True -o boost:without_type_erasure=True -o boost:without_wave=True
```

<details><summary>Click to expand log</summary>

```
[HOOK - conan-center.py] pre_export(): [DEPRECATED GLOBAL CPPSTD (KB-H001)] OK
[HOOK - conan-center.py] pre_export(): [REFERENCE LOWERCASE (KB-H002)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE METADATA (KB-H003)] OK
[HOOK - conan-center.py] pre_export(): [HEADER_ONLY, NO COPY SOURCE (KB-H005)] OK
[HOOK - conan-center.py] pre_export(): [FPIC OPTION (KB-H006)] OK
[HOOK - conan-center.py] pre_export(): [VERSION RANGES (KB-H008)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] Total recipe size: 223.0068359375 KB
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] OK
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: ['patches/*']
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE FOLDER (KB-H024)] OK
[HOOK - conan-center.py] pre_export(): [META LINES (KB-H025)] OK
[HOOK - conan-center.py] pre_export(): [CONAN CENTER INDEX URL (KB-H027)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE MINIMUM VERSION (KB-H028)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - RUN ENVIRONMENT (KB-H029)] OK
[HOOK - conan-center.py] pre_export(): [SYSTEM REQUIREMENTS (KB-H032)] OK
[HOOK - conan-center.py] pre_export(): [CONANDATA.YML FORMAT (KB-H030)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - NO IMPORTS() (KB-H034)] OK
[HOOK - conan-center.py] pre_export(): [NO AUTHOR (KB-H037)] OK
[HOOK - conan-center.py] pre_export(): [NO TARGET NAME (KB-H040)] OK
[HOOK - conan-center.py] pre_export(): [NO FINAL ENDLINE (KB-H041)] OK
[HOOK - conan-center.py] pre_export(): [NO REQUIRES.ADD() (KB-H044)] OK
[HOOK - conan-center.py] pre_export(): [DELETE OPTIONS (KB-H045)] OK
[HOOK - conan-center.py] pre_export(): [NO ASCII CHARACTERS (KB-H047)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE VERBOSE MAKEFILE (KB-H046)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE VERSION REQUIRED (KB-H048)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE WINDOWS EXPORT ALL SYMBOLS (KB-H049)] OK
[HOOK - conan-center.py] pre_export(): [DEFAULT OPTIONS AS DICTIONARY (KB-H051)] OK
[HOOK - conan-center.py] pre_export(): [CONFIG.YML HAS NEW VERSION (KB-H052)] OK
[HOOK - conan-center.py] pre_export(): [PRIVATE IMPORTS (KB-H053)] OK
Exporting package recipe
boost/1.76.0 exports: File 'conandata.yml' found. Exporting it...
boost/1.76.0 exports: Copied 1 '.yml' file: conandata.yml
boost/1.76.0: Calling export()
boost/1.76.0 export() method: Copied 1 '.yml' file: dependencies-1.76.0.yml
boost/1.76.0 exports_sources: Copied 15 '.patch' files
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] Saving conandata.yml: {'sources': {'1.76.0': {'url': ['https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2', 'https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2'], 'sha256': 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41'}}}
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] New conandata.yml contents: sources:
  1.76.0:
    sha256: f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41
    url:
    - https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2
    - https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2

[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] OK
[HOOK - conan-center.py] post_export(): [DEFAULT SHARED OPTION VALUE (KB-H050)] OK
boost/1.76.0: The stored package has not changed
boost/1.76.0: Using the exported files summary hash as the recipe revision: cc8ecaea4183df5331e6c7f52151753c
boost/1.76.0: Exported revision: cc8ecaea4183df5331e6c7f52151753c
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=10
os=Windows
os_build=Windows
[options]
boost:shared=False
boost:without_atomic=False
boost:without_chrono=False
boost:without_container=False
boost:without_context=False
boost:without_contract=True
boost:without_coroutine=True
boost:without_date_time=False
boost:without_exception=False
boost:without_fiber=False
boost:without_filesystem=False
boost:without_graph=True
boost:without_iostreams=True
boost:without_json=True
boost:without_locale=True
boost:without_log=True
boost:without_math=True
boost:without_nowide=True
boost:without_program_options=True
boost:without_random=True
boost:without_regex=True
boost:without_serialization=True
boost:without_stacktrace=True
boost:without_system=False
boost:without_test=True
boost:without_thread=False
boost:without_timer=True
boost:without_type_erasure=True
boost:without_wave=True
[build_requires]
[env]
CC=D:/Programmes/mingw64/bin/gcc.exe
CXX=D:/Programmes/mingw64/bin/g++.exe
boost/1.76.0: Forced build from source
boost/1.76.0 (test package): Installing package
Requirements
    boost/1.76.0 from 'conan-center' - Cache
Packages
    boost/1.76.0:efb3591148ba8964f0a7380d75f5a8846e31d49f - Build
Build requirements
    b2/4.5.0 from 'conan-center' - Cache
Build requirements packages
    b2/4.5.0:ca33edce272a279b24f87dc0d4cf5bbdcffbc187 - Cache

Installing (downloading, building) binaries...
b2/4.5.0: Already installed!
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
boost/1.76.0: Applying build-requirement: b2/4.5.0
boost/1.76.0: Building your package in C:\Users\spaceim\.conan_short\bde752\1
boost/1.76.0: Generator txt created conanbuildinfo.txt
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
boost/1.76.0: Calling build()
WARN: replace_in_file didn't find pattern '/* thread_local */' in 'C:\Users\spaceim\.conan_short\3309d4\1\source_subfolder\boost\stacktrace\detail\libbacktrace_impls.hpp' file.
WARN: replace_in_file didn't find pattern '/* static __thread */' in 'C:\Users\spaceim\.conan_short\3309d4\1\source_subfolder\boost\stacktrace\detail\libbacktrace_impls.hpp' file.
boost/1.76.0: WARN: Patching user-config.jam
boost/1.76.0: WARN:
using "gcc" :  :  D:/Programmes/mingw64/bin/g++.exe :
 ;
boost/1.76.0: WARN: b2.exe -q numa=on target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system --user-config=C:\Users\spaceim\.conan_short\3309d4\1\source_subfolder\tools\build\user-config.jam -sNO_ZLIB=1 -sNO_BZIP2=1 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.iconv=off boost.locale.icu=off --disable-icu --disable-iconv threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-context --with-date_time --with-exception --with-fiber --with-filesystem --with-system --with-thread toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=1 pch=on  cxxflags="-fPIC" install --prefix=C:\Users\spaceim\.conan_short\17c5eb\1 -j8 --abbreviate-paths -d0 --debug-configuration --build-dir="C:\Users\spaceim\.conan_short\bde752\1"
notice: found boost-build.jam at C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/boost-build.jam
notice: loading B2 from C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/bootstrap.jam
warning: mismatched versions of B2 engine and core
warning: B2 engine (b2.exe) is 4.5.0
warning: B2 core (at C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src) is 4.4-git
notice: Searching 'C:\Users\spaceim' 'C:\Users\spaceim' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/kernel' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/util' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/build' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/tools' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/contrib' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/.' for site-config configuration file 'site-config.jam'.
notice: Configuration file 'site-config.jam' not found in 'C:\Users\spaceim' 'C:\Users\spaceim' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/kernel' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/util' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/build' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/tools' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/contrib' 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build/src/.'.
notice: Loading explicitly specified user configuration file:
    C:\Users\spaceim\.conan_short\3309d4\1\source_subfolder\tools\build\user-config.jam
notice: Searching 'C:\Users\spaceim\.conan_short\3309d4\1\source_subfolder\tools\build' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'C:/Users/spaceim/.conan_short/3309d4/1/source_subfolder/tools/build'.
notice: will use 'D:/Programmes/mingw64/bin/g++.exe' for gcc, condition <toolset>gcc-10.3.0
notice: using gcc libraries :: <toolset>gcc-10.3.0 :: D:/Programmes/mingw64/bin D:/Programmes/mingw64/lib D:/Programmes/mingw64/lib32 D:/Programmes/mingw64/lib64
notice: using gcc archiver :: <toolset>gcc-10.3.0 :: d:/programmes/mingw64/x86_64-w64-mingw32/bin/ar.exe
notice: using gcc ranlib :: <toolset>gcc-10.3.0 :: d:/programmes/mingw64/x86_64-w64-mingw32/bin/ranlib.exe
notice: using rc compiler :: <toolset>gcc-10.3.0 :: D:\Programmes\mingw64\bin\windres.exe
notice: iostreams: not using zlib compression
notice: iostreams: not using bzip compression
notice: iostreams: not using lzma compression
notice: iostreams: not using zstd compression
notice: [python-cfg] Configuring python...
notice: [python-cfg] Checking interpreter command "python"...
notice: [python-cfg] running command 'DIR /-C /A:S "C:\Users\spaceim\AppData\Local\Programs\Python\Python39\python.exe" 2>&1'
notice: [python-cfg] running command 'python -c "from sys import *; print('version=%d.%d\nplatform=%s\nprefix=%s\nexec_prefix=%s\nexecutable=%s' % (version_info[0],version_info[1],platform,prefix,exec_prefix,executable))" 2>&1'
notice: [python-cfg] ...requested configuration matched!
notice: [python-cfg] Details of this Python configuration:
notice: [python-cfg]   interpreter command: "python"
notice: [python-cfg]   include path: "C:\Users\spaceim\AppData\Local\Programs\Python\Python39\Include"
notice: [python-cfg]   library path: "C:\Users\spaceim\AppData\Local\Programs\Python\Python39\libs"
notice: [python-cfg]   DLL search path: "C:\Users\spaceim\AppData\Local\Programs\Python\Python39"
notice: [python-cfg] Checking for NumPy...
notice: [python-cfg] running command 'python -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())"'
notice: [python-cfg] NumPy disabled. Reason:
notice: [python-cfg]   python -c "import sys; sys.stderr = sys.stdout; import numpy; print(numpy.get_include())" aborted with
notice: [python-cfg]   Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Performing configuration checks

    - default address-model    : 64-bit [1]
    - default architecture     : x86 [1]
    - compiler supports SSE2   : yes [2]
    - compiler supports SSE4.1 : yes [2]
    - has synchronization.lib  : yes [2]
    - C++11 mutex              : yes [2]
    - has BCrypt API           : no [2]
    - is Windows CE            : no [2]
    - has stat::st_mtim        : no [2]
    - has stat::st_mtimensec   : no [2]
    - has stat::st_mtimespec   : no [2]
    - has stat::st_birthtim    : no [2]
    - has stat::st_birthtimensec : no [2]
    - has stat::st_birthtimespec : no [2]
    - has statx                : no [2]
    - has statx syscall        : no [2]
    - cxx11_auto_declarations  : yes [2]
    - cxx11_constexpr          : yes [2]
    - cxx11_defaulted_functions : yes [2]
    - cxx11_final              : yes [2]
    - cxx11_hdr_mutex          : yes [2]
    - cxx11_hdr_tuple          : yes [2]
    - cxx11_lambdas            : yes [2]
    - cxx11_noexcept           : yes [2]
    - cxx11_nullptr            : yes [2]
    - cxx11_rvalue_references  : yes [2]
    - cxx11_template_aliases   : yes [2]
    - cxx11_thread_local       : yes [2]
    - cxx11_variadic_templates : yes [2]

[1] gcc-10.3.
[2] gcc-10.3./rls/bst.l-off/bst.l-off/lnk-sttc/nm-on/pythn-3.9/thrdp-wn32/thrd-mlt/vsblt-hdn

Component configuration:

    - atomic                   : building
    - chrono                   : building
    - container                : building
    - context                  : building
    - contract                 : not building
    - coroutine                : not building
    - date_time                : building
    - exception                : building
    - fiber                    : building
    - filesystem               : building
    - graph                    : not building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : not building
    - json                     : not building
    - locale                   : not building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - nowide                   : not building
    - program_options          : not building
    - python                   : not building
    - random                   : not building
    - regex                    : not building
    - serialization            : not building
    - stacktrace               : not building
    - system                   : building
    - test                     : not building
    - thread                   : building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building

...failed updating 1 target...
boost/1.76.0:
boost/1.76.0: ERROR: Package 'efb3591148ba8964f0a7380d75f5a8846e31d49f' build failed
boost/1.76.0: WARN: Build folder C:\Users\spaceim\.conan_short\bde752\1
ERROR: boost/1.76.0: Error in build() method, line 773
        self.run(full_command, run_environment=True)
        ConanException: Error 1 while executing b2.exe -q numa=on target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system --user-config=C:\Users\spaceim\.conan_short\3309d4\1\source_subfolder\tools\build\user-config.jam -sNO_ZLIB=1 -sNO_BZIP2=1 -sNO_LZMA=1 -sNO_ZSTD=1 boost.locale.iconv=off boost.locale.icu=off --disable-icu --disable-iconv threading=multi visibility=hidden link=static variant=release --with-atomic --with-chrono --with-container --with-context --with-date_time --with-exception --with-fiber --with-filesystem --with-system --with-thread toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=1 pch=on  cxxflags="-fPIC" install --prefix=C:\Users\spaceim\.conan_short\17c5eb\1 -j8 --abbreviate-paths -d0 --debug-configuration --build-dir="C:\Users\spaceim\.conan_short\bde752\1"
```

</details>

**Comment by SpaceIm** [comment]
I see that boost recipe doesn't set `threadapi` flag for b2. Is it not an issue for MinGW with posix thread?

**Comment by wissem01chiha** [comment]
I faced a very similar error on windows 11, gcc 11.2.0, Conan 2.1.0, and CMake 3.29, when trying to install boost library, which depends on other libs causing the error, I found a Conan bug with MinGw.
I solve the problem by disabling the build for the libs fiber and stacktrace.  
to do add these lines at the end of  conanfile.txt file :      
   
    .....
    .....
    [options]  
    boost/1.70.0:without_fiber=True  
    boost/1.70.0:without_stacktrace=True

**Comment by alezhu** [comment]
> I faced a similar error on windows 11, gcc 11.2.0, Conan 2.1.0, and CMake 3.29, when trying to install boost library, which depends on other libs causing the error, I found a Conan bug with MinGw. I solve the problem by disabling the build for the libs fiber and stacktrace. to do add these lines at the end of conanfile.txt file :
> 
> ```
> .....
> .....
> [options]  
> boost/1.70.0:without_fiber=True  
> boost/1.70.0:without_stacktrace=True    
> ```

Also if you use the conanfile.py file, you can add **default_options** property to the class in it:

```python
class ConanApplication(ConanFile):
    default_options  = {
        "boost*:without_fiber":True,
        "boost*:without_stacktrace":True,
    }
```
