### ISSUE TITLE
[gtest] NameError: name 'glob' is not defined

### ISSUE THREAD

**Issue by jeremy-coulon** [conan-io/conan-center-index#5158]
I can't build gtest/1.8.1 from source.
```
Traceback (most recent call last):
  File "/data/Jenkins-Slave/workspace/party_conan-center-index_develop@2/.pyenv-opt-rh-rh-python36-root-usr-bin-python3/lib64/python3.6/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/data/Jenkins-Slave/workspace/party_conan-center-index_develop@2/.pyenv-opt-rh-rh-python36-root-usr-bin-python3/lib64/python3.6/site-packages/conans/client/source.py", line 149, in _run_source
    conanfile.source()
  File "/data/Jenkins-Slave/workspace/party_conan-center-index_develop@2/.conan/data/gtest/1.8.1/exalead/testing/export/conanfile.py", line 80, in source
    extracted_dir = glob.glob("googletest-*/")[0]
NameError: name 'glob' is not defined
```

conan 1.35.0
python 3.6

`import glob` is missing in conanfile?

**Comment by jeremy-coulon** [comment]
Oops!
My mistake. My last merge made `import glob` disappear.
