### ISSUE TITLE
[package] openssl/1.1.1k: ./Configure fails due to missing perl packages (FindBin + File-Compare)

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#5386]
When building openssl/1.1.1k, configuration fails due to missing perl packages.
The missing perl packages are:
- `FindBin`,
- `File-Compare`

On my Fedora distro, I was able to install these by executing:
```sh
sudo dnf install perl-FindBin perl-File-Compare`
```

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **openssl/1.1.1k**
  * Operating System+version: **Fedora Linux 24**
  * Compiler+version: **GCC 11**
  * Conan version: **conan 1.34.0**
  * Python version: **Python 3.9.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration for profile default:

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
$ conan install openssl/1.1.1k@ --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Installing package: openssl/1.1.1k
Requirements
    openssl/1.1.1k from 'conan-center' - Cache
Packages
    openssl/1.1.1k:dfbe50feef7f3c6223a476cd5aeadb687084a646 - Build

Installing (downloading, building) binaries...
openssl/1.1.1k: WARN: Build folder is dirty, removing it: /home/maarten/.conan/data/openssl/1.1.1k/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646
openssl/1.1.1k: Copying sources to build folder
openssl/1.1.1k: Building your package in /home/maarten/.conan/data/openssl/1.1.1k/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646
openssl/1.1.1k: Generator txt created conanbuildinfo.txt
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK. 'fPIC' option found and apparently well managed
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
openssl/1.1.1k: Calling build()
openssl/1.1.1k: using target: conan-Release-Linux-x86_64-gcc-11 -> linux-x86_64
openssl/1.1.1k: my %targets = (
    "conan-Release-Linux-x86_64-gcc-11" => {
        inherit_from => [ "linux-x86_64" ],
        cflags => add("-m64 -O3 -s -fPIC"),
        cxxflags => add("-m64 -O3 -s -fPIC"),
        defines => add("NDEBUG"),
        includes => add(),
        lflags => add("-m64"),
        
        
        
        
        
        
        
        
    },
);

openssl/1.1.1k: ['"conan-Release-Linux-x86_64-gcc-11"', 'no-shared', '--prefix="/home/maarten/.conan/data/openssl/1.1.1k/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646"', '--openssldir="/etc/ssl"', 'no-unit-test', 'threads', 'PERL=perl', 'no-tests', '--release', '-fPIC']

----Running------
> perl ./Configure "conan-Release-Linux-x86_64-gcc-11" no-shared --prefix="/home/maarten/.conan/data/openssl/1.1.1k/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646" --openssldir="/etc/ssl" no-unit-test threads PERL=perl no-tests --release -fPIC
-----------------
Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /home/maarten/perl5/lib/perl5/x86_64-linux-thread-multi /home/maarten/perl5/lib/perl5 /home/maarten/perl5/lib/perl5/x86_64-linux-thread-multi /home/maarten/perl5/lib/perl5 /usr/local/lib64/perl5/5.32 /usr/local/share/perl5/5.32 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ./Configure line 15.
BEGIN failed--compilation aborted at ./Configure line 15.
openssl/1.1.1k: 
openssl/1.1.1k: ERROR: Package 'dfbe50feef7f3c6223a476cd5aeadb687084a646' build failed
openssl/1.1.1k: WARN: Build folder /home/maarten/.conan/data/openssl/1.1.1k/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646
ERROR: Traceback (most recent call last):
  File "/home/maarten/.local/lib/python3.9/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/home/maarten/.local/lib/python3.9/site-packages/conans/client/conanfile/build.py", line 16, in run_build_method
    conanfile.build()
  File "/home/maarten/.conan/data/openssl/1.1.1k/_/_/export/conanfile.py", line 702, in build
    self._make()
  File "/home/maarten/.conan/data/openssl/1.1.1k/_/_/export/conanfile.py", line 638, in _make
    self.run('{perl} ./Configure {args}'.format(perl=self._perl, args=args), win_bash=self._win_bash)
  File "/home/maarten/.local/lib/python3.9/site-packages/conans/model/conan_file.py", line 371, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 2 while executing perl ./Configure "conan-Release-Linux-x86_64-gcc-11" no-shared --prefix="/home/maarten/.conan/data/openssl/1.1.1k/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646" --openssldir="/etc/ssl" no-unit-test threads PERL=perl no-tests --release -fPIC
```

</details>

**Comment by perseoGI** [comment]
Hi there!
I'm closing this very old issue as this problem has been solved in the past.
Also, `openssl/1.1.1k` version is no longer supported.

Here are compilation (successful) logs:
```
$ conan create recipes/openssl/1.x.x --version 1.1.1w -b=missing

[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=15
os=Macos

...
openssl/1.1.1w (test package): Running CMake.build()
openssl/1.1.1w (test package): RUN: cmake --build "/Users/perseo/sources/conan-center-index/recipes/openssl/1.x.x/test_package/build/apple-clang-15-armv8-gnu17-release" -- -j14
[ 50%] Building C object CMakeFiles/test_package.dir/digest.c.o
[100%] Linking C executable test_package
[100%] Built target test_package
```

If for some reason, the problem remains, do not hesitate on open a new issue!
Happy coding 🐸
