### ISSUE TITLE
[package] <libcurl>/<7.78.0>: libtool error when building with Address Sanitizer

### ISSUE THREAD

**Issue by klimkin** [conan-io/conan-center-index#6671]
Build with Address Sanitizer fails in libcurl autotools configure phase. The build is successful if forcing the recipe to use CMake.
Note, the build is successful on other autotools packages - tested with `m4/1.4.18`. 

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **libcurl/7.78.0**
  * Operating System+version: **Debian GNU/Linux 10 (buster)**
  * Compiler+version: **GCC 9**
  * Conan version: **conan 1.40.0**
  * Python version: **Python 3.9.2**

### Conan profile
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.sanitizer=Address
compiler.version=9
os=Linux
os.distro=Debian
os_build=Linux
[options]
libcurl:shared=True
zlib:shared=True
[build_requires]
[env]
AR=gcc-ar-9
AS=as
ASAN_OPTIONS=detect_leaks=0 verify_asan_link_order=0
CC=gcc-9
CFLAGS=-fno-omit-frame-pointer -fsanitize=address
CXX=g++-9
CXXFLAGS=-fno-omit-frame-pointer -fsanitize=address
LDFLAGS=-fsanitize=address
RANLIB=gcc-ranlib-9
```

### Steps to reproduce (Include if Applicable)
~~~
conan install libcurl/7.78.0@ -pr profile.txt -o zlib:shared=True -o libcurl:shared=True --build=missing
~~~

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
checking for gcc... gcc-9
checking whether the C compiler works... no
configure: error: in `.conan/data/libcurl/7.78.0/_/_/build/606c8fdf4357630f466b91f5127938b5b12644a3/source_subfolder':
configure: error: C compiler cannot create executables
See `config.log' for more details
libcurl/7.78.0@:
libcurl/7.78.0@: ERROR: Package '606c8fdf4357630f466b91f5127938b5b12644a3' build failed
```

config.log:
```
configure:4312: $? = 1
configure:4331: checking whether the C compiler works
configure:4353: gcc-9 -m64 -O3 -s -fPIC -fno-omit-frame-pointer -fsanitize=address -I.conan/data/libtool/2.4.6/_/_/package/4a3e68bbbf37d4a3fd77ceb0b3d88d45a7f5791b/include -I.conan/data/pkgconf/1.7.4/_/_/package/77f21410050e0f5d6a7ad7fa0b8bb32b0db3dab9/include -I.conan/data/pkgconf/1.7.4/_/_/package/77f21410050e0f5d6a7ad7fa0b8bb32b0db3dab9/include/pkgconf -I.conan/data/openssl/1.1.1k/_/_/package/77f21410050e0f5d6a7ad7fa0b8bb32b0db3dab9/include -I.conan/data/zlib/1.2.11/_/_/package/eabe4ee3e9515ee787a8b7d41c0c2d20c28ff846/include -DPKGCONFIG_IS_STATIC -DNDEBUG -m64 -L.conan/data/libtool/2.4.6/_/_/package/4a3e68bbbf37d4a3fd77ceb0b3d88d45a7f5791b/lib -L.conan/data/pkgconf/1.7.4/_/_/package/77f21410050e0f5d6a7ad7fa0b8bb32b0db3dab9/lib -L.conan/data/openssl/1.1.1k/_/_/package/77f21410050e0f5d6a7ad7fa0b8bb32b0db3dab9/lib -L.conan/data/zlib/1.2.11/_/_/package/eabe4ee3e9515ee787a8b7d41c0c2d20c28ff846/lib -fsanitize=address conftest.c -lltdl -lpkgconf -lssl -lcrypto -lz -ldl -lpthread -lrt >&5
==103495==AddressSanitizer CHECK failed: ../../../../src/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:212 "((get_tls)) != ((0))" (0x0, 0x0)
    #0 0x7f706e4f57ed in AsanCheckFailed ../../../../src/libsanitizer/asan/asan_rtl.cc:72
    #1 0x7f706e51196a in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) ../../../../src/libsanitizer/sanitizer_common/sanitizer_termination.cc:77
    #2 0x7f706e505f84 in CallGetTls<__sanitizer::(anonymous namespace)::GetTlsStaticInfoCall> ../../../../src/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:212
    #3 0x7f706e505f84 in __sanitizer::InitTlsSize() ../../../../src/libsanitizer/sanitizer_common/sanitizer_linux_libcdep.cc:248
    #4 0x7f706e4f780b in AsanInitInternal ../../../../src/libsanitizer/asan/asan_rtl.cc:467
    #5 0x7f706e4f780b in AsanInitInternal ../../../../src/libsanitizer/asan/asan_rtl.cc:384
    #6 0x7f706f6b1fe1 in call_init elf/dl-init.c:72
    #7 0x7f706f6b20e8 in call_init elf/dl-init.c:30
    #8 0x7f706f6b20e8 in _dl_init elf/dl-init.c:119
    #9 0x7f706f6a30c9  (/lib64/ld-linux-x86-64.so.2+0x10c9)

configure:4357: $? = 1
configure:4395: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "curl"
| #define PACKAGE_TARNAME "curl"
| #define PACKAGE_VERSION "-"
| #define PACKAGE_STRING "curl -"
| #define PACKAGE_BUGREPORT "a suitable curl mailing list: https://curl.se/mail/"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
|
| int main (void)
| {
|
|  ;
|  return 0;
| }
configure:4400: error: in `.conan/data/libcurl/7.78.0/adklimki/test/build/606c8fdf4357630f466b91f5127938b5b12644a3/source_subfolder':
configure:4402: error: C compiler cannot create executables
```
</details>

**Comment by SpaceIm** [comment]
Please share the content of config.log

**Comment by klimkin** [comment]
@SpaceIm Added config.log to the Logs section in the description.

**Comment by perseoGI** [comment]
Hi there!
I'm closing this issue in favor of this one https://github.com/conan-io/conan-center-index/issues/23933 which seems to be a duplication. I'll put it in our look intos to discuss this problem (if it still a problem nowadays)

Thank you and happy coding 😄
