### ISSUE TITLE
[package] autoconf/all: cannot build in 2 profile context (where build == host)

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#6673]
Use the following `default64` profile:
```
[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]
CC=gcc
CXX=g++
AS=gcc
ASM=gcc
CFLAGS=-m64
CXXFLAGS=-m64
ASFLAGS=-m64
ASMFLAGS=-m64
LDFLAGS=-m64
```

Make sure that `m4` is NOT installed on your machine
==> Run any of the following
```
sudo apt-get remove m4
sudo dnf remove m4
sudo pacman -R m4
```

`which m4` should fail now with the following message:
```
/usr/bin/which: no m4 in (/home/maarten/perl5/bin:/home/maarten/.cargo/bin:/home/maarten/.local/bin:/home/maarten/local/bin:/home/maarten/.cargo/bin:/home/maarten/perl5/bin:/home/maarten/.cargo/bin:/home/maarten/.local/bin:/home/maarten/local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/opt/Xilinx/14.7/ISE_DS/ISE/bin/lin64:/home/maarten/.local/bin:/home/maarten/bin:/opt/Xilinx/14.7/ISE_DS/ISE/bin/lin64)
```

Then run 
```
conan create recipes/autoconf/all autoconf/2.71@ -pr:h default64 -pr:b default64
```

This fails on my machine with the following error:
```
checking for GNU M4 that supports accurate traces... configure: error: no acceptable m4 could be found in $PATH.
GNU M4 1.4.6 or later is required; 1.4.16 or newer is recommended.
GNU M4 1.4.15 uses a buggy replacement strstr on some systems.
Glibc 2.9 - 2.12 and GNU M4 1.4.11 - 1.4.15 have another strstr bug.
```

Adddng `m4/1.4.18` as a build requirement to `autoconf` is not a fix.

This issue came up in https://github.com/conan-io/conan/issues/7565

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **autoconf/all**
  * Operating System+version: **Fedora Linux 34**
  * Compiler+version: **GCC 11**
  * Conan version: **conan 1.38.0**
  * Python version: **Python 3.9.6**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]
CC=gcc
CXX=g++
AS=gcc
ASM=gcc
CFLAGS=-m64
CXXFLAGS=-m64
ASFLAGS=-m64
ASMFLAGS=-m64
LDFLAGS=-m64
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
[HOOK - conan-center.py] pre_export(): [DEPRECATED GLOBAL CPPSTD (KB-H001)] OK
[HOOK - conan-center.py] pre_export(): [REFERENCE LOWERCASE (KB-H002)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE METADATA (KB-H003)] OK
[HOOK - conan-center.py] pre_export(): [HEADER_ONLY, NO COPY SOURCE (KB-H005)] OK
[HOOK - conan-center.py] pre_export(): [FPIC OPTION (KB-H006)] OK
[HOOK - conan-center.py] pre_export(): [VERSION RANGES (KB-H008)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] Total recipe size: 27.609375 KB
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] OK
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: patches/**
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE FOLDER (KB-H024)] OK
[HOOK - conan-center.py] pre_export(): [META LINES (KB-H025)] OK
[HOOK - conan-center.py] pre_export(): [CONAN CENTER INDEX URL (KB-H027)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE MINIMUM VERSION (KB-H028)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - RUN ENVIRONMENT (KB-H029)] OK
[HOOK - conan-center.py] pre_export(): [SYSTEM REQUIREMENTS (KB-H032)] OK
[HOOK - conan-center.py] pre_export(): [CONANDATA.YML FORMAT (KB-H030)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - NO IMPORTS() (KB-H034)] OK
[HOOK - conan-center.py] pre_export(): [NO AUTHOR (KB-H037)] OK
[HOOK - conan-center.py] pre_export(): [NO TARGET NAME (KB-H040)] OK
[HOOK - conan-center.py] pre_export(): [NO FINAL ENDLINE (KB-H041)] OK
[HOOK - conan-center.py] pre_export(): [NO REQUIRES.ADD() (KB-H044)] OK
[HOOK - conan-center.py] pre_export(): [DELETE OPTIONS (KB-H045)] OK
[HOOK - conan-center.py] pre_export(): [NO ASCII CHARACTERS (KB-H047)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE VERBOSE MAKEFILE (KB-H046)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE VERSION REQUIRED (KB-H048)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE WINDOWS EXPORT ALL SYMBOLS (KB-H049)] OK
[HOOK - conan-center.py] pre_export(): [DEFAULT OPTIONS AS DICTIONARY (KB-H051)] OK
[HOOK - conan-center.py] pre_export(): [CONFIG.YML HAS NEW VERSION (KB-H052)] OK
[HOOK - conan-center.py] pre_export(): [PRIVATE IMPORTS (KB-H053)] OK
[HOOK - conan-center.py] pre_export(): [SINGLE REQUIRES (KB-H055)] OK
Exporting package recipe
autoconf/2.71 exports: File 'conandata.yml' found. Exporting it...
autoconf/2.71 exports: Copied 1 '.yml' file: conandata.yml
autoconf/2.71 exports_sources: Copied 10 '.patch' files
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] Saving conandata.yml: {'sources': {'2.71': {'sha256': '431075ad0bf529ef13cb41e9042c542381103e80015686222b8a9d4abef42a1c', 'url': 'https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.gz'}}, 'patches': {'2.71': [{'patch_file': 'patches/2.71-0001-autom4te-relocatable.patch', 'base_path': 'source_subfolder'}, {'patch_file': 'patches/2.71-0002-no-perl-path-in-shebang.patch', 'base_path': 'source_subfolder'}, {'patch_file': 'patches/2.71-0003-uppercase-autom4te_perllibdir.patch', 'base_path': 'source_subfolder'}, {'patch_file': 'patches/2.71-0004-no-embedded-m4-paths.patch', 'base_path': 'source_subfolder'}, {'patch_file': 'patches/2.71-0005-disable-man-regeneration.patch', 'base_path': 'source_subfolder'}, {'patch_file': 'patches/2.71-0006-autoconf-no-embedded-trailer_m4-path.patch', 'base_path': 'source_subfolder'}]}}
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] New conandata.yml contents: patches:
  '2.71':
  - base_path: source_subfolder
    patch_file: patches/2.71-0001-autom4te-relocatable.patch
  - base_path: source_subfolder
    patch_file: patches/2.71-0002-no-perl-path-in-shebang.patch
  - base_path: source_subfolder
    patch_file: patches/2.71-0003-uppercase-autom4te_perllibdir.patch
  - base_path: source_subfolder
    patch_file: patches/2.71-0004-no-embedded-m4-paths.patch
  - base_path: source_subfolder
    patch_file: patches/2.71-0005-disable-man-regeneration.patch
  - base_path: source_subfolder
    patch_file: patches/2.71-0006-autoconf-no-embedded-trailer_m4-path.patch
sources:
  '2.71':
    sha256: 431075ad0bf529ef13cb41e9042c542381103e80015686222b8a9d4abef42a1c
    url: https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.gz

[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] OK
[HOOK - conan-center.py] post_export(): [DEFAULT SHARED OPTION VALUE (KB-H050)] OK
[HOOK - conan-center.py] post_export(): [LICENSE PUBLIC DOMAIN (KB-H056)] OK
autoconf/2.71: The stored package has not changed
autoconf/2.71: Exported revision: f4de72d70c4ea70ab3e7aab5be4effa6
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
[build_requires]
[env]
AS=gcc
ASFLAGS=-m64
ASM=gcc
ASMFLAGS=-m64
CC=gcc
CFLAGS=-m64
CXX=g++
CXXFLAGS=-m64
LDFLAGS=-m64
Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux
[options]
[build_requires]
[env]
AS=gcc
ASFLAGS=-m64
ASM=gcc
ASMFLAGS=-m64
CC=gcc
CFLAGS=-m64
CXX=g++
CXXFLAGS=-m64
LDFLAGS=-m64
autoconf/2.71: Forced build from source
autoconf/2.71 (test package): Installing package
Requirements
Packages
Build requirements
    autoconf/2.71 from 'conan-center' - Cache
    m4/1.4.18 from 'conan-center' - Cache
Build requirements packages
    autoconf/2.71:cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31 - Build
    m4/1.4.18:24647d9fe8ec489125dfbae4b3ebefaf7581674c - Cache

Installing (downloading, building) binaries...
m4/1.4.18: Already installed!
m4/1.4.18: Appending PATH environment variable: /home/maarten/.conan/data/m4/1.4.18/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin
m4/1.4.18: Setting M4 environment variable: /home/maarten/.conan/data/m4/1.4.18/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/bin/m4
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
m4/1.4.18: WARN: Lib folder doesn't exist, can't collect libraries: /home/maarten/.conan/data/m4/1.4.18/_/_/package/24647d9fe8ec489125dfbae4b3ebefaf7581674c/lib
[HOOK - conan-center.py] post_package_info(): [LIBRARY DOES NOT EXIST (KB-H054)] OK
autoconf/2.71: WARN: Build folder is dirty, removing it: /home/maarten/.conan/data/autoconf/2.71/_/_/build/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31
autoconf/2.71: Copying sources to build folder
autoconf/2.71: Building your package in /home/maarten/.conan/data/autoconf/2.71/_/_/build/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31
autoconf/2.71: Generator txt created conanbuildinfo.txt
autoconf/2.71: Aggregating env generators
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
autoconf/2.71: Calling build()
autoconf/2.71: Calling:
 > /home/maarten/.conan/data/autoconf/2.71/_/_/build/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/source_subfolder/configure '--datarootdir=/home/maarten/.conan/data/autoconf/2.71/_/_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/bin/share' '--prefix=/home/maarten/.conan/data/autoconf/2.71/_/_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' --target=x86_64-linux-gnu

----Running------
> /home/maarten/.conan/data/autoconf/2.71/_/_/build/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/source_subfolder/configure '--datarootdir=/home/maarten/.conan/data/autoconf/2.71/_/_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/bin/share' '--prefix=/home/maarten/.conan/data/autoconf/2.71/_/_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' --target=x86_64-linux-gnu
-----------------
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
configure: autobuild project... GNU Autoconf
configure: autobuild revision... 2.71
configure: autobuild hostname... fedora
configure: autobuild timestamp... 20210804T010012Z
checking for a shell whose -n mode is known to work... /bin/sh
checking for characters that cannot appear in file names... none
checking whether directories can have trailing spaces... yes
checking for expr... /usr/bin/expr
checking for GNU M4 that supports accurate traces... configure: error: no acceptable m4 could be found in $PATH.
GNU M4 1.4.6 or later is required; 1.4.16 or newer is recommended.
GNU M4 1.4.15 uses a buggy replacement strstr on some systems.
Glibc 2.9 - 2.12 and GNU M4 1.4.11 - 1.4.15 have another strstr bug.
autoconf/2.71: 
autoconf/2.71: ERROR: Package 'cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31' build failed
autoconf/2.71: WARN: Build folder /home/maarten/.conan/data/autoconf/2.71/_/_/build/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31
ERROR: Traceback (most recent call last):
  File "/home/maarten/.local/lib/python3.9/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter
    yield
  File "/home/maarten/.local/lib/python3.9/site-packages/conans/client/conanfile/build.py", line 16, in run_build_method
    conanfile.build()
  File "/home/maarten/.conan/data/autoconf/2.71/_/_/export/conanfile.py", line 76, in build
    autotools = self._configure_autotools()
  File "/home/maarten/.conan/data/autoconf/2.71/_/_/export/conanfile.py", line 67, in _configure_autotools
    self._autotools.configure(args=conf_args, configure_dir=self._source_subfolder)
  File "/home/maarten/.local/lib/python3.9/site-packages/conans/client/build/autotools_environment.py", line 205, in configure
    self._conanfile.run(command, win_bash=self._win_bash, subsystem=self.subsystem)
  File "/home/maarten/.local/lib/python3.9/site-packages/conans/model/conan_file.py", line 426, in run
    raise ConanException("Error %d while executing %s" % (retcode, command))
conans.errors.ConanException: Error 1 while executing /home/maarten/.conan/data/autoconf/2.71/_/_/build/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/source_subfolder/configure '--datarootdir=/home/maarten/.conan/data/autoconf/2.71/_/_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/bin/share' '--prefix=/home/maarten/.conan/data/autoconf/2.71/_/_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31' '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libexecdir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' --target=x86_64-linux-gnu


```

</details>

**Comment by madebr** [comment]
I've created [a branch that uses `conan.tools.gnu.Autotools` on my fork](https://github.com/madebr/conan-center-index/tree/autoconf_modernize%2Buse_generate) but it suffers from the same problem.
