### ISSUE TITLE
[boost] boost/1.77.0: ConanException Error 1 while execuing b2

### ISSUE THREAD

**Issue by Grafnus** [conan-io/conan-center-index#8161]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.77.0**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0**
  * Conan version: **conan 1.40.2**
  * Python version: **Python 3.8.10**

### Conan profile
```
+---------------------------+
| Profile                   |
|---------------------------|
| include(default)          |
|                           |
| [settings]                |
| arch=x86_64               |
| build_type=Debug          |
| compiler.libcxx=libstdc++ |
| compiler.version=9        |
| [options]                 |
|                           |
| [env]                     |
|                           |
| [build_requires]          |
+---------------------------+
```

### Steps to reproduce (Include if Applicable)
Well, we are using the recipe from here to build boost. I needed to change a patch file to match a changed file (`1.69.0-locale-no-system.patch` to be specific). This all worked like a charm. Patch file are getting applied but following error comes by and I don't know why. 1.75.0 works fine.

We are building many Conan packages our-self on a Jenkins server and have a repo that is splitting the packages in several Jenkins jobs but that does not effect the way it is build.

### Logs
<details><summary>Click to expand log</summary>

```
conans.errors.ConanException: Error 1 while executing /data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/source/boost_1_77_0/tools/build/b2 target-os=linux architecture=x86 address-model=64 binary-format=elf abi=sysv --layout=system -sBOOST_BUILD_PATH=/data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/source/boost_1_77_0/tools/build --user-config=/data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/source/boost_1_77_0/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 threading=multi link=static variant=debug --without-python --without-stacktrace toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=0 cxxflags="-fPIC" -j12 --abbreviate-paths -d2 --debug-configuration --build-dir="/data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/build/f457b91cdb792d59ba52490fb19514f14fa80b63"

```

</details>

**Comment by SSE4** [comment]
the error message doesn't say much. can you try to add an option `-o boost:debug_level=1` (or higher) and capture a more complete log?

**Comment by Grafnus** [comment]
This is all I get. We are building with the Conan package tools and I am not sure how to set the option you mentioned @SSE4 

<details><summary>Click to expand log</summary>

```
boost/1.77.0@jenkins/stable: WARN: /data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/source/boost_1_77_0/tools/build/b2 target-os=linux architecture=x86 address-model=64 binary-format=elf abi=sysv --layout=system -sBOOST_BUILD_PATH=/data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/source/boost_1_77_0/tools/build --user-config=/data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/source/boost_1_77_0/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 threading=multi link=static variant=debug --without-python --without-stacktrace toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=0 cxxflags="-fPIC" -j12 --abbreviate-paths -d2 --debug-configuration --build-dir="/data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/build/f457b91cdb792d59ba52490fb19514f14fa80b63"

boost/1.77.0@jenkins/stable: ERROR: Package 'f457b91cdb792d59ba52490fb19514f14fa80b63' build failed

boost/1.77.0@jenkins/stable: WARN: Build folder /data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/build/f457b91cdb792d59ba52490fb19514f14fa80b63

Traceback (most recent call last):

  File "/data/jenkins/.local/lib/python3.8/site-packages/conans/errors.py", line 34, in conanfile_exception_formatter

    yield

  File "/data/jenkins/.local/lib/python3.8/site-packages/conans/client/conanfile/build.py", line 16, in run_build_method

    conanfile.build()

  File "/data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/export/conanfile.py", line 432, in build

    self.run(full_command)

  File "/data/jenkins/.local/lib/python3.8/site-packages/conans/model/conan_file.py", line 426, in run

    raise ConanException("Error %d while executing %s" % (retcode, command))

conans.errors.ConanException: Error 1 while executing /data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/source/boost_1_77_0/tools/build/b2 target-os=linux architecture=x86 address-model=64 binary-format=elf abi=sysv --layout=system -sBOOST_BUILD_PATH=/data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/source/boost_1_77_0/tools/build --user-config=/data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/source/boost_1_77_0/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 threading=multi link=static variant=debug --without-python --without-stacktrace toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=0 cxxflags="-fPIC" -j12 --abbreviate-paths -d2 --debug-configuration --build-dir="/data/jenkins/workspace/conan_boost/cnn_l_3/.conan/data/boost/1.77.0/jenkins/stable/build/f457b91cdb792d59ba52490fb19514f14fa80b63"


```

</details>

**Comment by DonOregano** [comment]
You can set it in the same way you set other boost options in your conanfile.

**Comment by Grafnus** [comment]
@DonOregano  I've tried to add the option like options like these `-o boost:without_fiber=True -o boost:without_stacktrace=True` are added:

The default we have:
```
options = {
        "shared": [True, False],
        "header_only": [True, False],
        "error_code_header_only": [True, False],
        "system_no_deprecated": [True, False],
        "asio_no_deprecated": [True, False],
        "filesystem_no_deprecated": [True, False],
        "fPIC": [True, False],
        "layout": ["system", "versioned", "tagged"],
        "magic_autolink": [True, False],  # enables BOOST_ALL_NO_LIB
        "python_executable": "ANY",  # system default python installation is used, if None
        "python_version": "ANY",  # major.minor; computed automatically, if None
        "namespace": "ANY",  # custom boost namespace for bcp, e.g. myboost
        "namespace_alias": [True, False],  # enable namespace alias for bcp, boost=myboost
        "zlib": [True, False],
        "bzip2": [True, False],
        "lzma": [True, False],
        "zstd": [True, False],
        "segmented_stacks": [True, False],
        "extra_b2_flags": "ANY"  # custom b2 flags
    }
    options.update({"without_%s" % libname: [True, False] for libname in lib_list})

    default_options = {
        'shared': False,
        'header_only': False,
        'error_code_header_only': False,
        'system_no_deprecated': False,
        'asio_no_deprecated': False,
        'filesystem_no_deprecated': False,
        'fPIC': True,
        'layout': 'system',
        'magic_autolink': False,
        'python_executable': 'None',
        'python_version': 'None',
        'namespace': 'boost',
        'namespace_alias': False,
        'zlib': True,
        'bzip2': True,
        'lzma': False,
        'zstd': False,
        'segmented_stacks': False,
        'extra_b2_flags': 'None',
    }

    for libname in lib_list:
        if libname != "python":
            default_options.update({"without_%s" % libname: False})
    default_options.update({"without_python": True})
    default_options.update({"without_stacktrace" : True})
```
After I edited it:
```
options = {
        "shared": [True, False],
        "header_only": [True, False],
        "error_code_header_only": [True, False],
        "system_no_deprecated": [True, False],
        "asio_no_deprecated": [True, False],
        "filesystem_no_deprecated": [True, False],
        "fPIC": [True, False],
        "layout": ["system", "versioned", "tagged"],
        "magic_autolink": [True, False],  # enables BOOST_ALL_NO_LIB
        "python_executable": "ANY",  # system default python installation is used, if None
        "python_version": "ANY",  # major.minor; computed automatically, if None
        "namespace": "ANY",  # custom boost namespace for bcp, e.g. myboost
        "namespace_alias": [True, False],  # enable namespace alias for bcp, boost=myboost
        "zlib": [True, False],
        "bzip2": [True, False],
        "lzma": [True, False],
        "zstd": [True, False],
        "segmented_stacks": [True, False],
        "extra_b2_flags": "ANY"  # custom b2 flags
    }
    options.update({"without_%s" % libname: [True, False] for libname in lib_list})

    options.update({"debug_level": "ANY"})

    default_options = {
        'debug_level': 1,
        'shared': False,
        'header_only': False,
        'error_code_header_only': False,
        'system_no_deprecated': False,
        'asio_no_deprecated': False,
        'filesystem_no_deprecated': False,
        'fPIC': True,
        'layout': 'system',
        'magic_autolink': False,
        'python_executable': 'None',
        'python_version': 'None',
        'namespace': 'boost',
        'namespace_alias': False,
        'zlib': True,
        'bzip2': True,
        'lzma': False,
        'zstd': False,
        'segmented_stacks': False,
        'extra_b2_flags': 'None',
    }

    for libname in lib_list:
        if libname != "python":
            default_options.update({"without_%s" % libname: False})
    default_options.update({"without_python": True})
    default_options.update({"without_stacktrace" : True})
```

I can find any indication that this works.

But I found some more indication in the logs:

```
...failed gcc.compile.c++ b12e06f1ae97d1271fbeda66e24afa454a9ecc9c/boost/bin.v2/libs/math/build/gcc-8/dbg/lnk-sttc/thrd-mlt/vsblt-hdn/acosh.o...
...failed gcc.compile.c++ b12e06f1ae97d1271fbeda66e24afa454a9ecc9c/boost/bin.v2/libs/math/build/gcc-8/dbg/lnk-sttc/thrd-mlt/vsblt-hdn/asinh.o...
...failed gcc.compile.c++ b12e06f1ae97d1271fbeda66e24afa454a9ecc9c/boost/bin.v2/libs/math/build/gcc-8/dbg/lnk-sttc/thrd-mlt/vsblt-hdn/atanh.o...
...failed gcc.compile.c++ b12e06f1ae97d1271fbeda66e24afa454a9ecc9c/boost/bin.v2/libs/math/build/gcc-8/dbg/lnk-sttc/thrd-mlt/vsblt-hdn/cbrt.o...
...failed gcc.compile.c++ b12e06f1ae97d1271fbeda66e24afa454a9ecc9c/boost/bin.v2/libs/math/build/gcc-8/dbg/lnk-sttc/thrd-mlt/vsblt-hdn/copysign.o...

...

...failed updating 126 targets...
...skipped 30 targets...
...updated 829 targets...



ConanException: Error 1 while executing b2 target-os=linux architecture=x86 address-model=64 binary-format=elf abi=sysv --layout=system -sBOOST_BUILD_PATH=build --user-config=user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 threading=multi link=static variant=debug --without-python --without-stacktrace toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=0 cxxflags="-fPIC" -j6 --abbreviate-paths -d2 --debug-configuration --build-dir="b12e06f1ae97d1271fbeda66e24afa454a9ecc9c"
```
I removed most of the paths and all the timestamps as it would make this more confusing

This is now a log from one of our CentOS Jenkins nodes. Ubuntu18/20 is working (for some reason). I gess the problem is something like the `cppstd` or something similar.
