### ISSUE TITLE
[package] boost/1.77.0: Error while executing b2.exe

### ISSUE THREAD

**Issue by Grafnus** [conan-io/conan-center-index#8621]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.77.0**
  * Operating System+version: **Windows Server 2019 amd64**
  * Compiler+version: **Visual Studio 2019**
  * Docker image: **Wo dont use docker**
  * Conan version: **conan 1.40.2**
  * Python version: **Python 3.8**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
+---------------------+
| Profile             |
|---------------------|
| include(default)    |
|                     |
| [settings]          |
| arch=x86_64         |
| build_type=Debug    |
| compiler.version=16 |
| [options]           |
|                     |
| [env]               |
|                     |
| [build_requires]    |
+---------------------+
```

### Steps to reproduce (Include if Applicable)

- There is no pattern to the occurrence of the issue. Its working fine on ubuntu18/20 and QNX but aarch64, centos8 and windows for vs2017 and vs2019 wont work. 
- I think this line `Boost.Locale failed to find iconv library to be built.` may be the key. But all I could find was some help for android/IOS
- We use the Conan Packge Tool as a generic way of building many conan packages on our jenkins.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
notice: [zlib] zlib is already configured

notice: [bzip2] bzip is already configured

notice: iostreams: not using lzma compression 

notice: iostreams: not using zstd compression 

Performing configuration checks

    - default address-model    : 64-bit [1]

    - default architecture     : x86 [1]

Building the Boost C++ Libraries.

    - compiler supports SSE2   : yes [2]

    - compiler supports SSE4.1 : yes [2]

    - has synchronization.lib  : yes [2]

    - has std::atomic_ref      : no [2]

    - has statx                : no [2]

    - has statx syscall        : no [2]

    - has BCrypt API           : yes [2]

    - has init_priority attribute : no [2]

    - has stat::st_blksize     : no [2]

    - has stat::st_mtim        : no [2]

    - has stat::st_mtimensec   : no [2]

    - has stat::st_mtimespec   : no [2]

    - has stat::st_birthtim    : no [2]

    - has stat::st_birthtimensec : no [2]

    - has stat::st_birthtimespec : no [2]

    - cxx11_auto_declarations  : yes [2]

    - cxx11_constexpr          : yes [2]

    - cxx11_defaulted_functions : yes [2]

    - cxx11_final              : yes [2]

    - cxx11_hdr_mutex          : yes [2]

    - cxx11_hdr_tuple          : yes [2]

    - cxx11_lambdas            : yes [2]

    - cxx11_noexcept           : yes [2]

    - cxx11_nullptr            : yes [2]

    - cxx11_rvalue_references  : yes [2]

    - cxx11_template_aliases   : yes [2]

    - cxx11_thread_local       : yes [2]

    - cxx11_variadic_templates : yes [2]

    - cxx11_auto_declarations  : yes [3]

    - cxx11_constexpr          : yes [3]

    - cxx11_defaulted_functions : yes [3]

    - cxx11_final              : yes [3]

    - cxx11_hdr_mutex          : yes [3]

    - cxx11_hdr_tuple          : yes [3]

    - cxx11_lambdas            : yes [3]

    - cxx11_noexcept           : yes [3]

    - cxx11_nullptr            : yes [3]

    - cxx11_rvalue_references  : yes [3]

    - cxx11_template_aliases   : yes [3]

    - cxx11_thread_local       : yes [3]

    - cxx11_variadic_templates : yes [3]

    - has_icu builds           : no [2]

warning: Graph library does not contain MPI-based parallel components.

note: to enable them, add "using mpi ;" to your user-config.jam.

note: to suppress this message, pass "--without-graph_parallel" to bjam.

    - zlib                     : yes [4]

    - bzip2                    : yes [4]

    - cxx11_decltype           : yes [2]

    - cxx11_basic_alignas      : yes [2]

    - iconv (libc)             : no [2]

    - iconv (separate)         : no [2]

- Boost.Locale failed to find iconv library to be built.

boost/1.77.0@jenkins/stable: 

boost/1.77.0@jenkins/stable: ERROR: Package 'a314a900b72218cbf4c851a2f869f646931afd36' build failed

boost/1.77.0@jenkins/stable: WARN: Build folder C:\cnn0\77553d\1

Traceback (most recent call last):

  File "C:\tools\Python38\lib\site-packages\conans\errors.py", line 34, in conanfile_exception_formatter

    yield

  File "C:\tools\Python38\lib\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method

    conanfile.build()

  File "C:\cnn_l_0\.conan\data\boost\1.77.0\jenkins\stable\export\conanfile.py", line 435, in build

    self.run(full_command)

  File "C:\tools\Python38\lib\site-packages\conans\model\conan_file.py", line 426, in run

    raise ConanException("Error %d while executing %s" % (retcode, command))

conans.errors.ConanException: Error 1 while executing C:\cnn0\bf2ce8\1\boost_1_77_0\tools\build\b2.exe target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system -sBOOST_BUILD_PATH=C:\cnn0\bf2ce8\1\boost_1_77_0\tools\build --user-config=C:\cnn0\bf2ce8\1\boost_1_77_0\tools\build\user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 runtime-link=shared threading=multi link=static variant=debug --without-python --without-stacktrace toolset=msvc  -j10 --abbreviate-paths -d2 --debug-configuration --build-dir="C:\cnn0\77553d\1"



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "C:\jenkins2\workspace\conan_boost\generic_build.py", line 75, in <module>

    builder.run()

  File "C:\tools\Python38\lib\site-packages\cpt\packager.py", line 585, in run

    self.run_builds(base_profile_name=base_profile_name,

  File "C:\tools\Python38\lib\site-packages\cpt\packager.py", line 698, in run_builds

    r.run()

  File "C:\tools\Python38\lib\site-packages\cpt\runner.py", line 145, in run

    self._results = self._conan_api.create(self._conanfile, name=name, version=version,

  File "C:\tools\Python38\lib\site-packages\conans\client\conan_api.py", line 93, in wrapper

    return f(api, *args, **kwargs)

  File "C:\tools\Python38\lib\site-packages\conans\client\conan_api.py", line 388, in create

    create(self.app, ref, graph_info, remotes, update, build_modes,

  File "C:\tools\Python38\lib\site-packages\conans\client\cmd\create.py", line 83, in create

    deps_install(app=app,

  File "C:\tools\Python38\lib\site-packages\conans\client\manager.py", line 82, in deps_install

    installer.install(deps_graph, remotes, build_modes, update, profile_host, profile_build,

  File "C:\tools\Python38\lib\site-packages\conans\client\installer.py", line 316, in install

    self._build(nodes_by_level, keep_build, root_node, profile_host, profile_build,

  File "C:\tools\Python38\lib\site-packages\conans\client\installer.py", line 451, in _build

    self._handle_node_cache(node, keep_build, processed_package_refs, remotes)

  File "C:\tools\Python38\lib\site-packages\conans\client\installer.py", line 541, in _handle_node_cache

    pref = self._build_package(node, output, keep_build, remotes)

  File "C:\tools\Python38\lib\site-packages\conans\client\installer.py", line 580, in _build_package

    pref = builder.build_package(node, keep_build, self._recorder, remotes)

  File "C:\tools\Python38\lib\site-packages\conans\client\installer.py", line 239, in build_package

    raise exc

  File "C:\tools\Python38\lib\site-packages\conans\client\installer.py", line 226, in build_package

    self._build(conanfile, pref)

  File "C:\tools\Python38\lib\site-packages\conans\client\installer.py", line 155, in _build

    raise exc

  File "C:\tools\Python38\lib\site-packages\conans\client\installer.py", line 147, in _build

    run_build_method(conanfile, self._hook_manager, reference=pref.ref, package_id=pref.id)

  File "C:\tools\Python38\lib\site-packages\conans\client\conanfile\build.py", line 16, in run_build_method

    conanfile.build()

  File "C:\tools\Python38\lib\contextlib.py", line 131, in __exit__

    self.gen.throw(type, value, traceback)

  File "C:\tools\Python38\lib\site-packages\conans\errors.py", line 40, in conanfile_exception_formatter

    raise ConanExceptionInUserConanfileMethod(msg)

conans.errors.ConanExceptionInUserConanfileMethod: boost/1.77.0@jenkins/stable: Error in build() method, line 435

	self.run(full_command)

	ConanException: Error 1 while executing C:\cnn0\bf2ce8\1\boost_1_77_0\tools\build\b2.exe target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system -sBOOST_BUILD_PATH=C:\cnn0\bf2ce8\1\boost_1_77_0\tools\build --user-config=C:\cnn0\bf2ce8\1\boost_1_77_0\tools\build\user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 runtime-link=shared threading=multi link=static variant=debug --without-python --without-stacktrace toolset=msvc  -j10 --abbreviate-paths -d2 --debug-configuration --build-dir="C:\cnn0\77553d\1"

script returned exit code 1
```

</details>

**Comment by Wuestenschiff** [comment]
Having the same issue on MAcOS trying to build boost 1.77

```
conan profile show  build/macos-clang-libstdc++-release/release/conan/cg-conan-Release.profile
Configuration for profile build/macos-clang-libstdc++-release/release/conan/cg-conan-Release.profile:

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=12
os=Macos
os.sdk=macosx
os.version=12.0
os_build=Macos
[options]
[conf]
tools.cmake.cmaketoolchain:user_toolchain=<path_on_my_system>/external/cmake-general/cmake-general/conan/profiles/../../toolchains/macos/clang-libstdc++.cmake
[build_requires]
[env]
CC=/usr/local/opt/llvm@12/bin/clang
CXX=/usr/local/opt/llvm@12/bin/clang++
CXXFLAGS=-stdlib++-isystem/usr/local/opt/gcc@11/include/c++/11 -cxx-isystem/usr/local/opt/gcc@11/include/c++/11/x86_64-apple-darwin20 -L/usr/local/opt/gcc@11/lib/gcc/11 -Wno-unused-command-line-argument
```
