### ISSUE TITLE
[package] qt/5.15.2: Error building 3rd party libraries for qtwebengine module

### ISSUE THREAD

**Issue by MartinDelille** [conan-io/conan-center-index#9103]
obj/third_party/boringssl/libboringssl.a

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.15.2**
  * Operating System+version: **MacOS 11.6.2**
  * Compiler+version: **apple-clang 13.0**
  * Docker image: **N//A**
  * Conan version: **conan 1.44.1**
  * Python version: **Python 3.9.6**

### Conan profile

```
$ conan profile show default
Configuration for profile default:

[settings]
os=Macos
os.version=10.14
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=13.0
compiler.libcxx=libc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Given the following `conanfile.txt`:

```toml
[requires]
qt/5.15.2@

[options]
qt:shared=True
qt:qtlocation=True
qt:qtwebchannel=True
qt:qtwebengine=True

[generators]
virtualrunenv
qt
```

When runnig `conan install conanfile.txt -s build_type=Debug -b qt` I have a compilation error (see log below).

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
$ conan install .. -s build_type=Debug -b qt
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13.0
os=Macos
os.version=10.14
os_build=Macos
[options]
[build_requires]
[env]

qt/5.15.2: Forced build from source
qt/5.15.2: Found valid Python 2 required for QtWebengine: version=Python 2.7.16
, path=/usr/bin/python2
conanfile.txt: Installing package
Requirements
    brotli/1.0.9 from 'conancenter' - Cache
    bzip2/1.0.8 from 'conancenter' - Cache
    double-conversion/3.1.5 from 'conancenter' - Cache
    freetype/2.10.4 from 'conancenter' - Cache
    libiconv/1.16 from 'conancenter' - Cache
    libjpeg/9d from 'conancenter' - Cache
    libmysqlclient/8.0.25 from 'conancenter' - Cache
    libpng/1.6.37 from 'conancenter' - Cache
    libpq/13.2 from 'conancenter' - Cache
    lz4/1.9.3 from 'conancenter' - Cache
    odbc/2.3.9 from 'conancenter' - Cache
    opengl/system from 'conancenter' - Cache
    openssl/1.1.1k from 'conancenter' - Cache
    pcre2/10.37 from 'conancenter' - Cache
    qt/5.15.2 from 'conancenter' - Cache
    sqlite3/3.36.0 from 'conancenter' - Cache
    zlib/1.2.11 from 'conancenter' - Cache
    zstd/1.5.0 from 'conancenter' - Cache
Packages
    brotli/1.0.9:32d688fc084e69d947b4aa34e442ca8fdd561309 - Cache
    bzip2/1.0.8:ef3ea4cc23dace4eece7cb3054285b6746ef1952 - Cache
    double-conversion/3.1.5:377bd9190d33fb990efb2f4d0ca7db7f5ad7a5e3 - Cache
    freetype/2.10.4:ca3112a541ac99c78955cbba159e3639e3e88e51 - Cache
    libiconv/1.16:32d688fc084e69d947b4aa34e442ca8fdd561309 - Cache
    libjpeg/9d:32d688fc084e69d947b4aa34e442ca8fdd561309 - Cache
    libmysqlclient/8.0.25:da962f7ed8eed8dfff63e294e76dd8510617e0fd - Cache
    libpng/1.6.37:515a910d2733a7afead573cfdfa90f6f0d5be98e - Cache
    libpq/13.2:32d688fc084e69d947b4aa34e442ca8fdd561309 - Cache
    lz4/1.9.3:32d688fc084e69d947b4aa34e442ca8fdd561309 - Cache
    odbc/2.3.9:61cf9bb3928ff1b0aa05b1074c88cb0a7b7b17d6 - Cache
    opengl/system:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    openssl/1.1.1k:32d688fc084e69d947b4aa34e442ca8fdd561309 - Cache
    pcre2/10.37:4bb0e68107ac1c6f503df7bcecd0f7514f2c243f - Cache
    qt/5.15.2:0979a304eba4c0c254df80a7729dc6c51a76eab5 - Build
    sqlite3/3.36.0:4a2bd41cf662ee085a62f011cb5f8df244ef12d0 - Cache
    zlib/1.2.11:32d688fc084e69d947b4aa34e442ca8fdd561309 - Cache
    zstd/1.5.0:32d688fc084e69d947b4aa34e442ca8fdd561309 - Cache
Build requirements
    bison/3.7.1 from 'conancenter' - Cache
    flex/2.6.4 from 'conancenter' - Cache
    gperf/3.1 from 'conancenter' - Cache
    m4/1.4.19 from 'conancenter' - Cache
    ninja/1.10.2 from 'conancenter' - Cache
Build requirements packages
    bison/3.7.1:b1a77ddf2a3381534ffd06bf8cdc4a83dce7cfa8 - Cache
    flex/2.6.4:b1a77ddf2a3381534ffd06bf8cdc4a83dce7cfa8 - Cache
    gperf/3.1:f54a620aa455095aed150c6410771011a4d4b50f - Cache
    m4/1.4.19:f54a620aa455095aed150c6410771011a4d4b50f - Cache
    ninja/1.10.2:f54a620aa455095aed150c6410771011a4d4b50f - Cache

Installing (downloading, building) binaries...
brotli/1.0.9: Already installed!
bzip2/1.0.8: Already installed!
bzip2/1.0.8: Appending PATH environment variable: /Users/martin/.conan/data/bzip2/1.0.8/_/_/package/ef3ea4cc23dace4eece7cb3054285b6746ef1952/bin

...

1 warning generated.
[5262/22351] OBJCXX obj/third_party/mozilla/mozilla/NSString+Utils.o
../../../../../../../source/qt5/qtwebengine/src/3rdparty/chromium/third_party/mozilla/NSString+Utils.mm:356:39: warning: 'CFURLCreateStringByReplacingPercentEscapesUsingEncoding' is deprecated: first deprecated in macOS 10.11 - Use [NSString stringByRemovingPercentEncoding] or CFURLCreateStringByReplacingPercentEscapes() instead, which always uses the recommended UTF-8 encoding. [-Wdeprecated-declarations]
  NSString *unescapedURI = (NSString*)CFURLCreateStringByReplacingPercentEscapesUsingEncoding(kCFAllocatorDefault,
                                      ^
../../../../../../../../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:393:13: note: 'CFURLCreateStringByReplacingPercentEscapesUsingEncoding' has been explicitly marked deprecated here
CFStringRef CFURLCreateStringByReplacingPercentEscapesUsingEncoding(CFAllocatorRef allocator, CFStringRef origString, CFStringRef charsToLeaveEscaped, CFStringEncoding encoding) API_DEPRECATED("Use [NSString stringByRemovingPercentEncoding] or CFURLCreateStringByReplacingPercentEscapes() instead, which always uses the recommended UTF-8 encoding.", macos(10.0,10.11), ios(2.0,9.0), watchos(2.0,2.0), tvos(9.0,9.0));
            ^
1 warning generated.
[5913/22351] LIBTOOL-STATIC obj/third_party/icu/libbundled_icuuc.a
FAILED: obj/third_party/icu/libbundled_icuuc.a
rm -f obj/third_party/icu/libbundled_icuuc.a && TOOL_VERSION=1604712156 python ../../../../../../../source/qt5/qtwebengine/src/3rdparty/chromium/build/toolchain/mac/filter_libtool.py /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static  -o obj/third_party/icu/libbundled_icuuc.a -filelist obj/third_party/icu/libbundled_icuuc.a.rsp
Traceback (most recent call last):
  File "/Users/martin/.conan/data/qt/5.15.2/_/_/build/0979a304eba4c0c254df80a7729dc6c51a76eab5/build_folder/qtwebengine/src/core/debug/../../../../../../../source/qt5/qtwebengine/src/3rdparty/chromium/build/toolchain/mac/filter_libtool.py", line 56, in <module>
    sys.exit(Main(sys.argv[1:]))
  File "/Users/martin/.conan/data/qt/5.15.2/_/_/build/0979a304eba4c0c254df80a7729dc6c51a76eab5/build_folder/qtwebengine/src/core/debug/../../../../../../../source/qt5/qtwebengine/src/3rdparty/chromium/build/toolchain/mac/filter_libtool.py", line 43, in Main
    if not IsBlacklistedLine(line):
  File "/Users/martin/.conan/data/qt/5.15.2/_/_/build/0979a304eba4c0c254df80a7729dc6c51a76eab5/build_folder/qtwebengine/src/core/debug/../../../../../../../source/qt5/qtwebengine/src/3rdparty/chromium/build/toolchain/mac/filter_libtool.py", line 28, in IsBlacklistedLine
    if pattern.match(line):
TypeError: cannot use a string pattern on a bytes-like object
[5922/22351] CXX obj/third_party/boringssl/boringssl/handoff.o
ninja: build stopped: subcommand failed.
make[4]: *** [run_ninja] Error 1
make[3]: *** [sub-gn_run-pro-make_first] Error 2
make[2]: *** [sub-core-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtwebengine-make_first] Error 2
qt/5.15.2:
qt/5.15.2: ERROR: Package '0979a304eba4c0c254df80a7729dc6c51a76eab5' build failed
qt/5.15.2: WARN: Build folder /Users/martin/.conan/data/qt/5.15.2/_/_/build/0979a304eba4c0c254df80a7729dc6c51a76eab5
ERROR: qt/5.15.2: Error in build() method, line 702
	self.run(self._make_program(), run_environment=True)
	ConanException: Error 2 while executing DYLD_LIBRARY_PATH="/Users/martin/.conan/data/bison/3.7.1/_/_/package/b1a77ddf2a3381534ffd06bf8cdc4a83dce7cfa8/lib:/Users/martin/.conan/data/flex/2.6.4/_/_/package/b1a77ddf2a3381534ffd06bf8cdc4a83dce7cfa8/lib:/Users/martin/.conan/data/pcre2/10.37/_/_/package/4bb0e68107ac1c6f503df7bcecd0f7514f2c243f/lib:/Users/martin/.conan/data/double-conversion/3.1.5/_/_/package/377bd9190d33fb990efb2f4d0ca7db7f5ad7a5e3/lib:/Users/martin/.conan/data/freetype/2.10.4/_/_/package/ca3112a541ac99c78955cbba159e3639e3e88e51/lib:/Users/martin/.conan/data/libjpeg/9d/_/_/package/32d688fc084e69d947b4aa34e442ca8fdd561309/lib:/Users/martin/.conan/data/sqlite3/3.36.0/_/_/package/4a2bd41cf662ee085a62f011cb5f8df244ef12d0/lib:/Users/martin/.conan/data/libmysqlclient/8.0.25/_/_/package/da962f7ed8eed8dfff63e294e76dd8510617e0fd/lib:/Users/martin/.conan/data/libpq/13.2/_/_/package/32d688fc084e69d947b4aa34e442ca8fdd561309/lib:/Users/martin/.conan/data/odbc/2.3.9/_/_/package/61cf9bb3928ff1b0aa05b1074c88cb0a7b7b17d6/lib:/Users/martin/.conan/data/openssl/1.1.1k/_/_/package/32d688fc084e69d947b4aa34e442ca8fdd561309/lib:/Users/martin/.conan/data/bzip2/1.0.8/_/_/package/ef3ea4cc23dace4eece7cb3054285b6746ef1952/lib:/Users/martin/.conan/data/libpng/1.6.37/_/_/package/515a910d2733a7afead573cfdfa90f6f0d5be98e/lib:/Users/martin/.conan/data/brotli/1.0.9/_/_/package/32d688fc084e69d947b4aa34e442ca8fdd561309/lib:/Users/martin/.conan/data/zstd/1.5.0/_/_/package/32d688fc084e69d947b4aa34e442ca8fdd561309/lib:/Users/martin/.conan/data/lz4/1.9.3/_/_/package/32d688fc084e69d947b4aa34e442ca8fdd561309/lib:/Users/martin/.conan/data/libiconv/1.16/_/_/package/32d688fc084e69d947b4aa34e442ca8fdd561309/lib:/Users/martin/.conan/data/zlib/1.2.11/_/_/package/32d688fc084e69d947b4aa34e442ca8fdd561309/lib" DYLD_FRAMEWORK_PATH="" make
```

</details>

**Comment by MartinDelille** [comment]
I cross posted the issue here: https://bugreports.qt.io/browse/QTBUG-100252

**Comment by MartinDelille** [comment]
After speaking with the Qt developers and @ericLemanissier, I was able to build qt with qtwebengine 5.15.8 with this conanfile.txt:

```
[requires]
qt/5.15.2@

[options]
qt:shared=True
qt:qtlocation=True
qt:qtwebchannel=True
qt:qtwebengine=True
qt:config=--no-feature-webengine-jumbo-build

[generators]
virtualrunenv
qt
```

I don't have any idea how I could use qtwebengine 5.15.8 though.

**Comment by ericLemanissier** [comment]
qt 5.15.13 was just released on CCI. could you try it ? Do you know which version of qt/which patchset fixed your issue ?

**Comment by MartinDelille** [comment]
Here is the error I have with qt 5.15.3:

```
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> >::shrink_to_fit()", referenced from:
      base::UTF8ToUTF16(char const*, unsigned long, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> >*) in libbase.a(base_jumbo_20.o)
      base::WideToUTF16(wchar_t const*, unsigned long, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> >*) in libbase.a(base_jumbo_20.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "../../../../../../../source/qt5/qtwebengine/src/3rdparty/chromium/build/toolchain/mac/linker_driver.py", line 307, in <module>
    Main(sys.argv)
  File "../../../../../../../source/qt5/qtwebengine/src/3rdparty/chromium/build/toolchain/mac/linker_driver.py", line 97, in Main
    subprocess.check_call(compiler_driver_args, env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../../../../../../../../../../../../../../../Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++', '-B', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/', '-Wl,-fatal_warnings', '-stdlib=libc++', '-arch', 'x86_64', '-Wl,-no_data_in_code_info', '-Wl,-no_function_starts', '-isysroot', '../../../../../../../../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk', '-mmacosx-version-min=10.13', '-Wl,-ObjC', '-o', './character_data_generator', '-Wl,-filelist,./character_data_generator.rsp', '-framework', 'ApplicationServices', '-framework', 'AppKit', '-framework', 'CoreFoundation', '-framework', 'IOKit', '-framework', 'OpenDirectory', '-framework', 'Security', '-framework', 'Foundation', '-lbsm', '-lpmenergy', '-lpmsample']' returned non-zero exit status 1
[10794/23964] CXX obj/third_party/webrtc/media/rtc_audio_video/webrtc_video_engine.o
ninja: build stopped: subcommand failed.
make[4]: *** [run_ninja] Error 1
make[3]: *** [sub-gn_run-pro-make_first] Error 2
```

**Comment by ericLemanissier** [comment]
@MartinDelille can you try with https://github.com/conan-io/conan-center-index/pull/9897 ?

**Comment by MartinDelille** [comment]
qtwebengine compilation is sooooo long!!! 😭

**Comment by MartinDelille** [comment]
I finally manage to build successfully qt + webengine on my machine ! Thank you for you helping this to happens!
