### ISSUE TITLE
[package] meson/0.60.2: PermissionError on Windows

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan-center-index#9633]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **meson/0.60.2**
  * Operating System+version: **Windows 10 21H1 19043.1526**
  * Compiler+version: **Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30706 for x86**
  * Docker image: **NA**
  * Conan version: **conan 1.45.0**
  * Python version: **Python 3.9.7**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

`conan create . meson/0.60.2@ -k`

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: Traceback (most recent call last):
  File "c:\conan\conan\conans\errors.py", line 34, in conanfile_exception_formatter
    yield
  File "c:\conan\conan\conans\client\conanfile\package.py", line 52, in _call_package
    conanfile.package()
  File "C:\Users\sse4\.conan\data\meson\0.60.2\_\_\export\conanfile.py", line 46, in package
    self.copy(pattern="*", dst="bin", src=self._source_subfolder)
  File "c:\conan\conan\conans\client\file_copier.py", line 84, in __call__
    fs = self._copy(src_folder, pattern, src, dst, links, ignore_case, excludes,
  File "c:\conan\conan\conans\client\file_copier.py", line 103, in _copy
    copied_files = self._copy_files(files_to_copy, src, dst, keep_path, symlinks)
  File "c:\conan\conan\conans\client\file_copier.py", line 240, in _copy_files
    shutil.copy2(abs_src_name, abs_dst_name)
  File "C:\Users\sse4\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 443, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\sse4\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\sse4\\.conan\\data\\meson\\0.60.2\\_\\_\\source\\source_subfolder\\test cases\\frameworks\\35 boost symlinks\\boost\\include\\boost'
```

</details>

slack: https://cpplang.slack.com/archives/C41CWV9HA/p1646591477768949

**Comment by SSE4** [comment]
broken link looks like:
```
03/07/2022  02:12 AM    <SYMLINKD>     boost [../Cellar/boost/0.3.0/include/boost]   
```
might be related to https://bugs.python.org/issue13702

**Comment by SSE4** [comment]
a simple workaround:
```
diff --git a/recipes/meson/all/conanfile.py b/recipes/meson/all/conanfile.py
index 4eecbc453..1a5610ee5 100644
--- a/recipes/meson/all/conanfile.py
+++ b/recipes/meson/all/conanfile.py
@@ -42,6 +42,20 @@ class MesonInstallerConan(ConanFile):
             os.chmod(filename, os.stat(filename).st_mode | 0o111)

     def package(self):
+        def _fix_symlinks(root, files):
+            for filename in files:
+                filename = os.path.join(root, filename)
+                if os.path.islink(filename):
+                    target = os.readlink(filename)
+                    if "/" in target:
+                        self.output.info("fixing broken link {}".format(target))
+                        target = target.replace("/", "\\")
+                        os.unlink(filename)
+                        os.symlink(target, filename)
+
+        for root, dirs, files in os.walk(self.source_folder, self._source_subfolder):
+            _fix_symlinks(root, dirs)
+            _fix_symlinks(root, files)
         self.copy(pattern="COPYING", dst="licenses", src=self._source_subfolder)
         self.copy(pattern="*", dst="bin", src=self._source_subfolder)
         tools.rmdir(os.path.join(self.package_folder, "bin", "test cases"))
```

**Comment by perseoGI** [comment]
Hi there, 
I was reviewing old issues and I have come across this one.
The `meson/0.60.2` version is no longer supported by Conan Center Index.

I'm closing this issue as this recipe has suffer plenty of modifications since this issue was reported.
If for some reason the problem remains nowadays, do not hesitate to reopen this issue or create a new ticket with updated information, preferably using `conan v2`.

Happy coding 🐸
